---
title: "Main Finding of outliers through Interceptor"
author: "Marlin"
date: "3/15/2022"
params:
  BaseDir: "Z:/"
output: 
  bookdown::html_document2: 
    fig_width: 8
    fig_height: 4
    code_folding: hide
editor_options: 
  chunk_output_type: inline
---


```{r set up markdown settings, echo=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE
)
```


```{r Start enviroment, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)
library(lmtest)
library(lubridate)
library(limma)
library(tidyr)
library(plotly)
library(gridExtra)
library(data.table)
library(formattable)
library(ggpubr)

#Data Files and prep work
source("../../lib/DataProccess.R")
source("../../lib/NormFuncs.R")
source("../../lib/OutlierDetectionFuncs.R")
source("../../lib/DataPathName.R")
BaseDir <- params$BaseDir#get the root of the directory where the data is stored
```

```{r helpful data manipulations, include = FALSE}

SecondAxisFormat <- list(#Second Axis components
  tickfont = list(size=11.7),
  titlefont=list(size=14.6),
  overlaying = "y",
  nticks = 4,
  dtick = 5e5,
  side = "right",
  title = "N1 (GC/L)",
  exponentformat = "e"
)
```


"Files Used: "

`r LIMSCasePath(BaseDir)`

`r LIMSWastePath(BaseDir)`


```{r DF Set Up, echo=FALSE}


#Importing the Madison case data
LatCaseDF <- ParseData(LIMSCasePath(BaseDir))%>% 
  mutate(SevenDayMACases = rollapply(data = FirstConfirmed, width = 7, FUN = mean, 
                            na.rm = TRUE,fill=NA))%>%
  filter(Date>ymd("2020-9-10"))%>%
  select(Date, Site, FirstConfirmed,SevenDayMACases)
SiteData <- unique(LatCaseDF$Site)

#Importing the Madison waste water data
LIMSFullDF <- ParseData(LIMSWastePath(BaseDir))%>%
  filter(Site %in% SiteData)%>%
  mutate(N1Pure = ifelse(is.na(N1),N1,N1),
         N1Pure = ifelse(is.na(N1),N1,N1),
         GeoMeanN12 = exp((log(N1Pure)+log(N1Pure))/2))%>%
  select(Date, Site, N1, BCoV , N2 , PMMoV,
         GeoMeanN12,FlowRate,temperature,equiv_sewage_amt)

#joining the two data frames together
FullDF <- full_join(LatCaseDF,LIMSFullDF, by = c("Date","Site"))%>%
  mutate(Pop = case_when(
    Site=="MMSD-P2" ~ 83127,#111967
    Site=="MMSD-P7" ~ 42734, #81977
    Site=="MMSD-P8" ~ 70024,#127634
    Site=="MMSD-P11" ~ 156651,#130799
    Site=="MMSD-P18" ~ 89139,#151470
    Site=="Madison" ~ 441675,#603847
  ))
```


```{r Outlier}
SizeUsed = 1
alphaUsed = .9
N1ShapeUnit = 4
N2ShapeUnit = 5

MadDF <- filter(FullDF,Site=="Madison")%>%
    mutate(FlagedOutliersN1 = IdentifyOutliers(N1,Bin = 21, Action = "Flag"),
           FlagedOutliersN2 = IdentifyOutliers(N2,Bin = 21, Action = "Flag"),
           NoOutlierVarN1 = ifelse(FlagedOutliersN1, NA, N1),
           NoOutlierVarN2 = ifelse(FlagedOutliersN2, NA, N2),)


NonOuliersDF <- MadDF%>%
  mutate(Outlier = ifelse(FlagedOutliersN1,N1,NA))%>%
           mutate(N1 = NoOutlierVarN1,
                  N2 = NoOutlierVarN2)

OutLierPlotDF <- MadDF%>%
  mutate(OutlierN1 = ifelse(FlagedOutliersN1,N1,NA),
         OutlierN2 = ifelse(FlagedOutliersN2,N2,NA))%>%
           mutate(N1 = NoOutlierVarN1,
                  N2 = NoOutlierVarN2)%>%
  #filter(!(is.na(N1)&is.na(Outlier)))%>%
  ggplot(aes(x=Date))+#Data depends on time 
  geom_point(aes(y=N1,
                color="N1", 
                info = N1),data=NonOuliersDF,size=.5)+#compares N1
  geom_point(aes(y=N2,
                color="N2", 
                info = N2),data=NonOuliersDF,size=.5)+#compares N1
  geom_point(aes(y=OutlierN1,
                 color="N1 Outlier",
                 info = OutlierN1))+
  geom_point(aes(y=OutlierN2,
                 color="N2 Outlier",
                 info = OutlierN2))+
  theme_light()# +
  #scale_y_log10()+
  #scale_color_manual(values=c("#F8766D","#999999"))

ggplotly(OutLierPlotDF)
#"2021-06-08","2021-10-17","2021-05-02","2021-01-26"
#make shape, not color change
#jittering



```



```{r N1 Normalizer, dpi = 100}
IntercepterDF <- FullDF %>%
  group_by(Site)%>%
  mutate(FudgeFactor = mean(N1))%>%#Mean of sites to see if it works as normalizer
  filter(Site != "Madison") #We are looking for agreement between the interceptors
                            #after some normalization so Madison just distracts




IntercepterOverLay <- IntercepterDF%>%
  ggplot(aes(x=Date))+
  geom_point(aes(y=N1,color = Site),size = SizeUsed, alpha= alphaUsed,shape=N1ShapeUnit)+
  geom_point(aes(y=N2,color = Site),size = SizeUsed, alpha= alphaUsed,shape=N2ShapeUnit)+
  theme_light() +
  scale_y_log10()

ggplotly(IntercepterOverLay)


IntercepterOverLayFlow <- IntercepterDF%>%
  ggplot(aes(x=Date))+
  geom_point(aes(y=N1*FlowRate,color = Site),size = SizeUsed, alpha= alphaUsed,shape=N1ShapeUnit)+
  geom_point(aes(y=N2*FlowRate,color = Site),size = SizeUsed, alpha= alphaUsed,shape=N2ShapeUnit)+
  theme_light() +
  scale_y_log10()

ggplotly(IntercepterOverLayFlow)


IntercepterOverLayPop <- IntercepterDF%>%
  ggplot(aes(x=Date))+
  geom_point(aes(y=N1/Pop,color = Site),size = SizeUsed, alpha= alphaUsed,shape=N1ShapeUnit)+
  geom_point(aes(y=N2/Pop, color = Site),size = SizeUsed, alpha= alphaUsed,shape=N2ShapeUnit)+
  theme_light() +
  scale_y_log10()

ggplotly(IntercepterOverLayPop)

#Get P18 to pop out
```

```{r Ranking}
TieMethod <- "average"

IntercepterDF%>%
  ggplot()+
  geom_histogram(aes(x=log(N1)),bins=15)+
  facet_wrap(~Site)

IntercepterCoreDF <- IntercepterDF%>%
  filter(!is.na(N1))%>%
  group_by(Date)%>%
  filter(n()==5)


IntercepterCoreDF%>%
  group_by(Date)%>%
  mutate(Ranking = frank(N1,ties.method = TieMethod))%>%
  group_by(Site)%>%
  summarize(N1AverageRanking = mean(Ranking, na.rm = TRUE))

IntercepterCoreDF%>%
  group_by(Date)%>%
  mutate(Ranking = frank(N1*FlowRate, ties.method = TieMethod))%>%
  group_by(Site)%>%
  summarize(N1FlowAverageRanking = mean(Ranking, na.rm = TRUE))

IntercepterCoreDF%>%
  group_by(Date)%>%
  mutate(Ranking = frank(N1/Pop,ties.method = TieMethod))%>%
  group_by(Site)%>%
  summarize(N1PopAverageRanking = mean(Ranking, na.rm = TRUE))


IntercepterCoreDF%>%
  group_by(Date)%>%
  mutate(Ranking = frank(N1, ties.method = TieMethod))%>%
  group_by(Site,Ranking)%>%
  ggplot()+
  geom_histogram(aes(x=Ranking,fill=Site),position = "dodge")


#Redo without P18 || The problamatic months
#Compare results between normalizations
```


```{r Per Change}
IntercepterChangeDF <- IntercepterDF%>%
  filter(!is.na(N1))%>%
  mutate(ChangeN1 = lead(N1) - N1,
         ChangeN2 = lead(N2) - N2,
         PerChangeN1 = log(lead(N1) - N1),
         PerChangeN2 = log(lead(N2) - N2))


IntercepterChangeOverLay <- IntercepterChangeDF%>%
  ggplot(aes(x=Date))+
  geom_point(aes(y = ChangeN1, color = Site), size = SizeUsed,
             alpha = alphaUsed, shape=N1ShapeUnit)+
  geom_point(aes(y = ChangeN2,color = Site), size = SizeUsed,
             alpha = alphaUsed, shape = N2ShapeUnit)+
  theme_light()#+
  #scale_y_log10()

ggplotly(IntercepterChangeOverLay)

IntercepterPerChangeOverLay <- IntercepterChangeDF%>%
  ggplot(aes(x = Date))+
  geom_point(aes(y = PerChangeN1, color = Site), size = SizeUsed,
             alpha = alphaUsed, shape = N1ShapeUnit)+
  geom_point(aes(y = PerChangeN2, color = Site), size = SizeUsed,
             alpha= alphaUsed,shape = N2ShapeUnit)+
  theme_light()#+
  #scale_y_log10()

ggplotly(IntercepterPerChangeOverLay)
```


```{r Loess smoothing plot}
LoessFunc <- function(SiteFilter,DF,SpanConstant = .163){
  MainDF <- DF%>%
    filter(Site==SiteFilter)
  MainDF[["loessN1"]] <- loessFit(y=(MainDF[["N1"]]), 
                      x=MainDF$Date, #create loess fit of the data
                      span=SpanConstant, #span of .2 seems to give the best result, not rigorously chosen
                      iterations=5)$fitted#2 iterations remove some bad patterns
return(MainDF)
}

SiteLoessDF <- lapply(c("MMSD-P11","MMSD-P18","MMSD-P2","MMSD-P7","MMSD-P8"),
                      LoessFunc,IntercepterDF,SpanConstant=.2)%>%
                bind_rows()

A <- SiteLoessDF%>%
  filter(!is.na(loessN1))%>%
  ggplot(aes(x=Date))+
  geom_point(aes(y=N1,color=Site),data=IntercepterDF,size=.5,alpha=.5)+
  geom_line(aes(y=loessN1,color=Site))+
  scale_y_log10()
ggplotly(A)

#Facet by normalizations, log/non log, orderered
#landscape 3 by 1
#Thumbnails
#Combine with N2?
#For comparisions we dont need points
```

```{r SLD smoothing plot}
Mean <- 11.73
StandardDeviation <- 7.68
Scale = StandardDeviation^2/Mean
Shape = Mean/Scale
SLDWidth <- 21
weights <- dgamma(1:SLDWidth, scale = Scale, shape = Shape)

SiteLoessDF <- FullDF%>%
  group_by(Site)%>%
  arrange(Site,Date)%>%
  filter(Site!="Madison")%>%
  mutate(SevDayCases = rollmean(x = FirstConfirmed, 7, fill=0))%>%
  arrange(Site,Date)%>%
  group_by(Site)#%>%
  #mutate(SLDCases = c(rep(NA, SLDWidth-1),
  #                      rollapply(FirstConfirmed, width=SLDWidth, FUN=weighted.mean, 
  #                               w=weights,
  #                               na.rm = FALSE)))

A <- SiteLoessDF%>%
  filter(!is.na(SevDayCases),
         SevDayCases != 0)%>%
  ggplot(aes(x=Date))+
  geom_point(aes(y = FirstConfirmed, color = Site, shape = Site), 
             data = IntercepterDF, size = .5, alpha = .5)+
  geom_line(aes(y = SevDayCases, color = Site))+
  #geom_line(aes(y = SLDCases, color = Site))+
  scale_y_log10()
ggplotly(A)

B <- SiteLoessDF%>%
  filter(!is.na(SevenDayMACases),
         SevDayCases != 0)%>%
  ggplot(aes(x=Date))+
  geom_point(aes(y = FirstConfirmed / Pop, color = Site, shape = Site), 
             data = IntercepterDF, size = .5, alpha = .5)+
  geom_line(aes(y = SevDayCases / Pop, color = Site))+
  #geom_line(aes(y = SLDCases / Pop, color = Site))+
  scale_y_log10()
ggplotly(B)
```
