---
title: "Main Finding of outliers through Interceptor Non Interactive plots"
author: "Marlin"
date: "3/15/2022"
params:
  BaseDir: "Z:/"
output: pdf_document
editor_options: 
  chunk_output_type: inline
---


```{r set up markdown settings, echo=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	echo = FALSE
)
```


```{r Start enviroment, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(lubridate)
library(zoo)
library(ggplot2)
library(plotly)
library(limma)
library(ggpubr)


#Data Files and prep work
source("../../lib/DataProccess.R")
source("../../lib/NormFuncs.R")
source("../../lib/OutlierDetectionFuncs.R")
source("../../lib/DataPathName.R")
BaseDir <- params$BaseDir#get the root of the directory where the data is stored
```


"Files Used: "

`r LIMSCasePath(BaseDir)`

`r LIMSWastePath(BaseDir)`


```{r DF Set Up, echo=FALSE}
#SLD Info
Mean <- 11.73
StandardDeviation <- 7.68
Scale = StandardDeviation^2/Mean
Shape = Mean/Scale
SLDWidth <- 21
weights <- dgamma(1:SLDWidth, scale = Scale, shape = Shape)


#Importing the Madison case data
LatCaseDF <- ParseData(LIMSCasePath(BaseDir))%>% 
  mutate(FirstConfirmed = ifelse(is.na(FirstConfirmed),0,FirstConfirmed))%>%
  arrange(Site,Date)%>%
  group_by(Site)%>%
  mutate(SevenDayMACases = rollapply(FirstConfirmed, width = 7, FUN = mean, 
                                     fill = NA, na.rm = TRUE),
         SLDCases = rollapply(FirstConfirmed, width=SLDWidth,FUN=weighted.mean,
                                  w=weights, fill = NA, na.rm = TRUE))%>%
  filter(Date>ymd("2020-8-10"))%>%
  select(Date, Site, FirstConfirmed,SevenDayMACases, SLDCases)

SiteData <- unique(LatCaseDF$Site)

#Importing the Madison waste water data
LIMSFullDF <- ParseData(LIMSWastePath(BaseDir))%>%
  filter(Site %in% SiteData)%>%
  mutate(N1Pure = ifelse(is.na(N1),N1,N1),
         N1Pure = ifelse(is.na(N1),N1,N1),
         GeoMeanN12 = exp((log(N1Pure)+log(N1Pure))/2))%>%
  mutate(SC2_mass = (3.785*1e6)*FlowRate*N1)%>%
  select(Date, Site, N1, BCoV , N2 , SC2_mass, PMMoV,
         GeoMeanN12,FlowRate,temperature,equiv_sewage_amt)

#joining the two data frames together
FullDF <- full_join(LatCaseDF,LIMSFullDF, by = c("Date","Site"))%>%
  mutate(Pop = case_when(
    Site=="MMSD-P2" ~ 83127,#111967
    Site=="MMSD-P7" ~ 42734, #81977
    Site=="MMSD-P8" ~ 70024,#127634
    Site=="MMSD-P11" ~ 156651,#130799
    Site=="MMSD-P18" ~ 89139,#151470
    Site=="Madison" ~ 441675,#603847
  ))
```


```{r Outlier}
SizeUsed = 1
alphaUsed = 1
strokeSize = 1
N1ShapeUnit = 4
N2ShapeUnit = 5



MadDF <- filter(FullDF,Site=="Madison")%>%
    mutate(FlagedOutliersN1 = IdentifyOutliers(N1,Bin = 21, Action = "Flag"),
           FlagedOutliersN2 = IdentifyOutliers(N2,Bin = 28, Action = "Flag"))




#"2021-06-08","2021-10-17","2021-05-02","2021-01-26"


source("IntercepterPlots.R")
source("IntercepterDFCreater.R")

OutLierPlotDF <- MadDF%>%
  OutLier_pointPlot_Prep("FlagedOutliersN1", "FlagedOutliersN2", "N1", "N2")%>%
  OutLier_pointPlot("N1","N2")

OutLierPlotDF+
  ggtitle("Covid partical conventration (GC/L) With Outlier")


OutLierPlotDF+
  ggtitle("Previous graph zoomed in")+
           scale_y_continuous(limits = c(0, 5800000))
```

```{r Intercepter OverView}
IntercepterDFPure <- FullDF %>%
  group_by(Site)%>%
  filter(Site != "Madison",
         !is.na(N1)|!is.na(N2))

 MassBalencePlot <- MassBalence_BarPlot_Prep(FullDF,"Site", "Madison", "SC2_mass")%>%
  MassBalence_BarPlot("SC2_mass","Site", "SelectedSite")+
  ggtitle("SARS-CoV-2, 24h Mass Loading (Madison)")


OutlierDF <- MadDF%>%
  filter(FlagedOutliersN2|FlagedOutliersN1)

OutlierDatesIntercepters <- unique(inner_join(IntercepterDFPure,OutlierDF["Date"],by=c("Date"))$Date)

a <- OutLierPlotDF+
  #scale_x_date(limits = c(StartRange,EndRange)) +
  geom_vline(xintercept = OutlierDatesIntercepters,color="Red") +
  theme(title = element_blank(),
        axis.text.x = element_blank(), 
        axis.title.x = element_blank(),
        legend.position="none")+
  scale_y_continuous(limits = c(0,7.5e6))

b <- MassBalencePlot+
  #scale_x_date(limits = c(StartRange,EndRange)) +
  geom_vline(xintercept = (OutlierDatesIntercepters),color="Red") +
  theme(title = element_blank(),
    axis.text.x = element_blank(), 
        axis.title.x = element_blank(),
    legend.position="none")+
  scale_y_continuous(limits = c(0,7.4e14))


OutlierComp <- ggarrange(a,b,nrow=2,align ="v",legend.grob=get_legend(MassBalencePlot),legend="right")


annotate_figure(OutlierComp, top = text_grob("Composite outliers compared to Interceptors", 
               color = "black", size = 12))

#Add lables
##Viral load?
```



```{r N1 Normalizer, dpi = 100}

IntercepterDF <- FullDF %>%
  group_by(Site)%>%
  filter(Site != "Madison")

IntercepterOverLay <- IntercepterDF%>%
  filter(Date>mdy("1/1/2021"), !is.na(N1))%>%
  pointPlotSite("N1","N2", "Site")+
  scale_y_log10()+
  ggtitle("Intercepters Covid Concentration")

IntercepterOverLay

#Get P18 to pop out
```







```{r Loess smoothing plot, fig.height = 5, fig.width = 9}

LoessFunc <- function(SiteFilter,DF,SpanConstant = .163,Var){
  MainDF <- DF%>%
    filter(Site==SiteFilter)
  MainDF[[paste0("loess",Var)]] <- loessFit(y=(MainDF[[Var]]),
                      x=MainDF$Date, #create loess fit of the data
                      span=SpanConstant, #span of .2 seems to give the best result,
                                          #not rigorously chosen
                      iterations=5)$fitted#2 iterations remove some bad patterns
  #Same as above but for N2
  N2Name <- gsub("1","2",Var)
  MainDF[[paste0("loess", N2Name)]] <- loessFit(y=(MainDF[[N2Name]]),
                      x=MainDF$Date,
                      span=SpanConstant,
                      iterations=5)$fitted#
return(MainDF)
}
#Temp clone to test 7 MA
# LoessFunc <- function(SiteFilter,DF,SpanConstant = .163,Var){
#   N2Name <- gsub("1","2",Var)
#   MainDF <- DF%>%
#     filter(Site==SiteFilter)%>%
#     mutate(!!paste0("loess",Var) := rollapply(!!sym(Var), width = 51,
#                                              FUN = mean, fill = NA, na.rm = TRUE ),
#            !!paste0("loess",N2Name) := rollapply(!!sym(N2Name), width = 51,
#                                              FUN = mean, fill = NA, na.rm = TRUE ))
#   return(MainDF)
# }

SiteLoessDF <- IntercepterDF%>%
  mutate(FlowN1 = FlowRate*N1,
         PopN1 = N1/Pop,
         FlowN2 = FlowRate*N2,
         PopN2 = N1/Pop,
         PopFlowN1 = N1*FlowRate/Pop,
         PopFlowN2 = N2*FlowRate/Pop)
  
  
  

BaseColDF <- lapply(c("MMSD-P11","MMSD-P18","MMSD-P2","MMSD-P7","MMSD-P8"),
                      LoessFunc,SiteLoessDF,SpanConstant = .15,
         Var = "N1")%>%
          bind_rows()

BaseGridPlot <- BaseColDF%>%
            filter(!is.na(loessN1))%>%  
            LinePlotSite("loessN1","loessN2", "Site")
            


NonLogPlotlyPlot <- BaseGridPlot+
            labs(title = "Linear scale", ylab = "Covid Conc With Norm")

LogPlotlyPlot <- BaseGridPlot+
            scale_y_log10()+
            labs(title = "Log scale")+
  theme(axis.title.y=element_blank())


LoessPlot <- ggarrange(NonLogPlotlyPlot,LogPlotlyPlot, common.legend = TRUE)

annotate_figure(LoessPlot, top = text_grob("Smoothed interceptors", 
               color = "black", size = 12))



```


```{r Motivated For next section}

IntercepterOverLay+
  geom_line(aes(y=N1, color = Site, linetype  = "N1"))+
  geom_line(aes(y=N2, color = Site, linetype  = "N2"))+
  ggtitle("Connected Intercepters Covid Concentration")

#Move legend to right


```

```{r Per Change}
IntercepterChangeDF <- IntercepterDF%>%
  filter(!is.na(N1))%>%
  mutate(ChangeN1 = lead(N1) - N1,
         ChangeN2 = lead(N2) - N2)


IntercepterChangeOverLay <- IntercepterChangeDF%>%
  pointPlotSite("ChangeN1","ChangeN2", "Site")+
  ylab("")+
  ggtitle("First Diffrence intercepters and Madison")
#IntercepterChangeOverLay
```


```{r pop Madison}

MadChangeDF <- MadDF%>%
  filter(!is.na(N1))%>%
  mutate(ChangeN1 = lead(N1) - N1,
         ChangeN2 = lead(N2) - N2)


MadChangeOverLay <- MadChangeDF%>%
  mutate(Flagged = FlagedOutliersN2|FlagedOutliersN1)%>%
  pointPlotSite("ChangeN1","ChangeN2", "Flagged")

ggarrange(IntercepterChangeOverLay, MadChangeOverLay, nrow = 2, align = "v")
Lim <- 1e6
ZoomSettings <- scale_y_continuous(limits = c(-Lim,Lim))
ggarrange(IntercepterChangeOverLay+ZoomSettings, 
          MadChangeOverLay+ZoomSettings, nrow = 2, align = "v")


```
