---
params:
  BaseDir: "Z:/"
  ##BaseDir: "/Volumes/byandell/"
title: "N1N2 Relationship"
author: "Marlin"
date: "11/2/2021"
output: html_document
knit: (
  function(inputFile, encoding) { 
    FileComp = strsplit(inputFile,"/")[[1]];
    File = FileComp[length(FileComp)];
    File = substr(File,1,nchar(File)-4);
    pSubTitle <- paste0('RmdOutput/',Sys.Date(),"_",File);
    rmarkdown::render( 
      input       = inputFile, 
      encoding    = encoding, 
      output_file = pSubTitle) })
---

```{r set up markdown settings, echo=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE
)
```


```{r Start enviroment, message=FALSE, warning=FALSE, echo=FALSE}
library(ggpubr)
library(forecast)
library(lmtest)
library(lubridate)
library(limma)
library(zoo)
library(dplyr)
library(readxl)

#Data Files and prep work
source("../../../lib/GenPlotMaking.R")
#source("../../../lib/WasteWaterDataProccess.R")
#source("../../../lib/CasesDataProccess.R")
source("../../../lib/DataProccess.R")
source("../../../lib/HelperFunctions.R")


source("../../../lib/NoTSCorrelationFunctions.R")
source("../../../lib/DataPathName.R")
```

```{r DF Set Up, echo=FALSE}
BaseDir <- params$BaseDir

LatCaseDF <- ParseData(LIMSCasePath(BaseDir))%>% 
  rename(Cases = FirstConfirmed)%>%
  filter(!is.na(Site)) %>%
  select(Date,Site,Cases)%>%
  filter(Site=="Madison")
  

LIMSFullDF <- ParseData(LIMSWastePath(BaseDir))%>%
  select(Date,Site, N1,N1Error,N2,N2Error)%>%
  filter(Site=="Madison")


```

"Files Used: "

`r LIMSCasePath(BaseDir)`

`r LIMSWastePath(BaseDir)`




Strong trend between N1 and N2 with a correlation of .93

```{r N1vsN2,warning=FALSE}
LIMSFullDF%>%
  ggplot()+
  aes(x=N1,y=N2)+
  geom_point()+
  ggtitle("non log plot")


LIMSFullDF%>%
  ggplot()+
  aes(x=N1,y=N2)+
  geom_point()+
  scale_y_log10()+
  scale_x_log10()+
  ggtitle("log plot")

cor(LIMSFullDF$N1,LIMSFullDF$N2,use="complete.obs")
```

