---
title: "CovWasteDashboard"
author: "Marlin"
date: "5/7/2021"
output: html_document
---

```{r}
library(shiny)
library(ggpubr)
library(dplyr)
library(shinydashboard)
library(shinyjqui)
library(shinycssloaders)
```

#Data Files and prepwork
```{r}
source("../../UntrackedData/DataProccess.R")
LatWasteFN <- "../../UntrackedData/WW SARS-COV-2 Data V5.xlsx"
LatSpringCaseFN="../../UntrackedData/SpringSemester_CasesByDorm.tsv"
LatFallCaseFN="../../UntrackedData/Oct2020toEndFall_CasesByDorm.tsv"

HFGWasteFN = "../../UntrackedData/HFG_mean_data.csv"
HFGCaseFN="../../UntrackedData/Madison_HighFreq_CaseData_20210507.csv"


RollAvg = function(vectorT,Day=7){
  CurrNum = rep(NA,7)
  SlideMeanVec=vector(mode="double", length=length(vectorT))
  for (i in 1:length(vectorT)){
    
    CurrNum[(i-1)%%Day+1]=vectorT[i]
    SlideMeanVec[i]=mean(CurrNum,na.rm=T)
  }
  return(SlideMeanVec)
}
```
#tab1 data
```{r}
LatCaseDF=CovidDataDorms(LatSpringCaseFN,LatFallCaseFN)%>%
  mutate(Per_pos=100*Cases/Tests)

Fullday=data.frame(Date=seq.Date(min(LatCaseDF$Date),max(LatCaseDF$Date),1))
LatCaseDF=full_join(LatCaseDF,Fullday,by=c("Date"))%>%
  arrange(Site,Date)%>%
  group_by(Site)%>%
  mutate(rollingPer_pos=RollAvg(Per_pos))%>%
  ungroup()



LatWasteDF=WasteWater(LatWasteFN)%>%
  mutate(Date=as.Date(Date))%>%
  mutate(GeoMean=(N1*N2)^.5)%>%
  filter(!is.na(Date),!is.na(N1))%>%
  filter(Date<mdy("6/5/2021"))
```


```{r}
#tab2 data

#Reads Transformed HFG Data

HFGWasteDF=read.csv(HFGWasteFN, row.names = 1)%>%
  mutate(Filter=as.character(Filter),Well=as.character(Well),Date=as.Date(Date))%>%
  na.omit()%>%
  rename(`Filter replicates`=Filter)


HFGCaseDF=full_join(HFGCasesPARSER(HFGCaseFN),filter(HFGWasteDF,Plant!="Madison"),by=c("Plant","Date"))
Fullday=data.frame(Date=seq.Date(min(HFGCaseDF$Date),max(HFGCaseDF$Date),1))
HFGCaseDF=full_join(HFGCaseDF,Fullday,by=c("Date"))%>%
  arrange(Plant,Date)%>%
  group_by(Plant)%>%
  mutate(SevCases=RollAvg(cases))%>%
  ungroup()


#Generating the weekends starts and end dates
#TO DO:Capture the weekend if the data intersects with it
DateRangeDF=data.frame(Date=seq(min(HFGCaseDF$Date), max(HFGCaseDF$Date), "days"))%>%
  mutate(Days=weekdays(Date))%>%
  filter(Days %in% c("Sunday","Monday"))
if (DateRangeDF$Days[1]=="Monday"){
  DateRangeDF=DateRangeDF[-1,]}
if (tail(DateRangeDF$Days, n=1)=="Sunday"){
  DateRangeDF=head(DateRangeDF, -1)}
MRan=filter(DateRangeDF,Days=="Sunday")%>%
  rename(Left=Date)
SRan=filter(DateRangeDF,Days=="Monday")%>%
  rename(Right=Date)
DateRangeCDF=cbind(MRan,SRan)%>%
  select(Left,Right)
#

```

```{r}
#constants and presets
maxLeftShift=-14
maxRightShift=14
XAxisLabSiz=10
YAxisLabSiz=15
GenFontSiz=20
alphaPoint=.7
PointSize=2
alphaWeek=.2

Middle_theme = function(){
  
  theme_grey() %+replace%    #Theme for the plots in the middle
    theme(
      text = element_text(size=GenFontSiz),
      axis.title.x = element_blank(),
      strip.text.x = element_blank(),
      axis.text.x = element_blank(),
      axis.text.y = element_text(size = YAxisLabSiz, colour = "black"))
}
Header_theme = function(){
  
  theme_grey() %+replace%    #Theme for the top plots
    theme(plot.margin = unit(c(1,0,1,0), "cm"),
    text = element_text(size=GenFontSiz),
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = YAxisLabSiz, colour = "black"),
    axis.text.x = element_text(size = XAxisLabSiz, colour = "black"),
    strip.text.x = element_text(size = GenFontSiz, colour = "black"))
}
Second_theme = function(){
  Middle_theme() %+replace%    #Theme for the plots underneither the first plots
  theme(axis.text.x = element_text(size = XAxisLabSiz, colour = "black"))
}

#Creates consistent jittering for data
myseed=1234567890

```

```{r}
#Parts Of Tab 2 defined outside for ease of use
TopDisc=div("Pink sections are weekends")
BotDisc=div("Data source: HFG data for stats preliminary 3-18-21.xlsx from 3/18/2021 jocelyn.hemming@slh.wisc.edu email.")
BotDisc2=div("Questions? Contact Marlin Lee mrlee6@wisc.edu or Steve Goldstein sgoldstein@wisc.edu")
#Creates buttons for Plant location,Line, and scale
Tab2=tabItem(tabName = "HFGDash",
             # Boxes need to be put in a row (or column)
             fluidRow(
               jqui_resizable(box(width=4,
                                  title = "Controls",
                                  selectInput(inputId = "Plant", label = ("Plant"),
                                              choices = c("All",unique(HFGWasteDF$Plant)),
                                              multiple=F,
                                              selected="Madison"),
                                  selectInput(inputId = "Vars2", label = ("Varibles"),
                                              choices = c("N1GC","N2GC","PMMOVGC","cases"),
                                              multiple=T,
                                              selected=c("N1GC","cases")),
                                  conditionalPanel(
                                    condition = "input.Vars2.includes('cases')",
                                    checkboxInput(inputId="7day2",label=("7 day average of cases"),value=T),
                                    sliderInput("Offset2", "Shift cases Date",min = maxLeftShift, max = maxRightShift,step=1,value=0)
                                  ),
                                  conditionalPanel(
                                    condition = "(!input.Vars2.includes('cases')||1!=input.Vars2.length)&&0!=input.Vars2.length",
                                    checkboxInput(inputId = "Line2", label = ("Daily mean of 9 replicates"),
                                                  value=F),
                                    checkboxInput(inputId = "Means", label = ("Mean of qPCR replicates"),
                                                  value=F),
                                    selectInput(inputId = "scale2", label = ("y scale"),
                                                choices = c("log","linear"),
                                                selected="log"),
                                    selectInput(inputId = "Outlier", label = ("Outlier"),
                                                choices = c("Remove Outliers"),
                                                multiple=T,
                                                selected="Remove Outliers")
                                  ),

                                  
                                  
               )),
               jqui_resizable(box(width=7,title ="High frequency waste water analysis",TopDisc,br(),div(withSpinner(plotOutput("plot2",inline=TRUE,width="auto",height="auto")),style="overflow-x: scroll"), br(),BotDisc,BotDisc2))
             ))
```

```{r}
#Parts Of Tab 1 defined outside for ease of use
TopDisc=div("")
BotDisc=div("Data source: Case Data from PnC Oct2020toEndFall_CasesByDorm and SpringSemester_CasesByDorm")
BotDisc2=div("Wastewater data from the DHS: WW SARS-COV-2 Data V5")
BotDisc3=div("Questions? Contact Marlin Lee mrlee6@wisc.edu or Steve Goldstein sgoldstein@wisc.edu")
#Creates buttons for Plant location,Line, and scale
Tab1=tabItem(tabName = "MadDash",
             # Boxes need to be put in a row (or column)
             fluidRow(
               jqui_resizable(box(width=4,
                                  title = "Controls",
                                  selectInput(inputId = "Site", label = ("Site"),
                                              choices = c("UW-Sellery" ,"UW-LakeShore"),
                                              multiple=T,
                                              selected=c("UW-Sellery" ,"UW-LakeShore")),
                                  selectInput(inputId = "Vars", label = ("Varibles"),
                                              choices = c("N1","N2","PMMoV","Pct_BCoV","GeoMean","Percent of tests positive"),
                                              multiple=T,
                                              selected=c("N1","Percent of tests positive")),
                                  
                                  conditionalPanel(
                                    condition = "input.Vars.includes('Percent of tests positive')",
                                    checkboxInput(inputId="7day",label=("7 day average of percent positive"),value=T),
                                    sliderInput("Offset", "Shift percent positive Date",min = maxLeftShift, max = maxRightShift,step=1,value=0)
                                  ),
                                  conditionalPanel(
                                    condition = "(!input.Vars.includes('Percent of tests positive')||1!=input.Vars.length)&&0!=input.Vars.length",
                                    checkboxInput(inputId="Line",label=("loess curve of waste water"),value=T),
                                    selectInput(inputId = "scale", label = ("y scale"),
                                                choices = c("log","linear"),
                                                selected="log"),
                                    conditionalPanel(
                                      condition = "input.Line == true",
                                      sliderInput("span", "Span variable of loess smoothing",min = .15, max = .75,step=.01,value=.42)
                                    )
                                  ),
                                  
               )),
               #title = "UW dorms Covid Visualization"
               jqui_resizable(box(width=7,TopDisc,br(),div(withSpinner(plotOutput("plot1",inline=TRUE)),style="overflow-x: scroll"), br(),BotDisc,BotDisc2,BotDisc3))
             ))

```

```{r}
#Creates UI for dashboard
ui <- dashboardPage(
  #top left descriptor
  dashboardHeader(title = "Waste Water interactive"),
  #left hand side tab selector
  dashboardSidebar(sidebarMenu(
    menuItem("UW Dorms WasteWater", tabName = "MadDash", icon = icon("dashboard")),
    menuItem("HFG high frequencey", tabName = "HFGDash", icon = icon("dashboard"))
  )),
  #Contents of different tabs defined above
  dashboardBody(
    tabItems(
      Tab1,
      Tab2
    ))
)
```

```{r}
#create graphic                                       
server <- function(input, output) {
  
  #Required for tab 1
  filtered_data_PWaste<- reactive({
    return(filter(LatWasteDF, LatWasteDF$Site %in% input$Site))
  })
  filtered_data_PCov<- reactive({
    return(filter(LatCaseDF, Site %in% input$Site))
  })
  
  minCDorms=reactive({
    return(min(filtered_data_PWaste()$Date)+input$Offset)
  })
  
  maxCDorms=reactive({
    return(max(filtered_data_PWaste()$Date)+input$Offset)
  })
  
  buildplot1 = function(vari){
    #set.seed(myseed)
    #!!sym() reads string as a variable of the data frame
    set.seed(myseed)
    DormPlot=ggplot(data=filtered_data_PWaste(),aes(y=!!sym(vari),x=Date))+geom_jitter(alpha=alphaPoint,height=0,width=.1,size=PointSize)+ylab(vari)
    #adds mean line
    DormPlot = DormPlot+facet_wrap(~Site, nrow = 1)+Middle_theme()
    if(input$scale=="log"){
      DormPlot=DormPlot+scale_y_log10()
    }
    if(input$Line==TRUE){
      DormPlot=DormPlot+geom_smooth(span=input$span)
    }
    DormPlot=DormPlot+scale_x_date(position="top",date_breaks="24 days",date_labels="%b %d")
    return(DormPlot)
  }
  #Creates list of ggplots for ggarange
  Make_Plots1 = reactive({
    plots=lapply(input$Vars[input$Vars!="Percent of tests positive"],buildplot1)
    if("Percent of tests positive" %in% input$Vars){
      set.seed(myseed)
      DormPlot=ggplot(data=filtered_data_PCov())+
        geom_jitter(aes(y=Per_pos,x=Date),alpha=alphaPoint,height=0,width=.1,size=PointSize)
      if(input$'7day'){
        DormPlot=DormPlot+geom_line(aes(y=rollingPer_pos,x=Date),size=1,color="red")
      }
      DormPlot=DormPlot+ylab("Percent Positive")+
      facet_wrap(~Site, nrow = 1)+coord_cartesian(xlim=c(minCDorms(), maxCDorms()))+
      scale_x_date(date_breaks="24 days",date_labels="%b %d")
      plots=c(list(DormPlot),plots)
    }
    return(plots)
  })
  #plots N1GC
  output$plot1<-renderPlot(
    width = function() 245+425*length(input$Site),
    height = function() 60+300*length(input$Vars),
    {
      if(length(input$Vars)==0||length(input$Site)==0){
        return()
      }
      plots=Make_Plots1()
      #Add plant labels
      #add x axis labels
      if("Percent of tests positive" %in% input$Vars){
        T=2
        if(length(input$Vars)==1){
          T=1
        }
      }else{
        T=1
      }
      plots[[1]]=plots[[1]] + Header_theme()
      plots[[T]]=plots[[T]] + Second_theme()
      OvarLn=length(input$Vars[input$Vars!="Percent of tests positive"])
      return(annotate_figure(top=text_grob("UW dorms Wastewater Surveillance",size=25),ggarrange(plotlist=plots,ncol =1,align="v",heights=c(1.2,rep(1,times = OvarLn)))))
    })
  #-------------------------
  #required for tab2
  #Filters data for right plants and variables
  HFGCaseDataFil = reactive({
    if(input$Plant!="All")
      return(filter(HFGCaseDF, HFGCaseDF$Plant %in% input$Plant))
    return(HFGCaseDF)
    Plant
  })
  filtered_data_P<- reactive({
    if(input$Plant!="All")
      return(filter(HFGWasteDF, HFGWasteDF$Plant %in% input$Plant))
    return(HFGWasteDF)
  })
  #creates data with original values
  filtered_data_N<- reactive({
    filtered_data_P()%>%
      filter(Type=="Normal")
  })
  
  #Data of the means of each day
  Data_mean_var = reactive({
    filtered_data_P()%>%
      filter(Type=="Plant Mean")
  })
  #Data of the means of each Filter
  Filter_mean_var = reactive({
    filtered_data_P()%>%
      filter(Type=="Filter Mean")
  })
  #Putting data in reactive shell for possible additions
  DF_Week = reactive({
    return(DateRangeCDF)
  })
  minCHFG=reactive({
    return(min(HFGCaseDF$Date))
  })
  
  maxCHFG=reactive({
    return(max(HFGCaseDF$Date))
  })
  #Function Creates ggplots that gets merged into final graphic
  buildplot2 = function(vari){
    set.seed(myseed)
    #!!sym() reads string as a variable of the dataframe
    HFGDPlot=ggplot()+
      geom_jitter(data=filtered_data_N(),aes(y=!!sym(vari),x=Date,color=`Filter replicates`),alpha=alphaPoint,height=0,width=.1,size=PointSize)+ylab(vari)
    #adds mean line
    if(input$Line2==T){
      HFGDPlot=HFGDPlot+geom_line(data=Data_mean_var(),aes(y=!!sym(vari),x=Date),size=1)
    }
    #add filter means
    if(input$Means==T){
      set.seed(myseed)
      HFGDPlot=HFGDPlot+geom_jitter(data=Filter_mean_var(),aes(y=!!sym(vari),x=Date,fill=`Filter replicates`), shape=23, size=2.5*PointSize, height=0, width=.1)
    }
    #hides outliers
    #Does this by setting y upper bounds for later cropping
    if ("Remove Outliers" %in% input$Outlier){
      if(input$scale2=="log"){
        quint=quantile(pull(HFGWasteDF,vari),.995)[[1]]
      }
      else{
        quint=quantile(pull(HFGWasteDF,vari),.975)[[1]]
      }
    }
    else{
      quint=max(pull(HFGWasteDF,vari))
    }
    minVal=min(HFGWasteDF[vari],na.rm = T)
    #sets appropriate scale
    #also applies weekend indicators because logscale can not have -inf(or any negitive number) as the ymin
    if(input$scale2=="log y scale"){
      HFGDPlot = HFGDPlot + scale_y_log10()
      HFGDPlot=HFGDPlot+geom_rect(data=DF_Week(), aes(xmin=Left, xmax=Right, ymin=0, ymax=Inf), fill='pink', alpha=alphaWeek)}
    else{
      HFGDPlot=HFGDPlot+
        coord_cartesian(ylim=c(minVal, quint),xlim=c(minCHFG(), maxCHFG()))+
      geom_rect(data=DF_Week(), aes(xmin=Left, xmax=Right, ymin=-Inf, ymax=Inf), fill='pink', alpha=alphaWeek)}
    #faucet the data by Plant and remove hud elements that dont need to be in all three varible strips
    HFGDPlot = HFGDPlot+scale_x_date(position="top")+facet_wrap(~Plant, nrow = 1)+Middle_theme()
    return(HFGDPlot)
  }
  #Creates list of ggplots for ggarange
  Make_Plots2 = reactive({
    plots=lapply(input$Vars2[input$Vars2!="cases"],buildplot2)
    if("cases" %in% input$Vars2){
      set.seed(myseed)
      CasePlot=ggplot(data=HFGCaseDataFil())+
        geom_jitter(aes(y=cases,x=Date),alpha=alphaPoint,height=0,width=.1,size=PointSize)
      if(input$'7day2'){
        CasePlot=CasePlot+geom_line(aes(y=SevCases,x=Date),size=1,color="red")
      }
      CasePlot=CasePlot+geom_rect(data=DF_Week(), aes(xmin=Left, xmax=Right, ymin=-Inf, ymax=Inf), fill='pink', alpha=alphaWeek)+ylab("Cases")+
        facet_wrap(~Plant, nrow = 1)+coord_cartesian(xlim=c(minCHFG()+input$Offset2, maxCHFG()+input$Offset2))
      plots=c(list(CasePlot),plots)
    }
    return(plots)
  })
  #plots N1GC
  output$plot2<-renderPlot(
    width = function() 245+800*ifelse(input$Plant=="All",10,1),
    height = function() 60+300*length(input$Vars2),
    {
      if(length(input$Vars2)==0){
        return()
      }
      plots=Make_Plots2()
      #Add plant labels
      #add x axis labels
      if("cases" %in% input$Vars2){
        T=2
        if(length(input$Vars)==1){
          T=1
        }
      }else{
        T=1
      }
      plots[[1]]=plots[[1]] + Header_theme()
      plots[[T]]=plots[[T]] + Second_theme()
      return(annotate_figure( left = text_grob("(GC/L)", rot = 90,size=GenFontSiz),ggarrange(plotlist=plots,ncol =1,common.legend = TRUE,legend = "right",align="v")))
    })
  #top = text_grob("High frequency waste water analysis",size=20),  
  
  
}
shinyApp(ui = ui, server = server)
```