---
title: "HFG interactive graphic"
author: "Marlin"
date: "4/3/2021"
output:
  pdf_document: default
  html_document: default
---
```{r}

source("../Scripts/DataProccess.R")


HFGData="../../UntrackedData/HFG data for stats preliminary 3-18-21.xlsx"

HFGFrame=HFGInfo(HFGData)%>%
  mutate(Filter=as.character(Filter),Well=as.character(Well))

HFGFrame.Filtered=HFGFrame%>%
  filter(!is.na(N1GC),!is.na(Date))%>%
  group_by(Plant,Date)%>%
  mutate(n=n())%>%
  filter(n==9)%>%
  ungroup()%>%
  select(-n)

DateRange=data.frame(Date=seq(min(HFGFrame$Date), max(HFGFrame$Date), "days"))%>%
  mutate(Days=weekdays(Date))%>%
  filter(Days %in% c("Sunday","Monday"))
if (DateRange$Days[1]=="Monday"){
  DateRange=DateRange[-1,]}
if (tail(DateRange$Days, n=1)=="Sunday"){
  DateRange=head(DateRange, -1)}
MRan=filter(DateRange,Days=="Sunday")%>%
  rename(Left=Date)
SRan=filter(DateRange,Days=="Monday")%>%
  rename(Right=Date)

DateRangeD=cbind(MRan,SRan)%>%
  select(Left,Right)

HFGDFrame=HFGFrame.Filtered%>%
  rename(`Filter replicates`=Filter)%>%
  mutate(Is_W_end=weekdays(Date) %in% c("Sunday","Monday"))
myseed=1234567890
library(shiny)
library(ggpubr)
```

```{r}
#Creates buttons for Plant location,Line, and scale
ui <- fluidPage(
    titlePanel("HFG Interactive graphic"),
    sidebarLayout(
        sidebarPanel(
            selectInput(inputId = "Plant", label = ("Plant"),
                        choices = c("All",unique(HFGDFrame$Plant)),
                        multiple=F,
                        selected="Madison"),
            selectInput(inputId = "Vars", label = ("Varibles"),
                        choices = c("N1GC","N2GC","PMMOVGC"),
                        multiple=T,
                        selected="N1GC"),
            checkboxInput(inputId = "Line", label = ("Daily mean of 9 replicates"),
                          value=F),
            checkboxInput(inputId = "Means", label = ("Mean of qPCR replicates"),
                          value=F),
            checkboxInput(inputId = "scale", label = ("y scale"),
                        value=T),
            sliderInput(inputId = "YLim", label = "Shown Y Quintile",min = .9, max = 1,step=.005,value=1)
        ),
        #creates panel
        mainPanel(div("Pink sections are weekends"),br(),plotOutput("plot1",inline=TRUE), br(),div("Data source: HFG data for stats preliminary 3-18-21.xlsx from 3/18/2021 jocelyn.hemming@slh.wisc.edu email."),div("Questions? Contact Marlin Lee mrlee6@wisc.edu or Steve Goldstein sgoldstein@wisc.edu"))
    )
)
```


```{r}
#create graphic                                       
server <- function(input, output) {
    #reduces data to only Plant selected
    filtered_data_P<- reactive({
        if(input$Plant!="All")
            return(filter(HFGDFrame, HFGDFrame$Plant %in% input$Plant))
        return(HFGDFrame)
        })
    #Data of the means of each day
    Data_mean_var = reactive({
      DF_mean=filtered_data_P()%>%
            group_by(Date,Plant)
      for (var in input$Vars){
        DF_mean=DF_mean%>%
          mutate(!!paste0("Mean",var) := exp(mean(log(!!sym(var)))))
      }
      DF_mean=DF_mean%>%
        distinct(Date,Plant,`Filter replicates`,.keep_all=T)%>%
        ungroup()
      return(DF_mean)
    })
    Filter_mean_var = reactive({
      DF_meanv=filtered_data_P()%>%
            group_by(Date,Plant,`Filter replicates`)
      for (var in input$Vars){
        DF_meanv=DF_meanv%>%
          mutate(!!paste0("Mean",var) := exp(mean(log(!!sym(var)))))
      }
      DF_meanv=DF_meanv%>%
        distinct(Date,Plant,`Filter replicates`,.keep_all=T)%>%
        ungroup()
      return(DF_meanv)
    })
      DF_Week = reactive({
        
      return(DF_Week)
    })
    buildplot = function(vari){
      set.seed(myseed)
      HFGDPlot=ggplot()+
            geom_jitter(data=filtered_data_P(),aes(y=!!sym(vari),color=`Filter replicates`,x=Date),alpha=.7,height=0,width=.1,size=3)+ylab(vari)
      if(input$Line==T){
          HFGDPlot=HFGDPlot+geom_line(data=Data_mean_var(),aes(y=!!sym(paste0("Mean",vari)),x=Date),size=1)
      }
      if(input$Means==T){
          set.seed(myseed)
          HFGDPlot=HFGDPlot+geom_jitter(data=Filter_mean_var(),aes(y=!!sym(paste0("Mean",vari)),fill=`Filter replicates`,x=Date), shape=23, size=5, height=0, width=.1)
      }
      quint=quantile(pull(HFGDFrame,vari),input$YLim,na.rm=T)[[1]]
      #scales it if button is on
      if(input$scale==T)
          HFGDPlot = HFGDPlot + scale_y_log10(limits = c(min(HFGDFrame[vari]),quint))
      else
        HFGDPlot=HFGDPlot+scale_y_continuous(limits = c(min(HFGDFrame[vari]),quint))
      HFGDPlot=HFGDPlot+geom_rect(data=DateRangeD, aes(xmin=Left, xmax=Right, ymin=0, ymax=Inf), fill='pink', alpha=.2)
      HFGDPlot = HFGDPlot+facet_wrap(~Plant, nrow = 1)+theme(text = element_text(size=20),strip.text.x = element_blank(),axis.text.x = element_blank(),axis.text.y = element_text(size = 15, colour = "black"))+ rremove("xlab")
      return(HFGDPlot)
    }
    #plots N1GC
    output$plot1<-renderPlot(
        width = function() 800*ifelse(input$Plant=="All",10,1),
        height = function() 100+550*length(input$Vars),
        {
          plots=lapply(input$Vars,buildplot)
          plots[[1]]=plots[[1]] + theme(strip.text.x = element_text(size = 20, colour = "black"))
          plots[[length(plots)]]=plots[[length(plots)]] + theme(axis.title.x = element_text(size = 20, colour = "black"),axis.text.x = element_text(size = 15, colour = "black"))
          ggarrange(plotlist=plots,ncol =1,common.legend = TRUE, legend = "right")
        })
}
shinyApp(ui = ui, server = server)
```

```{r}
Vars=c("N1GC","N2GC","PMMOVGC")

buildplot = function(vari){
      set.seed(myseed)
      HFGDPlot=ggplot()+
            geom_jitter(data=HFGDFrame,aes(y=!!sym(vari),color=`Filter replicates`,x=Date),alpha=.7,height=0,width=.1,size=3)+ rremove("xlab")}
plots=lapply(Vars,buildplot)
plots[[2]]=plots[[2]] + theme(axis.title.x = element_text("Arial", "plain", "black", 20))
plots
```


