---
output:
  pdf_document: default
  html_document: default
editor_options: 
  chunk_output_type: console
---
```{r warning = FALSE, message = FALSE,echo = FALSE}
source("../Scripts/DataProccess.R")

HFGData="../../UntrackedData/HFG data for stats preliminary 3-18-21.xlsx"

HFGFrame=HFGInfo(HFGData)%>%
  mutate(Filter=as.character(Filter),Well=as.character(Well))%>%
  filter(!is.na(N1GC),!is.na(Filter),!is.na(Plant),!is.na(Date))%>%
  mutate(DayPlace=paste(Plant,Date),DayPlaceFilter=paste(Plant,Date,Filter))%>%
  select(DayPlace,DayPlaceFilter,N1GC)%>%
  group_by(DayPlace)%>%
  mutate(n=n())%>%
  filter(n==9)

HFGSumarized=HFGFrame%>%
  group_by(DayPlace)%>%
  mutate(N=n(),K=length(unique(DayPlaceFilter)))%>%
  mutate(Y_mean_DP=mean(log(N1GC)))%>%
  group_by(DayPlaceFilter)%>%
  mutate(Y_mean_Filter=mean(log(N1GC)))%>%
  group_by(DayPlace)%>%
  summarize(between=sum((Y_mean_Filter-Y_mean_DP)^2)/(K-1),within=sum((log(N1GC)-Y_mean_Filter)^2)/(N-K))%>%
  distinct()%>%
  mutate(Plant=strsplit(DayPlace, " ")[[1]][1])

#Example point={1,1,1,2,3,4,5,5,5}
#sample means are ={1,3,5}
#total mean = {3}
#numerator = 3 * (1-3)^2 + 

#OverallData=HFGFrame%>%
#  mutate(Y_mean=mean(log(N1GC)),N=n(),K=length(unique(DayPlaceFilter)))%>%
#  group_by(DayPlaceFilter)%>%
#  mutate(Y_mean_Filter=mean(log(N1GC)))%>%
#  ungroup()%>%
#  summarize(between=sum((Y_mean_Filter-Y_mean)^2)/(K-1),within=sum((log(N1GC)-Y_mean_Filter)^2)/(N-K))%>%
#  distinct()%>%
#  mutate(FScore=between/within)
#OverallData

#DayPlace.aov <- aov(log(N1GC) ~ DayPlaceFilter, data = HFGFrame)
#summary(DayPlace.aov)[1][[1]][4][1]


```


```{r fig.width=8, fig.height=8,echo = FALSE}

HFGSumarized%>%
  ggplot()+geom_point(aes(x=between,y=within,color=Plant))+
  geom_abline(intercept = 0, slope = 1)+
  scale_y_log10()+
  scale_x_log10()

HFGSumarized%>%
  ggplot()+geom_histogram(aes(x=between/within),bins = 30)+
  geom_vline(xintercept = 1,color="red")+
  scale_x_log10()+
  xlab("F Score")
```
```{r}
library(VCA)

HFGFrame=HFGInfo(HFGData)%>%
  filter(Plant=="Madison")%>%
  filter(!is.na(N1GC),!is.na(Filter),!is.na(Well),!is.na(Date),!is.na(Plant))%>%
  mutate(N1GC=as.numeric(N1GC),Filter=factor(Filter),Well=factor(Well),Date=factor(Date),Plant=factor(Plant))%>%
  select(N1GC,Plant,Date,Filter,Well)
levels(HFGFrame$Filter)


HFGFrame
varPlot(form=N1GC~Filter, Data=HFGFrame)


#20 9 madison

form=N1GC~Filter
form <- terms(form, simplify = TRUE)


temp=terms(form, simplify = TRUE)

nest=attr(temp, "term.labels")

nest <- sapply(nest, function(x) {
        x <- unlist(strsplit(x, ":"))
        return(x[length(x)])
})
 tab <- table(nest)
resp <- rownames(attr(form, "factors"))[1]


HFGFrame=HFGFrame[sample(nrow(HFGFrame), 9), ]

VCA:::buildList
unique(as.character(Data[, Current]))
```

```{r}
Data = HFGFrame
Nesting = nest
Current = nest[1]
resp = resp
keep.order = TRUE
useVarNam = FALSE 
Points = list(pch = 16, cex = 0.5, col = "black")
#VCA:::buildList(Data,Nesting,Current,resp,keep.order,useVarNam,Points)
```


```{r}
    lev <- unique(as.character(Data[, Current]))
    if (is.list(Points)) {
        if ((is.list(Points$col)) && ("var" %in% names(Points$col)) && 
            (Points$col$var %in% colnames(Data))) {
            if (length(unique(Data[, Points$col$var])) > length(unique(Points$col$col))) {
                Points$col$col <- rep(Points$col$col, ceiling(length(unique(Data[, 
                  Points$col$var]))/length(unique(Points$col$col))))
            }
            tmp <- 1:length(unique(Data[, Points$col$var]))
            names(tmp) <- unique(Data[, Points$col$var])
            Data$PointsColor <- Points$col$col[tmp[as.character(Data[, 
                Points$col$var])]]
        }
        else {
            Data$PointsColor <- rep(Points$col, nrow(Data))
        }
        if ((is.list(Points$pch)) && ("var" %in% names(Points$pch)) && 
            (Points$pch$var %in% colnames(Data))) {
            if (length(unique(Data[, Points$pch$var])) > length(unique(Points$pch$pch))) {
                Points$pch$pch <- rep(Points$pch$pch, ceiling(length(unique(Data[, 
                  Points$pch$var]))/length(unique(Points$pch$pch))))
            }
            tmp <- 1:length(unique(Data[, Points$pch$var]))
            names(tmp) <- unique(Data[, Points$pch$var])
            Data$PointsPCH <- Points$pch$pch[tmp[as.character(Data[, 
                Points$pch$var])]]
        }
        else {
            Data$PointsPCH <- rep(Points$pch, nrow(Data))
        }
        if ((is.list(Points$bg)) && ("var" %in% names(Points$bg)) && 
            (Points$bg$var %in% colnames(Data))) {
            if (length(unique(Data[, Points$bg$var])) > length(unique(Points$bg$bg))) {
                Points$bg$bg <- rep(Points$bg$bg, ceiling(length(unique(Data[, 
                  Points$bg$var]))/length(unique(Points$bg$bg))))
            }
            tmp <- 1:length(unique(Data[, Points$bg$var]))
            names(tmp) <- unique(Data[, Points$bg$var])
            Data$PointsBG <- Points$bg$bg[tmp[as.character(Data[, 
                Points$bg$var])]]
        }
        else {
            Data$PointsBG <- rep(Points$bg, nrow(Data))
        }
        if ((is.list(Points$cex)) && ("var" %in% names(Points$cex)) && 
            (Points$cex$var %in% colnames(Data))) {
            if (length(unique(Data[, Points$cex$var])) > length(unique(Points$cex$cex))) {
                Points$cex$cex <- rep(Points$cex$cex, ceiling(length(unique(Data[, 
                  Points$cex$var]))/length(unique(Points$cex$cex))))
            }
            tmp <- 1:length(unique(Data[, Points$cex$var]))
            names(tmp) <- unique(Data[, Points$cex$var])
            Data$PointsCEX <- Points$cex$cex[tmp[as.character(Data[, 
                Points$cex$var])]]
        }
        else {
            Data$PointsCEX <- rep(Points$cex, nrow(Data))
        }
        Points <- NULL
    }
    if (!keep.order) {
        suppressWarnings(levInt <- as.integer(lev))
        if (!any(is.na(levInt))) 
            lev <- lev[sort(levInt, index.return = TRUE)$ix]
        else lev <- sort(lev)
    }
    lst <- vector("list", length = length(lev))
    attr(lst, "factor") <- Current
    Mean <- Median <- SD <- CV <- Nelem <- Nlevel <- numeric(length(lev))
    Nbin <- 0
    SDrange <- c(Inf, -Inf)
    CVrange <- c(Inf, -Inf)
    if (useVarNam) {
        names(lst) <- paste(Current, lev, sep = sep)
    } else names(lst) <- lev
    for (i in 1:length(lev)) {
        tmpData <- Data[which(Data[, Current] == lev[i]), ]
        Mean[i] <- mean(tmpData[, resp], na.rm = TRUE)
        Median[i] <- median(tmpData[, resp], na.rm = TRUE)
        SD[i] <- sd(tmpData[, resp], na.rm = TRUE)
        CV[i] <- SD[i] * 100/Mean[i]
        if (Current == Nesting[length(Nesting)]) {
            lst[[i]] <- tmpData[, resp]
            attr(lst[[i]], "Color") <- tmpData$PointsColor
            attr(lst[[i]], "Symbol") <- tmpData$PointsPCH
            attr(lst[[i]], "BG") <- tmpData$PointsBG
            attr(lst[[i]], "CEX") <- tmpData$PointsCEX
            if (na.rm) 
                lst[[i]] <- na.omit(lst[[i]])
            Nelem[i] <- length(unique(tmpData[, Current]))
            Nbin <- Nbin + 1
            if (!is.na(SD[i]) && SD[i] < SDrange[1]) 
                SDrange[1] <- SD[i]
            if (!is.na(SD[i]) && SD[i] > SDrange[2]) 
                SDrange[2] <- SD[i]
            if (!is.na(CV[i]) && CV[i] < CVrange[1]) 
                CVrange[1] <- CV[i]
            if (!is.na(CV[i]) && CV[i] > CVrange[2]) 
                CVrange[2] <- CV[i]
        }
        else {
            lst[[i]] <- buildList(Data = tmpData, Nesting = Nesting, 
                Current = Nesting[which(Nesting == Current) + 
                  1], resp = resp, keep.order = keep.order, useVarNam, 
                Points = Points)
            Nelem[i] <- sum(attr(lst[[i]], "Nelem"))
            Nbin <- Nbin + attr(lst[[i]], "Nbin")
            tmpSD <- attr(lst[[i]], "SDrange")
            if (tmpSD[1] < SDrange[1]) 
                SDrange[1] <- tmpSD[1]
            if (tmpSD[2] > SDrange[2]) 
                SDrange[2] <- tmpSD[2]
            tmpCV <- attr(lst[[i]], "CVrange")
            if (tmpCV[1] < CVrange[1]) 
                CVrange[1] <- tmpCV[1]
            if (tmpCV[2] > CVrange[2]) 
                CVrange[2] <- tmpCV[2]
        }
        Nlevel[i] <- length(lst[[i]])
    }
    attr(lst, "Nelem") <- Nelem
    attr(lst, "Nlevel") <- Nlevel
    attr(lst, "Nbin") <- Nbin
    attr(lst, "SDrange") <- SDrange
    attr(lst, "CVrange") <- CVrange
    attr(lst, "Stats") <- list(Mean = Mean, Median = Median, 
        SD = SD, CV = CV)
    lst
```