---
title: "HFG interactive graphic"
author: "Marlin"
date: "4/3/2021"
output:
  pdf_document: default
  html_document: default
editor_options: 
  chunk_output_type: inline
---

```{r}
library(shiny)
library(ggpubr)
library(dplyr)
library(shinydashboard)


#Reads Transformed HFG Data
HFGData=read.csv("../../UntrackedData/R_connect_HFG_TEMP/HFG_mean_data.csv", row.names = 1)%>%
    mutate(Filter=as.character(Filter),Well=as.character(Well),Date=as.Date(Date))%>%
    na.omit()

#Generating the weekends starts and end dates
#TO DO:Capture the weekend if the data intersects with it
DateRange=data.frame(Date=seq(min(HFGData$Date), max(HFGData$Date), "days"))%>%
    mutate(Days=weekdays(Date))%>%
    filter(Days %in% c("Sunday","Monday"))
if (DateRange$Days[1]=="Monday"){
    DateRange=DateRange[-1,]}
if (tail(DateRange$Days, n=1)=="Sunday"){
    DateRange=head(DateRange, -1)}
MRan=filter(DateRange,Days=="Sunday")%>%
    rename(Left=Date)
SRan=filter(DateRange,Days=="Monday")%>%
    rename(Right=Date)
DateRangeD=cbind(MRan,SRan)%>%
    select(Left,Right)
#


#minnor quality of life changes
HFGDFrame=HFGData%>%
    rename(`Filter replicates`=Filter)

#Creates consistant jittering for data
myseed=1234567890
```

```{r}
#Parts Of Tab 1 defined outside for ease of use
TopDisc=div("Pink sections are weekends")
BotDisc=div("Data source: HFG data for stats preliminary 3-18-21.xlsx from 3/18/2021 jocelyn.hemming@slh.wisc.edu email.")
BotDisc2=div("Questions? Contact Marlin Lee mrlee6@wisc.edu or Steve Goldstein sgoldstein@wisc.edu")
#Creates buttons for Plant location,Line, and scale
Tab1=tabItem(tabName = "dashboardWIP",
            # Boxes need to be put in a row (or column)
    fluidRow(
    box(
        title = "Controls",
        selectInput(inputId = "Plant", label = ("Plant"),
                    choices = c("All",unique(HFGDFrame$Plant)),
                    multiple=F,
                    selected="Madison"),
        selectInput(inputId = "Vars", label = ("Varibles"),
                    choices = c("N1GC","N2GC","PMMOVGC"),
                    multiple=T,
                    selected="N1GC"),
        checkboxInput(inputId = "Line", label = ("Daily mean of 9 replicates"),
                      value=F),
        checkboxInput(inputId = "Means", label = ("Mean of qPCR replicates"),
                      value=F),
        selectInput(inputId = "scale", label = ("y scales"),
                    choices = c("log y scale","linear scale"),
                    selected="log y scale"),
        selectInput(inputId = "Outlier", label = ("Outlier"),
                    choices = c("Remove Outliers"),
                    multiple=T,
                    selected="Remove Outliers")
    ),
    box(TopDisc,br(),div(plotOutput("plot1",inline=TRUE),style="overflow-x: scroll"), br(),BotDisc,BotDisc2)
))

#Defining of tab 2 for future use
Tab2=tabItem(tabName = "dashboard",
        fluidRow(
            box(
                title="Future Work"
            )
        )
)

#Creates UI for dashboard
ui <- dashboardPage(
    #top left descriptor
    dashboardHeader(title = "HFG Interactive graphic"),
    #left hand side tab selector
    dashboardSidebar(sidebarMenu(
        menuItem("DashboardWIP", tabName = "dashboardWIP", icon = icon("dashboard")),
        menuItem("Dashboard", tabName = "dashboard", icon = icon("dashboard"))
    )),
    #Contents of different tabs defined above
    dashboardBody(
        tabItems(
            Tab1,
            Tab2
            ))
)
```


```{r}
#create graphic                                       
server <- function(input, output) {
    #Filters data for right plants and variables
    filtered_data_P<- reactive({
        if(input$Plant!="All")
            return(filter(HFGDFrame, HFGDFrame$Plant %in% input$Plant))
        return(HFGDFrame)
    })
    #creates data with original values
    filtered_data_N<- reactive({
        filtered_data_P()%>%
            filter(Type=="Normal")
    })
    
    #Data of the means of each day
    Data_mean_var = reactive({
        filtered_data_P()%>%
            filter(Type=="Plant Mean")
    })
    #Data of the means of each Filter
    Filter_mean_var = reactive({
        filtered_data_P()%>%
            filter(Type=="Filter Mean")
    })
    #Putting data in reactive shell for possible additions
    DF_Week = reactive({
        return(DateRangeD)
    })
    #Function Creates ggplots that gets merged into final graphic
    buildplot = function(vari){
        set.seed(myseed)
        #!!sym() reads string as a variable of the dataframe
        HFGDPlot=ggplot()+
            geom_jitter(data=filtered_data_N(),aes(y=!!sym(vari),x=Date,color=`Filter replicates`),alpha=.7,height=0,width=.1,size=3)+ylab(vari)
        #adds mean line
        if(input$Line==T){
            HFGDPlot=HFGDPlot+geom_line(data=Data_mean_var(),aes(y=!!sym(vari),x=Date),size=1)
        }
        #add filter means
        if(input$Means==T){
            set.seed(myseed)
            HFGDPlot=HFGDPlot+geom_jitter(data=Filter_mean_var(),aes(y=!!sym(vari),x=Date,fill=`Filter replicates`), shape=23, size=5, height=0, width=.1)
        }
        #hides outliers
        #Does this by setting y upper bounds for later cropping
        if ("Remove Outliers" %in% input$Outlier){
            if(input$scale=="log y scale"){
                quint=quantile(pull(HFGDFrame,vari),.995)[[1]]}
            else{
                quint=quantile(pull(HFGDFrame,vari),.975)[[1]]}
        }
        else{
            quint=max(pull(HFGDFrame,vari))}
        minVal=min(HFGDFrame[vari],na.rm = T)
        #sets appropriate scale
        #also applies weekend indicators because logscale can not have -inf(or any negitive number) as the ymin
        if(input$scale=="log y scale"){
            HFGDPlot = HFGDPlot + scale_y_log10()+coord_cartesian(ylim=c(minVal, quint))
            HFGDPlot=HFGDPlot+geom_rect(data=DF_Week(), aes(xmin=Left, xmax=Right, ymin=0, ymax=Inf), fill='pink', alpha=.2)}
        else{
            HFGDPlot=HFGDPlot+coord_cartesian(ylim=c(minVal, quint))
            HFGDPlot=HFGDPlot+geom_rect(data=DF_Week(), aes(xmin=Left, xmax=Right, ymin=-Inf, ymax=Inf), fill='pink', alpha=.2)}
        #faucet the data by Plant and remove hud elliments that dont need to be in all three varible strips
        HFGDPlot = HFGDPlot+facet_wrap(~Plant, nrow = 1)+theme(text = element_text(size=20),strip.text.x = element_blank(),axis.text.x = element_blank(),axis.text.y = element_text(size = 15, colour = "black"))+ rremove("xlab")
        return(HFGDPlot)
    }
    #Creates list of ggplots for ggarange
    Make_Plots = reactive({
        plots=lapply(input$Vars,buildplot)
        return(plots)
    })
    #plots N1GC
    output$plot1<-renderPlot(
        width = function() 245+400*ifelse(input$Plant=="All",10,1),
        height = function() 60+300*length(input$Vars),
        {
            plots=Make_Plots()
            #Add plant labels
            plots[[1]]=plots[[1]] + theme(strip.text.x = element_text(size = 20, colour = "black"))
            #add x axis labels
            plots[[length(plots)]]=plots[[length(plots)]] + theme(axis.title.x = element_text(size = 20, colour = "black"),axis.text.x = element_text(size = 15, colour = "black"))
            return(annotate_figure( left = text_grob("(GC/L)", rot = 90,size=20),ggarrange(plotlist=plots,ncol =1,common.legend = TRUE, legend = "right")))
        })
}
shinyApp(ui = ui, server = server)
```



