---
title: "Using HFG Data to predict range of posible values"
author: "Marlin"
date: "6/2/2021"
output:
  pdf_document: default
  html_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```


```{r Importing, include=FALSE}
library(shiny)
library(ggpubr)
library(dplyr)
library(shinydashboard)
library(shinyjqui)
library(shinycssloaders)

#Data Files and prepwork
source("../Scripts/GenPlotMaking.R")
source("../Scripts/WasteWaterDataProccess.R")
source("../Scripts/CassesDataProccess.R")
source("../Scripts/HelperFunctions.R")
LatWasteFN <- "../../UntrackedData/WW SARS-COV-2 Data V5.xlsx"
LatSpringCaseFN="../../UntrackedData/SpringSemester_CasesByDorm.tsv"
LatFallCaseFN="../../UntrackedData/FallSemester_CasesByDorm.tsv"
HFGWasteFN = "../../UntrackedData/HFG data for stats preliminary 3-18-21.xlsx"
HFGCaseFN="../../UntrackedData/HighFreq_CaseData_2021-05-07.csv"
LatMMSDFN = "../../UntrackedData/MMSD_Cases.2021-05-21.csv"

```

```{r start up, include=FALSE}
HFGFrame=HFGInfo(HFGWasteFN)%>%
  select(Date,Site=Plant,Filter,Well,N1=N1GC,N2=N2GC,PMMoV=PMMOVGC,Pct_BCoV=BCoV,everything())%>%
  mutate(Filter=as.character(Filter),Well=as.character(Well))%>%
  na.omit()


HFGCaseDF=HFGCasesPARSER(HFGCaseFN)
Fullday=data.frame(Date=seq.Date(min(HFGCaseDF$Date),max(HFGCaseDF$Date),1))
HFGCaseDF=full_join(HFGCaseDF,Fullday,by=c("Date"))

# HFGCaseDF2=HFGCaseDF%>%
#       mutate(isna=ifelse(EpisodeCases==-999,"True","false"))%>%
#       mutate(EpisodeCases=ifelse(EpisodeCases==-999,NA,EpisodeCases))%>%
#       mutate(CollectedCases=ifelse(CollectedCases==-999,NA,CollectedCases))%>%
#       mutate(ConfirmedCases=ifelse(ConfirmedCases==-999,NA,ConfirmedCases))
# 
# HFGCaseDFroll2=HFGCaseDF2%>%
#       filter(!is.na(Site))%>%
#       arrange(Site,Date)%>%
#       group_by(Site)%>%
#       mutate(CollectedCases2=RollAvg(CollectedCases),EpisodeCases2=RollAvg(EpisodeCases),ConfirmedCases2=RollAvg(ConfirmedCases))%>%
#       ungroup()


LatCaseDF=CovidDataPARSER(LatSpringCaseFN,LatFallCaseFN,LatMMSDFN)

LatWasteDF=WasteWater(LatWasteFN)%>%
  mutate(Date=as.Date(Date))%>%
  filter(!is.na(Date),!is.na(N1),!is.na(Site))%>%
  filter(Date<mdy("6/5/2021"))%>%
  select(Date,Site,N1,N2,PMMoV,Pct_BCoV,AVG)
```




Clear linear relationship between N1 and its standard deviations

```{r Varience within groups}

HFGFrame%>%
  select(Date,Site,Filter,N1)%>%
  group_by(Site,Date)%>%
  summarize(mN1=exp(mean(log(N1))),vN1=var(N1))%>%
  ggplot()+geom_point(aes(x=mN1,y=sqrt(vN1),color=Site))+
  scale_y_log10()+scale_x_log10()+ggtitle("Mean vs Standard deviation of 9 points")

HFGVarNine=HFGFrame%>%
  select(Date,Site,Filter,N1)%>%
  group_by(Site,Date)%>%
  summarize(mN1=mean(N1),vN1=var(N1))


cor(HFGVarNine$mN1,sqrt(HFGVarNine$vN1))

HFGFrame%>%
  select(Date,Site,Filter,N1)%>%
  group_by(Site,Date,Filter)%>%
  summarize(mN1=mean(N1),vN1=var(N1))%>%
  ggplot()+geom_point(aes(x=mN1,y=sqrt(vN1),color=Site))+
  scale_y_log10()+scale_x_log10()+ggtitle("Mean vs Standard deviation of 3 points")



HFGVarThree=HFGFrame%>%
  select(Date,Site,Filter,N1)%>%
  group_by(Site,Date,Filter)%>%
  summarize(mN1=mean(N1),vN1=var(N1))


cor(HFGVarThree$mN1,sqrt(HFGVarThree$vN1),use="pairwise.complete.obs")
cor(HFGVarThree$mN1,HFGVarThree$vN1,use="pairwise.complete.obs")

# cases
# LM
# SD
# mean line
# collection, analysis
#
#
```

Generated LM from relationship

```{r validating,fig.height = 15, fig.width = 15,include=F}
T=8

HFGVar=HFGFrame%>%
  select(Date,Site,N1)%>%
  filter(N1<10e7)%>%
  group_by(Site,Date)%>%
  summarize(mN1=mean(N1),vN1=var(N1))

LM=lm(data=HFGVar,sqrt(vN1)~mN1-1)

LM

# HFGFrame%>%
#   select(Date,Site,N1,Filter)%>%
#   mutate(lower=N1-1.860*sqrt(207167*N1)/sqrt(9))%>%
#   mutate(Upper=N1+1.860*sqrt(207167*N1)/sqrt(9))%>%
#   #mutate(contzero=lower<0&Upper>0)
#   ggplot()+
#   geom_rect(aes(fill=Filter,ymin=lower,ymax=Upper,xmin=Date-.3,xmax=Date+.3),alpha=.1)+
#   geom_point(aes(x=Date,y=N1,color=Filter))+scale_y_log10()+facet_wrap(~Site)

```

```{r Extend to general data varience,fig.height = 15, fig.width = 15,include=F}
LatWasteDF%>%
  select(Date,Site,N1)%>%
  mutate(lower=N1-2*0.2196*N1)%>%
  mutate(Upper=N1+2*0.2196*N1)%>%
  #mutate(contzero=lower<0&Upper>0)
  ggplot()+
  geom_rect(aes(ymin=lower,ymax=Upper,xmin=Date-1,xmax=Date+1),fill="red",alpha=.1)+
  geom_point(aes(x=Date,y=N1))+facet_wrap(~Site)


```

using the strong relationship we can predict the standard deviation of the point to get a better understanding of the possible true values

```{r Compare madison method,fig.height = 15, fig.width = 15}
LatData=LatWasteDF%>%
  filter((Site=="Madison"))%>%
  select(Date,Site,N1)%>%
  mutate(lower=N1-2*0.2199*N1)%>%
  mutate(Upper=N1+2*0.2199*N1)
HFGData=HFGFrame%>%
  filter((Site=="Madison"))

#??lat data off shifted by one day??
N1Start=min(HFGFrame$Date)
N1End=max(HFGFrame$Date)


ggplot()+
  geom_rect(aes(ymin=lower,ymax=Upper,xmin=Date-1.3,xmax=Date-.7),fill="red",alpha=.1,data=LatData)+
  geom_point(aes(y=N1,color=Filter,x=Date,shape="High Frequency"),data=HFGData)+
  geom_point(aes(y=N1,x=Date-1,shape="Longitudinal"),data=LatData,size=2.5)+
  scale_y_log10()+
  scale_x_date(limits=c(N1Start,N1End))+ggtitle("Waste data and predicted 2 standard deviations")

```

```{r Extend,fig.height = 15, fig.width = 15}
LatData=LatWasteDF%>%
  select(Date,Site,N1)%>%
  mutate(lower=N1-2*0.2196*N1)%>%
  mutate(Upper=N1+2*0.2196*N1)

#??lat data off shifted by one day??
N1Start=min(HFGFrame$Date)
N1End=max(HFGFrame$Date)


ggplot()+
  geom_rect(aes(ymin=lower,ymax=Upper,xmin=Date-1,xmax=Date+1),fill="red",alpha=.1,data=LatData)+
  geom_point(aes(y=N1,x=Date),data=LatData,size=2.5)+
  facet_wrap(~Site)+
  scale_y_log10()+
  ggtitle("Waste data and predicted 2 standard deviations")

```

