---
title: "N1 measurement is the arithmetic mean of 3 replicates"
output: html_notebook
---

```{r}

library(ggpubr)
library(dplyr)


#Data Files and prep work
source("../Scripts/GenPlotMaking.R")
source("../Scripts/WasteWaterDataProccess.R")
source("../Scripts/CassesDataProccess.R")
source("../Scripts/HelperFunctions.R")

source("../Scripts/WasteShiny/PrepData.R", local = TRUE)

```

```{r Data set has comp to previous data sets, fig.height = 6, fig.width = 13}
MadLIMSDF=LIMSFullDF%>%
  filter(Site=="Madison")%>%
  select(Date,N1,N1Error)%>%
  mutate(Date=Date+1)

 MadHFDF=HFGFrame%>%
   filter((Site=="Madison"))
 
N1Start=min(MadHFDF$Date)-1
N1End=max(MadHFDF$Date)+1

MadLongDF=LatWasteDF%>%
  filter(Site=="Madison")%>%
  select(Date,N1)



MadBothDF=full_join(MadLIMSDF,MadHFDF,by=c("Date"))%>%
  rename(LIMSN1=N1.x,HFN1=N1.y)%>%
  mutate(Diff=HFN1-LIMSN1,Diff=ifelse(is.na(HFN1),LIMSN1,Diff),Diff=ifelse(is.na(LIMSN1),HFN1,Diff))%>%
  mutate(Missing=ifelse(is.na(HFN1),"N1 missing in HF data","No missing data"))%>%
  mutate(Missing=ifelse(is.na(LIMSN1),"N1 missing in LIMS data",Missing))

MadHFMeanDF=MadHFDF%>%
  filter(Site=="Madison")%>%
  group_by(Date)%>%
  summarise(N1GeoMean=exp(mean(log(N1),na.rm = TRUE)),N1Mean=mean(N1,na.rm = TRUE))


ggplot()+
  geom_point(aes(x=Date,y=N1,shape="HF DF",color=`Filter replicates`),data=MadHFDF)+
  geom_point(aes(x=Date-1,y=N1,shape="Longitudinal"), data = MadLongDF ,size=3)+
  geom_point(aes(x=Date-.25,y=N1GeoMean,shape="HF Geo Mean"),data = MadHFMeanDF,size=3)+
  geom_point(aes(x=Date+.25,y=N1Mean,shape="HF Mean"),data = MadHFMeanDF,size=3)+
  #geom_point(aes(x=Date-1,y=N1,shape="LIMS"),data = MadLIMSDF,size=3)+
  scale_y_log10()+
  scale_x_date(limits=c(N1Start,N1End))+
  ggtitle("Both datasets are identical to a point")+
  ylab("N1")+ Header_theme(ConfigOption)+
      theme(axis.text.x = element_text(size = ConfigOption$XAxisLabSiz, colour = "black"),
            axis.title.x = element_text(size = ConfigOption$GenFontSiz, colour = "black"),
            plot.margin = unit(c(.5,0,0,0), "cm"))


MadLongDF2=MadLongDF%>%
  mutate(Date=Date-1)

(MadAllMeans=full_join(MadHFMeanDF,MadLongDF2,by=c("Date"))%>%
  mutate(GeoMeanVsN1=abs(N1GeoMean-N1))%>%
  mutate(MeanVsN1=abs(N1Mean-N1))%>%
  filter(!is.na(GeoMeanVsN1)))

MadAllMeans%>%
  ggplot()+aes(x=Date)+
  geom_point(aes(y=MeanVsN1,color="mean"),size=2)+
  geom_point(aes(y=GeoMeanVsN1,color="geomean"),size=2)+
  scale_x_date(limits=c(N1Start,N1End))


(MadAllMeansRounded=MadAllMeans%>%
  mutate(N1GeoMean=round(N1GeoMean),N1Mean=round(N1Mean))%>%
  mutate(GeoMeanVsN1=abs(N1GeoMean-N1))%>%
  mutate(MeanVsN1=abs(N1Mean-N1)))

```

```{r Varience calculated}
MadBothDF%>%
  select(Date,HFN1,N1Error)%>%
  group_by(Date)%>%
  summarise(N1Error=mean(N1Error),HFN1Error=sd(HFN1)/sqrt(length(HFN1)))%>%
  ggplot()+
  aes(x=Date)+
  geom_point(aes(y=N1Error))+
  geom_point(aes(y=HFN1Error, color="HFN1Error"))+
  scale_x_date(limits=c(N1Start,N1End))

#
```