---
title: "Lat Model Work"
author: "Marlin"
date: "5/17/2021"
output: html_document
---

```{r}

library(ggpubr)
library(dplyr)
source("../Scripts/GenPlotMaking.R")
source("../Scripts/WasteWaterDataProccess.R")
source("../Scripts/CassesDataProccess.R")
source("../Scripts/HelperFunctions.R")
LatWasteFN <- "../../UntrackedData/WW SARS-COV-2 Data V5.xlsx"
LatSpringCaseFN="../../UntrackedData/SpringSemester_CasesByDorm.tsv"
LatFallCaseFN="../../UntrackedData/Oct2020toEndFall_CasesByDorm.tsv"
CovidFileName = "../../UntrackedData/MMSD_Cases.csv"


```

```{r}

knitr::opts_chunk$set(echo = TRUE,fig.width = 15,fig.height = 15)

LatCaseDormsDF=CovidDataDorms(LatSpringCaseFN,LatFallCaseFN)%>%
  mutate(Per_pos=100*Cases/Tests)%>%
  select(-negitive_tests)



covidData=CovidData(CovidFileName)%>%
  mutate(Per_pos=100*Cases/Tests)%>%
  select(Date,Site,Cases,Tests,Per_pos)
LatCaseDF=rbind(covidData,LatCaseDormsDF)

Fullday=data.frame(Date=seq.Date(min(LatCaseDF$Date),max(LatCaseDF$Date),1))
LatCaseDF=full_join(LatCaseDF,Fullday,by=c("Date"))%>%
  arrange(Site,Date)%>%
  group_by(Site)%>%
  mutate(rollingPer_pos=RollPerPos(Cases,Tests))%>%
  ungroup()

LatWasteDF=WasteWater(LatWasteFN)%>%
  mutate(Date=as.Date(Date))%>%
  mutate(GeoMean=(N1*N2)^.5)%>%
  filter(!is.na(Date),!is.na(N1))%>%
  filter(Date<mdy("6/5/2021"))

MMSDData=full_join(LatWasteDF,LatCaseDF,by=c("Site","Date"))%>%
  filter(!is.na(Site),!is.na(Date))


LatWasteDF%>%
  mutate(Month=format(Date,"%B"))%>%
  ggplot()+geom_boxplot(aes(x=Month,y=N1),fill="light blue")+geom_point(aes(x=Month,y=mean(N1)),shape = 4)+facet_wrap(~Site)#+scale_y_log10()

```

 
```{r}
SiteOffsetMatrix = function(CaseDF,WasteDF,seqminmax){
  cor.df=NA
  for (i in seqminmax){
    if(i!=min(seqminmax)){
      
    cor.df=cor.df%>%
      select(-Site)
    }
    TempCaseDF=CaseDF%>%
      mutate(Date=Date+i)
    MMSDDF=full_join(TempCaseDF,WasteDF,by=c("Site","Date"))%>%
    filter(!is.na(Site),!is.na(Date))
    TVec=MMSDDF%>%
      group_by(Site)%>%
      summarize("{i}":= cor(x = N1/PMMoV, y = rollingPer_pos, use = "pairwise.complete.obs"))
    cor.df=cbind(cor.df,TVec)
  }
  mincol=toString(min(seqminmax))
  maxcol=toString(max(seqminmax))
  cor.df=cor.df%>%
    select(-cor.df)%>%
    select(Site,!Site)%>%
    pivot_longer(mincol:maxcol)%>%
    group_by(Site)%>%
    mutate(bestCase=max(value))%>%
    mutate(bestAlpha=ifelse(value==bestCase,1,0))
  cor.df$name=factor(cor.df$name, levels=c(mincol:maxcol))
    return(cor.df)
}

SiteOffsetMatrix(LatCaseDF,LatWasteDF,-14:14)%>%
  ggplot(aes(y=Site, x=name)) + 
  geom_tile(aes(fill= value)) + geom_tile(aes(alpha=bestAlpha),fill="white",show.legend = FALSE)+theme(axis.text.x = element_text(angle = 90))+ scale_fill_continuous(type = "viridis")


```