---
title: "HFG interactive graphic"
author: "Marlin"
date: "4/3/2021"
output:
  pdf_document: default
  html_document: default
editor_options: 
  chunk_output_type: inline
---

```{r}
library(shiny)
library(ggpubr)
library(dplyr)
library(shinydashboard)


source("../Scripts/DataProccess.R")
Waterfilename <- "../../UntrackedData/WW SARS-COV-2 Data V5.xlsx"
CovidFileName = "../../UntrackedData/MMSD_Cases.csv"

TCovDF=CovidData(CovidFileName)

Spring="../../UntrackedData/SpringSemester_CasesByDorm.tsv"
Fall="../../UntrackedData/Oct2020toEndFall_CasesByDorm.tsv"
DCovDF=CovidDataDorms(Spring,Fall)

#Reads Transformed HFG Data
MWasteWater=WasteWater(Waterfilename)%>%
  mutate(Date=as.Date(Date))%>%
  filter(!is.na(Date),!is.na(N1))%>%
  filter(Date<mdy("6/5/2021"))



#Creates consistant jittering for data
myseed=1234567890



  
```

```{r}
maxShift=10
maxShifL=-10


#Parts Of Tab 1 defined outside for ease of use
TopDisc=div("")
BotDisc=div("Data source: DHS ------")
BotDisc2=div("Questions? Contact Marlin Lee mrlee6@wisc.edu or Steve Goldstein sgoldstein@wisc.edu")
#Creates buttons for Plant location,Line, and scale
Tab1=tabItem(tabName = "dashboardWIP",
            # Boxes need to be put in a row (or column)
    fluidRow(
    box(
        title = "Controls",
        selectInput(inputId = "Site", label = ("Site"),
                    choices = unique(DCovDF$Site),
                    multiple=T,
                    selected=c("UW-Sellery" ,"UW-LakeShore")),
      selectInput(inputId = "Vars", label = ("Varibles"),
                    choices = c("N1","N2","PMMoV","Cases"),
                    multiple=T,
                    selected=c("N1GC","Cases")),
      checkboxInput(inputId="Line",label=("Smoothed Line of Data"),value=T),
      selectInput(inputId = "scale", label = ("y scales"),
                    choices = c("log y scale","linear scale"),
                    selected="log y scale"),
      sliderInput("Offset", "Offset",min = maxShifL, max = maxShift,step=1,value=0)
      #sliderInput("Smoothed", "Data Smoothed",min = 0, max = 5,step=1,value=0)

    ),
    box(TopDisc,br(),div(plotOutput("plot1",inline=TRUE),style="overflow-x: scroll"), br(),BotDisc,BotDisc2)
))

#Defining of tab 2 for future use
Tab2=tabItem(tabName = "dashboard",
        fluidRow(
            box(
                title="Future Work"
            )
        )
)

#Creates UI for dashboard
ui <- dashboardPage(
    #top left descriptor
    dashboardHeader(title = "HFG Interactive graphic"),
    #left hand side tab selector
    dashboardSidebar(sidebarMenu(
        menuItem("DashboardWIP", tabName = "dashboardWIP", icon = icon("dashboard")),
        menuItem("Dashboard", tabName = "dashboard", icon = icon("dashboard"))
    )),
    #Contents of different tabs defined above
    dashboardBody(
        tabItems(
            Tab1,
            Tab2
            ))
)
```


```{r}
#create graphic                                       
server <- function(input, output) {
    #Filters data for right plants and variables
    filtered_data_PWaste<- reactive({
          return(filter(MWasteWater, MWasteWater$Site %in% input$Site))
    })
    
    filtered_data_PCov<- reactive({
          return(filter(DCovDF, Site %in% input$Site))
    })
    
    minC=reactive({
      return(min(filtered_data_PWaste()$Date)+input$Offset)
      })
    
    maxC=reactive({
      return(max(filtered_data_PWaste()$Date)+input$Offset)
      })
    
    buildplot = function(vari){
      if(vari=="Cases"){
        DormPlot=ggplot(data=filtered_data_PCov(),aes(y=Cases,x=Date))+
          geom_jitter(alpha=.7,height=0,width=.1,size=2)+
          facet_wrap(~Site, nrow = 1)+coord_cartesian(xlim=c(minC(), maxC()))+
          theme(text = element_text(size=20),strip.text.x = element_blank(),axis.text.x = element_blank(),axis.text.y = element_text(size = 15, colour = "black"))+ rremove("xlab")
        return(DormPlot)
      }
      #set.seed(myseed)
      #!!sym() reads string as a variable of the data frame
      DormPlot=ggplot(data=filtered_data_PWaste(),aes(y=!!sym(vari),x=Date))+geom_jitter(alpha=.7,height=0,width=.1,size=2)+ylab(vari)
      #adds mean line
      DormPlot = DormPlot+facet_wrap(~Site, nrow = 1)+theme(text = element_text(size=20),strip.text.x = element_blank(),axis.text.x = element_blank(),axis.text.y = element_text(size = 15, colour = "black"))+ rremove("xlab")
      if(input$scale=="log y scale"){
        DormPlot=DormPlot+scale_y_log10()
      }
      if(input$Line==TRUE){
        DormPlot=DormPlot+geom_smooth()
      }
        return(DormPlot)
    }
    #Creates list of ggplots for ggarange
    Make_Plots = reactive({
        plots=lapply(input$Vars,buildplot)
        return(plots)
    })
    #plots N1GC
    output$plot1<-renderPlot(
        width = function() 245+400*length(input$Site),
        height = function() 60+300*length(input$Vars),
        {

            plots=Make_Plots()
            #Add plant labels
            plots[[1]]=plots[[1]] + theme(strip.text.x = element_text(size = 20, colour = "black"))
            #add x axis labels
            plots[[length(plots)]]=plots[[length(plots)]] + theme(axis.title.x = element_text(size = 20, colour = "black"),axis.text.x = element_text(size = 15, colour = "black"))
            return(ggarrange(plotlist=plots,ncol =1))
        })
}

shinyApp(ui = ui, server = server)



```


```{r}
SevDayRollAvg = function(vectorT){
  CurrNum = vector(mode="double", length=length(7))
  SlideMeanVec=vector(mode="double", length=length(vectorT))
    for (i in 1:length(vectorT)){
      
      CurrNum[(i-1)%%7+1]=vectorT[i]
      print(mean(CurrNum,na.rm=T))
      
      SlideMeanVec[i]=mean(CurrNum,na.rm=T)
    }
  return(SlideMeanVec)
}
Fullday
seq.Date(min(LatCaseDF$Date),max(LatCaseDF$Date),1)
SevDayRollAvg(c(5,NA,5))
LatCaseDF%>%
  ggplot()+aes(x=Date,y=Per_pos)+geom_point()+geom_line(aes(y=rollingPer_pos),color="Red")+facet_wrap(~Site, nrow = 1)+
  scale_x_date(limits = c(mdy("2/6/2021"),mdy("2/15/2021")))
(1.7316017+3.5714286+0.4184100+1.2765957)/7
```