---
title: "WasteWater_Difficultys"
author: "Marlin"
date: "6/1/2021"
output:
  pdf_document: default
  html_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```


```{r Importing, include=FALSE}
library(shiny)
library(ggpubr)
library(dplyr)
library(shinydashboard)
library(shinyjqui)
library(shinycssloaders)

#Data Files and prepwork
source("../Scripts/GenPlotMaking.R")
source("../Scripts/WasteWaterDataProccess.R")
source("../Scripts/CassesDataProccess.R")
source("../Scripts/HelperFunctions.R")
LatWasteFN <- "../../UntrackedData/WW SARS-COV-2 Data V5.xlsx"
LatSpringCaseFN="../../UntrackedData/SpringSemester_CasesByDorm.tsv"
LatFallCaseFN="../../UntrackedData/FallSemester_CasesByDorm.tsv"
HFGWasteFN = "../../UntrackedData/HFG data for stats preliminary 3-18-21.xlsx"
HFGCaseFN="../../UntrackedData/HighFreq_CaseData_2021-05-07.csv"
LatMMSDFN = "../../UntrackedData/MMSD_Cases.2021-05-21.csv"

```

```{r start up, include=FALSE}
HFGFrame=HFGInfo(HFGWasteFN)%>%
  select(Date,Site=Plant,Filter,Well,N1=N1GC,N2=N2GC,PMMoV=PMMOVGC,Pct_BCoV=BCoV,everything())%>%
  mutate(Filter=as.character(Filter),Well=as.character(Well))%>%
  na.omit()


HFGCaseDF=HFGCasesPARSER(HFGCaseFN)
Fullday=data.frame(Date=seq.Date(min(HFGCaseDF$Date),max(HFGCaseDF$Date),1))
HFGCaseDF=full_join(HFGCaseDF,Fullday,by=c("Date"))

HFGCaseDF2=HFGCaseDF%>%
      mutate(isna=ifelse(EpisodeCases==-999,"True","false"))%>%
      mutate(EpisodeCases=ifelse(EpisodeCases==-999,NA,EpisodeCases))%>%
      mutate(CollectedCases=ifelse(CollectedCases==-999,NA,CollectedCases))%>%
      mutate(ConfirmedCases=ifelse(ConfirmedCases==-999,NA,ConfirmedCases))

HFGCaseDFroll2=HFGCaseDF2%>%
      filter(!is.na(Site))%>%
      arrange(Site,Date)%>%
      group_by(Site)%>%
      mutate(CollectedCases2=RollAvg(CollectedCases),EpisodeCases2=RollAvg(EpisodeCases),ConfirmedCases2=RollAvg(ConfirmedCases))%>%
      ungroup()


LatCaseDF=CovidDataPARSER(LatSpringCaseFN,LatFallCaseFN,LatMMSDFN)%>%
  select(Date,Site,Cases,Tests,Per_pos,rollingPer_pos,SevCases)%>%
  mutate(SevTest=RollAvg(Tests))

LatWasteDF=WasteWater(LatWasteFN)%>%
  mutate(Date=as.Date(Date))%>%
  filter(!is.na(Date),!is.na(N1),!is.na(Site))%>%
  filter(Date<mdy("6/5/2021"))%>%
  select(Date,Site,N1,N2,PMMoV,Pct_BCoV,AVG)
```

```{r paused down, fig.height = 8, fig.width = 15}
N1Start=min(HFGFrame$Date)
N1End=max(HFGFrame$Date)
CStart=min(HFGCaseDF$Date)
CEnd=max(HFGCaseDF$Date)
SiteOptions=c("Hudson","Kenosha","Platteville","Madison", "Merrill","Plymouth","River Falls","Sun Prairie","Wausau","Oshkosh")


HFGCaseDFroll2%>%
  ggplot()+aes(x=Date)+geom_point(aes(y=ConfirmedCases,x=Date-2))+
  scale_x_date(limits=c(N1Start,N1End))+
  facet_wrap(~Site,scales = "free")+ggtitle("Sparse HFG Case Data")
  
SiteOptions2=c("Kenosha","Madison", "Sun Prairie","Wausau","Oshkosh")

HFGFrame%>%
  filter(!is.na(N1),Site %in% SiteOptions2)%>%
  group_by(Site)%>%
  summarize(`N1 testing Range`=max(Date)-min(Date),NDays=length(unique(Date)))

SiteOptions2=c("Kenosha","Madison", "Sun Prairie","Wausau")
```

```{r No Clear relation, fig.height = 6, fig.width = 16}
SiteOptions3=c("Kenosha","Madison")

p1=HFGFrame%>%
  filter(Site %in% SiteOptions2)%>%
  ggplot()+aes(x=Date,y=N1)+
  geom_point()+
#  scale_y_log10()+
  scale_x_date(limits=c(N1Start,N1End))+
  facet_wrap(~Site,nrow = 1, scales = "free_y")

p2=HFGCaseDFroll2%>%
  filter(Site %in% SiteOptions2)%>%
  ggplot()+aes(x=Date)+
  #geom_point(aes(y=CollectedCases),color="red")+
  #geom_point(aes(y=EpisodeCases),color="blue")+
  geom_point(aes(y=ConfirmedCases))+
  geom_line(aes(y=ConfirmedCases2,color="7 day average"))+
  scale_x_date(limits=c(N1Start,N1End))+
  facet_wrap(~Site,nrow = 1, scales = "free_y")

#EpisodeCases    ConfirmedCases CollectedCases
annotate_figure(top=text_grob("No clear pattern partially due to short time frame",size=15),ggarrange(p1,p2,nrow = 2,align="hv",common.legend = T))
```

```{r outliers PMMoV, fig.height = 6, fig.width = 13}

HFGFrame%>%
  filter(Site %in% SiteOptions2)%>%
  mutate(marked=ifelse(PMMoV<1*10^7,"Low PMMoV","MAIN G"))%>%
  mutate(marked=ifelse(PMMoV>1*10^8,"High PMMoV",marked))%>%
  ggplot()+aes(x=PMMoV,y=N1,color=marked)+geom_point()+scale_y_log10()+
  scale_x_log10()+facet_wrap(~Site)+ggtitle("N1 Vs PMMoV looking for trend")

HFGFrame%>%
  filter(Site %in% SiteOptions2)%>%
  mutate(marked=ifelse(PMMoV<1*10^7,"Low PMMoV","MAIN G"))%>%
  mutate(marked=ifelse(PMMoV>1*10^8,"High PMMoV",marked))%>%
  ggplot()+aes(x=Date,y=N1,color=marked)+geom_point()+
  scale_y_log10()+facet_wrap(~Site)+ggtitle("N1 Vs Date using categories from previous graph")

```

```{r outliers Per_Bcov, fig.height = 6, fig.width = 13}

HFGFrame%>%
  filter(Site %in% SiteOptions2)%>%
  filter(N1<2e6)%>%
  mutate(marked=ifelse(Pct_BCoV<.5,"Low %Bcov","MAIN G"))%>%
  mutate(marked=ifelse(Pct_BCoV>10,"High %Bcov",marked))%>%
  ggplot()+aes(x=Pct_BCoV,y=N1,color=marked)+geom_point()+
  #scale_y_log10()+
  #scale_x_log10()+
  facet_wrap(~Site)+
  ggtitle("N1 Vs PMMoV looking for trend")
#, scales = "free"
#scale_x_log10()+,color=marked

HFGFrame%>%
  filter(Site %in% SiteOptions2)%>%
  mutate(marked=ifelse(Pct_BCoV<.5,"Low %Bcov","MAIN G"))%>%
  mutate(marked=ifelse(Pct_BCoV>10,"High %Bcov",marked))%>%
  ggplot()+aes(x=Date,y=N1,color=marked)+geom_point()+
  scale_y_log10()+facet_wrap(~Site)+
  ggtitle("N1 Vs Date using categories from previous graph")
#meam=data.frame(a=1:1000)
#meam$b=30*runif(1000)-15
#meam%>%
#  mutate(noiscor=a+b)%>%
#  ggplot()+geom_point(aes(x=a,y=noiscor))+
#  scale_y_log10()+
#  scale_x_log10()
```

```{r Thresholding Dorms, fig.height = 8, fig.width = 15}
shift=-0
LeftDate=min(LatWasteDF$Date)
RightDate=max(LatWasteDF$Date)
p1=LatWasteDF%>%
  filter((Site=="UW-Sellery")|(Site=="UW-LakeShore"))%>%
  ggplot()+aes(x=Date,y=N1)+geom_point(aes(color=N1>5e4))+
  #scale_y_log10()+
  #geom_smooth(span=.42)+
  facet_wrap(~Site)+
  scale_x_date(limits=c(LeftDate,RightDate))

p2=LatCaseDF%>%
  filter((Site=="UW-Sellery")|(Site=="UW-LakeShore"))%>%
  ggplot()+aes(x=Date)+
  geom_point(aes(y=Cases))+
  geom_line(aes(y=SevCases))+
  facet_wrap(~Site,scales="free_y")+
  scale_x_date(limits=c(LeftDate+shift,RightDate+shift))

p3=LatCaseDF%>%
  filter((Site=="UW-Sellery")|(Site=="UW-LakeShore"))%>%
  filter(Tests<2000)%>%
  ggplot()+aes(x=Date)+
  geom_point(aes(y=Tests,color="Tests"))+
  geom_line(aes(y=SevTest,color="Tests"))+
  facet_wrap(~Site,scales="free_y")+
  scale_x_date(limits=c(LeftDate+shift,RightDate+shift))

p4=LatCaseDF%>%
  filter(Per_pos<50)%>%
  filter((Site=="UW-Sellery")|(Site=="UW-LakeShore"))%>%
  ggplot()+aes(x=Date)+
  geom_point(aes(y=Per_pos,color="Per_pos"))+
  geom_line(aes(y=rollingPer_pos,color="Per_pos"))+
  facet_wrap(~Site,scales="free_y")+
  scale_x_date(limits=c(LeftDate+shift,RightDate+shift))

annotate_figure(top=text_grob("Dorm data with thresholding",size=15),ggarrange(plotlist = list(p1,p2),nrow = 2,align="hv",common.legend = T))

```

```{r Thresholding Gen, fig.height = 16, fig.width = 15}
shift=-0
LeftDate=min(LatWasteDF$Date)
RightDate=max(LatWasteDF$Date)
p1=LatWasteDF%>%
  filter((Site=="Madison"))%>%
  ggplot()+aes(x=Date,y=N1)+geom_point(aes(color=N1>5e4))+
  scale_y_log10()+
  #geom_smooth(span=.42)+
  facet_wrap(~Site)+
  scale_x_date(limits=c(LeftDate,RightDate))

p2=LatCaseDF%>%
  filter((Site=="Madison"))%>%
  ggplot()+aes(x=Date)+
  geom_point(aes(y=Cases,color="Cases"))+
  geom_line(aes(y=SevCases,color="Cases"))+
  facet_wrap(~Site,scales="free_y")+
  scale_x_date(limits=c(LeftDate+shift,RightDate+shift))

p3=LatCaseDF%>%
  filter((Site=="Madison"))%>%
  filter(Tests<2000)%>%
  ggplot()+aes(x=Date)+
  geom_point(aes(y=Tests,color="Tests"))+
  geom_line(aes(y=SevTest,color="Tests"))+
  facet_wrap(~Site,scales="free_y")+
  scale_x_date(limits=c(LeftDate+shift,RightDate+shift))

p4=LatCaseDF%>%
  filter(Per_pos<50)%>%
  filter((Site=="Madison"))%>%
  ggplot()+aes(x=Date)+
  geom_point(aes(y=Per_pos,color="Per_pos"))+
  geom_line(aes(y=rollingPer_pos,color="Per_pos"))+
  facet_wrap(~Site,scales="free_y")+
  scale_x_date(limits=c(LeftDate+shift,RightDate+shift))

ggarrange(plotlist = list(p1,p2,p3,p4),nrow = 4,align="hv")

```

```{r boxplots, fig.height = 8, fig.width = 15}
shift=-0
LeftDate=min(LatWasteDF$Date)
RightDate=max(LatWasteDF$Date)

p1=LatWasteDF%>%
  filter((Site=="UW-Sellery")|(Site=="UW-LakeShore"))%>%
  mutate(Loc="10")%>%
  mutate(Loc=ifelse(Site=="UW-LakeShore"&Date<mdy("1/20/2021"),"4",Loc))%>%
  mutate(Loc=ifelse(Site=="UW-LakeShore"&Date<mdy("12/23/2020"),"3",Loc))%>%
  mutate(Loc=ifelse(Site=="UW-LakeShore"&Date<mdy("11/18/2020"),"2",Loc))%>%
  mutate(Loc=ifelse(Site=="UW-LakeShore"&Date<mdy("10/9/2020"),"1",Loc))%>%
  
  mutate(Loc=ifelse(Site=="UW-Sellery"&Date<mdy("2/5/2021"),"4",Loc))%>%
  mutate(Loc=ifelse(Site=="UW-Sellery"&Date<mdy("12/8/2020"),"3",Loc))%>%
  mutate(Loc=ifelse(Site=="UW-Sellery"&Date<mdy("11/18/2020"),"2",Loc))%>%
  mutate(Loc=ifelse(Site=="UW-Sellery"&Date<mdy("10/11/2020"),"1",Loc))%>%
  ggplot()+
  geom_boxplot(aes(y=N1,x=Date,group=Loc),fill="light blue")+
  scale_y_log10()+
  facet_wrap(~Site)
  #scale_x_date(limits=c(LeftDate,RightDate))

p2=LatCaseDF%>%
  filter((Site=="UW-Sellery")|(Site=="UW-LakeShore"))%>%
  ggplot()+aes(x=Date)+
  geom_point(aes(y=Cases))+
  geom_line(aes(y=SevCases))+
  facet_wrap(~Site,scales="free_y")+
  scale_x_date(limits=c(LeftDate+shift,RightDate+shift))

annotate_figure(top=text_grob("Dorm data with arbitrary boxing",size=15),ggarrange(p1,p2,nrow = 2,align="hv",common.legend = T))
```

```{r madison messure same data}

LatData=LatWasteDF%>%
  filter((Site=="Madison"))
HFGData=HFGFrame%>%
  filter((Site=="Madison"))

#??lat data off shifted by one day??

ggplot()+geom_point(aes(y=N1,color=Filter,x=Date,shape="High Frequency"),data=HFGData)+
  geom_point(aes(y=N1,x=Date-1,shape="Longitudinal"),data=LatData,size=2.5)+
  scale_x_date(limits=c(N1Start,N1End))+ggtitle("HFG and Longitudinal data match")

```