---
params:
  BaseDir: "Z:/"
  ##BaseDir: "/Volumes/byandell/"
title: "N1 measurement is the arithmetic mean of 3 replicates"
output: html_notebook
---

```{r}

library(ggpubr)
library(dplyr)
library(tidyverse)
library(readxl)
#BiocManager::install("limma")
#Data Files and prep work
source("../../lib/GenPlotMaking.R")
source("../../lib/WasteWaterDataProccess.R")
source("../../lib/CasesDataProccess.R")
source("../../lib/HelperFunctions.R")
```

```{r DF Set Up, include=TRUE}
BaseDir <- params$BaseDir
LatMMSDFN  <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/MMSD_Cases.csv")
LatSpringDormFN  <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/SpringSemester_CasesByDorm.TSV")
LatFallDormFN  <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/FallSemester_CasesByDorm.TSV")
HFGWasteFN  <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/HFG data for stats corrected 071421.xlsx")

LIMSFN <- paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/WATERMICRO_WW_COVID-2021-06-30 17 40.xlsx")

HFGCasesFN  <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/HighFreq_CaseData_2021-05-07.csv")

LatCaseDF <- CovidDataPARSER(
  LatSpringDormFN, LatFallDormFN,MMSDFN = LatMMSDFN
  )%>% 
  
  filter(!is.na(Site)) %>%
  select(Date,Site,Cases,Tests,Per_pos)

HFGCaseDF <- HFGCasesPARSER(FN = HFGCasesFN)%>%
  filter(!is.na(Site))%>%
  mutate(Tests=NA,Per_pos=NA)%>%
  select(Date,Site,Cases=ReportedCases,Tests,Per_pos)%>%
  mutate(Cases = ifelse(Cases==-999,2.5,Cases))%>%
  filter(Site!="Madison")

FullCase <- bind_rows(HFGCaseDF,LatCaseDF)

FullCaseRoll <- RollPerPos(FullCase,"Cases","Tests",Facet="Site",n = 14)%>%
  filter(Per_pos!=-500)

LIMSFullDF <- LIMSDataPARSER(LIMSFN)%>%
  select(Date,Site, BCoV, N1,N1Error,N2, N2Error,PMMoV,Pop,FlowRate)

HFGFrame <- HFGWastePARSER(HFGWasteFN)%>%
  rename(Site=Plant,N1=N1GC,N2=N2GC,PMMoV=PMMOVGC,Pct_BCoV=BCoV)%>%
  mutate(Filter=as.character(Filter),Well=as.character(Well))%>%
  rename(`Filter replicates`=Filter)
```

```{r Data set has comp to previous data sets, fig.height = 6, fig.width = 13}
MadLIMSDF=LIMSFullDF%>%
  filter(Site=="Madison")%>%
  select(Date,N1,N1Error)%>%
  mutate(Date=Date+1)

 MadHFDF=HFGFrame%>%
   filter((Site=="Madison"))
 
N1Start=min(MadHFDF$Date)-1
N1End=max(MadHFDF$Date)+1

MadLongDF=LIMSFullDF%>%
  filter(Site=="Madison")%>%
  select(Date,N1)



MadBothDF=full_join(MadLIMSDF,MadHFDF,by=c("Date"))%>%
  rename(LIMSN1=N1.x,HFN1=N1.y)%>%
  mutate(Diff=HFN1-LIMSN1,Diff=ifelse(is.na(HFN1),LIMSN1,Diff),Diff=ifelse(is.na(LIMSN1),HFN1,Diff))%>%
  mutate(Missing=ifelse(is.na(HFN1),"N1 missing in HF data","No missing data"))%>%
  mutate(Missing=ifelse(is.na(LIMSN1),"N1 missing in LIMS data",Missing))

MadHFMeanDF=MadHFDF%>%
  filter(Site=="Madison")%>%
  group_by(Date)%>%
  summarise(N1GeoMean=exp(mean(log(N1),na.rm = TRUE)),N1Mean=mean(N1,na.rm = TRUE))


ggplot()+
  geom_point(aes(x=Date,y=N1,shape="HF DF",color=`Filter replicates`),data=MadHFDF)+
  geom_point(aes(x=Date,y=N1,shape="Longitudinal"), data = MadLongDF ,size=3)+
  geom_point(aes(x=Date,y=N1GeoMean,shape="HF Geo Mean"),data = MadHFMeanDF,size=3)+
  geom_point(aes(x=Date,y=N1Mean,shape="HF Mean"),data = MadHFMeanDF,size=3)+
  #geom_point(aes(x=Date-1,y=N1,shape="LIMS"),data = MadLIMSDF,size=3)+
  scale_y_log10()+
  scale_x_date(limits=c(N1Start,N1End))+
  ggtitle("Both datasets are identical to a point")+
  ylab("N1")


MadLongDF2=MadLongDF%>%
  mutate(Date=Date-1)

(MadAllMeans=full_join(MadHFMeanDF,MadLongDF2,by=c("Date"))%>%
  mutate(GeoMeanVsN1=abs(N1GeoMean-N1))%>%
  mutate(MeanVsN1=abs(N1Mean-N1))%>%
  filter(!is.na(GeoMeanVsN1)))

MadAllMeans%>%
  ggplot()+aes(x=Date)+
  geom_point(aes(y=MeanVsN1,color="mean"),size=2)+
  geom_point(aes(y=GeoMeanVsN1,color="geomean"),size=2)+
  scale_x_date(limits=c(N1Start,N1End))


(MadAllMeansRounded=MadAllMeans%>%
  mutate(N1GeoMean=round(N1GeoMean),N1Mean=round(N1Mean))%>%
  mutate(GeoMeanVsN1=abs(N1GeoMean-N1))%>%
  mutate(MeanVsN1=abs(N1Mean-N1)))

```

```{r Varience calculated}
MadBothDF%>%
  select(Date,HFN1,N1Error)%>%
  group_by(Date)%>%
  summarise(N1Error=mean(N1Error),HFN1Error=sd(HFN1)/sqrt(length(HFN1)))%>%
  ggplot()+
  aes(x=Date)+
  geom_point(aes(y=N1Error))+
  geom_point(aes(y=HFN1Error, color="HFN1Error"))+
  scale_x_date(limits=c(N1Start,N1End))

#
```
