library(devtools)

document()
build_vignettes(quiet=FALSE)
dir.create("inst/doc", recursive = TRUE)
file.copy(dir("doc", full.names=TRUE), "inst/doc", overwrite=TRUE)
build(vignettes = FALSE, args = c("--resave-data"))
install(quick=FALSE)
check(args = c("--no-tests"), vignettes = FALSE)
test()
vignette(package = "DSIWastewater")
vignette("vignettes_DHSTopLevelAnalysis_Outlier")