---
title: "OutlierDecMethodFinder"
author: "Marlin"
date: '2022-06-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r pressure, echo=FALSE}
library(DSIWastewater)
library(dplyr)
```

```{r helper funcs, fig.height=15,fig.width=14.25}
Cat.map <- c("major increase" = 2, "moderate increase" = 1, 
              "fluctuating" = 0, "no change" = 0,
              "moderate decrease" = -1, "major decrease" = -2)  
convertCatToNumeric <- function(DF, Schema = Cat.map){
  DF%>%
    mutate(Catagory = {{Schema}}[Catagory])
}
addMissingPredictions <- function(DF){
  RetDF <- DF%>%
    group_by(WWTP, Method)%>%
    tidyr::fill(Catagory, .direction = "down")
  return(RetDF)
  
}

classMeanDiff <- function(DF, 
                          rawVec,
                          BaseVec = Loess){
  DF%>% 
    mutate(Error = abs({{BaseVec}} - {{rawVec}}))%>%
    summarise(Mean_Error = mean(Error, na.rm = TRUE))
}
classMeanDiffLongFormat <- function(DF, 
                          rawVec,
                          BaseVec = Loess){
  DF%>%
  convertCatToNumeric()%>%
    pivot_wider(id_cols = c(date, WWTP),
                values_from = Catagory, 
                names_from = Method)%>% 
    mutate(Error = abs({{BaseVec}} - {{rawVec}}))%>%
    summarise(Mean_Error = mean(Error, na.rm = TRUE))
}


comparePredOutputs <- function(DF){
  plot_DF <- DF%>%
    #addMissingPredictions()%>%
    mutate(days_elapsed = 14)%>%
    pivot_wider(id_cols = c(date, WWTP, days_elapsed),
                values_from = Catagory, 
                names_from = Method)%>%
    filter(sars_adj_log10_Filtered!=sars_cov2_adj_load_log10)%>%
    pivot_longer(
               c(Loess, sars_adj_log10_Filtered, sars_cov2_adj_load_log10),
               values_to = "Catagory", 
                names_to = "Method")%>%
    ungroup()
  
  ret_plot <- createDHSMethod_Plot(plot_DF, created_data, 
                 PointVal = c( "sars_cov2_adj_load_log10",
                               "sars_adj_log10_Filtered"),
                 LineVal = "Loess")
  print(ret_plot)
  return(c(classMeanDiffLongFormat(plot_DF,sars_cov2_adj_load_log10),
           classMeanDiffLongFormat(plot_DF,sars_adj_log10_Filtered)))
}
comparePredOutputs(reg_estimates_data)

```


```{r create worksheet4}
data(wastewater_data, package = "DSIWastewater")

workset4_data <- buildWorkSheet4(wastewater_data)

#Only show Site with more than 180 measurements for vignette for brevity
workset4_data <- workset4_data[workset4_data$n >= 180,]


workset4_Smooth_data <- do.call(rbind,
                              lapply(
                                split(workset4_data,~WWTP),
                                LoessSmoothMod))

```

```{r run regression analysis}
reg_estimates_data <- buildRegressionEstimateTable(created_data,
                               RunOn = c("Loess"),
                               verbose = TRUE)%>%
  convertCatToNumeric()%>%
    pivot_wider(id_cols = c(date, WWTP),
                values_from = Catagory, 
                names_from = Method)
head(reg_estimates_data)


BaseLineMetric <- reg_estimates_data%>%
  select(date, WWTP, Loess)
```

```{r quality messure}

classMeanDiffLongFormat(reg_estimates_data, sars_cov2_adj_load_log10)
classMeanDiffLongFormat(reg_estimates_data, Loess, sars_adj_log10_Filtered)
```

```{r}
RunQuintSpec <- function(n, verbose = FALSE){
  df_data <- computeJumps(workset4_Smooth_data)
  ranked_data <- rankJumps(df_data)
  ranked_quantile_data <- computeRankQuantiles(ranked_data)
  classied_data <- flagOutliers(ranked_quantile_data, n,
                                col = MessureRank.quantile)
  created_data <- RemoveOutliers(classied_data)
  reg_estimates_data <- buildRegressionEstimateTable(created_data,
                               RunOn = c("sars_adj_log10_Filtered"))%>%
          convertCatToNumeric()%>%
          select(date,WWTP, sars_adj_log10_Filtered = Catagory)%>%
          dplyr::full_join(BaseLineMetric, by = c("date", "WWTP"))%>%
          classMeanDiff(Loess, sars_adj_log10_Filtered)
    if(verbose){
      print(paste("n",n))
      print(paste("mean Removed:",
                mean(is.na(created_data$sars_adj_log10_Filtered),
                     na.rm=TRUE)))
      print(paste("Mean Error:",reg_estimates_data$Mean_Error))
    }
  reg_estimates_data$index <- n
  reg_estimates_data$perRemoved <- created_data$sars_adj_log10_Filtered%>%
    is.na()%>%
    mean()
  return(reg_estimates_data)
}
max = .2
n = 100
Test_Res3 <- lapply((0:n)*(max/n),RunQuintSpec)

```
```{r}
M <- data.table::rbindlist(Test_Res2)
M$index <- (0:n)*(max/n)
plot(M$index, M$Mean_Error)
```

```{r}
df_data <- computeJumps(workset4_Smooth_data)
ranked_data <- rankJumps(df_data)
ranked_quantile_data <- computeRankQuantiles(ranked_data)
classied_data <- flagOutliers(ranked_quantile_data, n,
                            col = MessureRank.quantile)

reg_estimates_data <- buildRegressionEstimateTable(created_data,
                              RunOn = c("sars_adj_log10_Filtered"))%>%
          convertCatToNumeric()


#%>%
          select(date,WWTP, sars_adj_log10_Filtered = Catagory)%>%
          dplyr::full_join(BaseLineMetric, by = c("date", "WWTP"))%>%
          classMeanDiff(Loess, sars_adj_log10_Filtered)

```
