---
title: "FullDataParsingAndAnalysis"
author: "Marlin"
date: "6/8/2021"
output: html_document
---


```{r setup, include=FALSE}
library(shiny)
library(ggpubr)
library(dplyr)
library(shinydashboard)
library(shinyjqui)
library(shinycssloaders)

#Data Files and prep work
source("../Scripts/GenPlotMaking.R")
source("../Scripts/WasteWaterDataProccess.R")
source("../Scripts/CasesDataProccess.R")
source("../Scripts/HelperFunctions.R")


source("../Scripts/WasteShiny/PrepData.R", local = TRUE)


LIMSFullDFRoll=RollAvg(LIMSFullDF,n=21,var=c("N1","N1Error"))%>%
  filter(!is.nan(N1)&!is.nan(N1Error))%>%
  select(Date,Site,N1,N1Error)

```

```{r LIMS vs long dataset, include = FALSE}



MadLIMSDF=LIMSFullDF%>%
  filter(Site=="Madison")%>%
  select(Date,N1)%>%
  mutate(Date=Date+1)

 MadHFDF=HFGFrame%>%
   filter((Site=="Madison"))

MadLongDF=LatWasteDF%>%
  filter(Site=="Madison")%>%
  select(Date,N1)

MadBothDF=full_join(MadLIMSDF,MadLongDF,by=c("Date"))%>%
  rename(LongN1=N1.y,LIMSN1=N1.x)%>%
  mutate(Diff=LIMSN1-LongN1,Diff=ifelse(is.na(LIMSN1),LongN1,Diff),Diff=ifelse(is.na(LongN1),LIMSN1,Diff))%>%
  mutate(Missing=ifelse(is.na(LIMSN1),"N1 missing in Full data","No missing data"))%>%
  mutate(Missing=ifelse(is.na(LongN1),"N1 missing in Longitudinal data",Missing))


N1Start=min(MadHFDF$Date)-1
N1End=max(MadHFDF$Date)+1

MadBothDF%>%
  ggplot()+geom_point(aes(x=Date,y=Diff,color=Missing))+
  ggtitle("Both datasets are identical to a point")+
  ylab("LIMS N1 - Longitudinal N1")+ Header_theme(ConfigOption)+
      theme(axis.text.x = element_text(size = ConfigOption$XAxisLabSiz, colour = "black"),
            axis.title.x = element_text(size = ConfigOption$GenFontSiz, colour = "black"),
            plot.margin = unit(c(.5,0,0,0), "cm"))
MadBothDF%>%
  ggplot()+geom_jitter(aes(x=Date,y=LongN1,color="Longitudinal"),width=0,height=20000)+
  geom_jitter(aes(x=Date,y=LIMSN1,color="LIMS"),width=0,height=20000)+
  geom_vline(xintercept = N1Start,linetype="dashed")+
  geom_vline(xintercept = N1End,linetype="dashed")+
  ggtitle("Both datasets are identical to a point")+
  ylab("N1")+ Header_theme(ConfigOption)+
      theme(axis.text.x = element_text(size = ConfigOption$XAxisLabSiz, colour = "black"),
            axis.title.x = element_text(size = ConfigOption$GenFontSiz, colour = "black"),
            plot.margin = unit(c(.5,0,0,0), "cm"))


```



```{r Summary of the data}
SiteOptions=c("Hudson","Kenosha","Platteville","Madison", "Merrill","Plymouth","River Falls","Sun Prairie","Wausau","Oshkosh")

MadisonLIMSData=LIMSFullDF%>%
  filter(grepl("Madison",Site))%>%
  group_by(Site)%>%
  summarise(n=n(),Dur=max(Date)-min(Date),min=min(Date),max=max(Date))
UWLIMSData=LIMSFullDF%>%
  filter(grepl("UW",Site))%>%
  group_by(Site)%>%
  summarise(n=n(),Dur=max(Date)-min(Date),min=min(Date),max=max(Date))
HFLIMSData=LIMSFullDF%>%
  filter(Site %in% SiteOptions)%>%
  group_by(Site)%>%
  summarise(n=n(),Dur=max(Date)-min(Date),min=min(Date),max=max(Date))

LIMSFullDF%>%
  group_by(Site)%>%
  summarise(n=n(),Dur=max(Date)-min(Date),MeanP=mean(Pop,na.rm=TRUE))%>%
  arrange(desc(MeanP))
LargePopAreas=c("Madison","Hudson","Kenosha","Wausau","Oshkosh")

```

```{r error scales lin with N1, fig.height = 6, fig.width = 13}


LIMSFullDF%>%
  ggplot()+aes(x=N1,y=N1Error)+geom_point()+
  scale_y_log10()+
  scale_x_log10()+ 
  Header_theme(ConfigOption)+
      theme(axis.text.x = element_text(size = ConfigOption$XAxisLabSiz, colour = "black"),
            axis.title.x = element_text(size = ConfigOption$GenFontSiz, colour = "black"),
            plot.margin = unit(c(.5,0,0,0), "cm"))



LIMSFullDF%>%
  ggplot()+aes(x=N2,y=N2Error)+
  geom_point()+
  scale_y_log10()+
  scale_x_log10()+ 
  Header_theme(ConfigOption)+
      theme(axis.text.x = element_text(size = ConfigOption$XAxisLabSiz, colour = "black"),
            axis.title.x = element_text(size = ConfigOption$GenFontSiz, colour = "black"),
            plot.margin = unit(c(.5,0,0,0), "cm"))

```

```{r rig testing}
N1ZPrep=LIMSFullDF%>%
  mutate(N1ErrorNorm=N1Error/N1)%>%
  filter(!is.na(N1ErrorNorm))%>%
  filter(N1ErrorNorm>0,N1ErrorNorm!=Inf)%>%
  summarise(meanNorm=mean(N1ErrorNorm),SDNorm=sqrt(var(N1ErrorNorm)),
            mean=mean(N1Error),SD=sqrt(var(N1Error)),
            regMean=mean(N1),regSE=sqrt(var(N1)))

LIMSFullDF%>%
  select(Date,N1,N1Error)%>%
  mutate(N1ErrorNorm=N1Error/N1)%>%
  filter(N1ErrorNorm>0,N1ErrorNorm!=Inf)%>%
  mutate(meanN1Norm=N1ZPrep$regMean,
         SDN1Norm=N1ZPrep$regSE,
         meanError=N1ZPrep$mean,
         SDError=N1ZPrep$SD,
         RegMean=N1ZPrep$regMean,
         RegSE=N1ZPrep$regSE)%>%
  mutate(ZScoreNorm=(N1ErrorNorm-meanN1Norm)/SDN1Norm,
         ZScore=(N1-RegMean)/RegSE,
         ZScoreError=(N1Error-meanError)/SDError)%>%
  ggplot()+
  #geom_bar(aes(x=ZScore))
  geom_point(aes(x=N1,y=ZScoreError))+
  scale_y_log10()+
  scale_x_log10()
  #scale_y_continuous(limits=c(-3000,2000))
#,y=ZScoreNorm
```
```{r ouliers with rolling average and predicted var}
CriticalPoint=5
TestingDF=inner_join(LIMSFullDFRoll,LIMSFullDF,by=c("Date","Site"))%>%
  rename(rollN1=N1.x,N1=N1.y,rollN1Error=N1Error.x,N1Error=N1Error.y)%>%
  select(Date,Site,rollN1,rollN1Error,N1,N1Error)%>%
  mutate(ZScore=(N1-rollN1)/rollN1Error*.8)%>%
  mutate(ExtremeScores=!(ZScore>-2&ZScore<2))
TestingDF%>%
  ggplot()+
  geom_point(aes(x=N1,y=ZScore))+
  scale_x_log10()


TestingDF%>%
  filter(Site=="Madison")%>%
  ggplot()+aes(x=Date-15,y=N1)+
  geom_point()+facet_wrap(~Site)+
  scale_y_log10()

TestingDF%>%
  filter(Site=="Madison")%>%
  filter(!ExtremeScores)%>%
  ggplot()+aes(x=Date,y=N1)+
  geom_point()+facet_wrap(~Site)+
  scale_y_log10()

# LatCaseDF%>%
#   filter(Site=="Madison")%>%
#   filter(!is.na(Cases))%>%
#   filter(!is.na(Date))%>%
#   ggplot()+aes(x=Date,y=Cases)+geom_point()+
#   scale_x_date(limits=Limits)+facet_wrap(~Site)+
#   scale_y_log10()
```

```{r LM Creation extended,fig.height = 10, fig.width = 14}
HFGVar=HFGFrame%>%
  select(Date,Site,N1,Pct_BCoV)%>%
  filter(N1<10e7)%>%
  group_by(Site,Date)%>%
  summarize(N1Error=var(N1),N1=mean(N1))

VarN1LIMSMadMode = LIMSFullDF%>%
  filter(Site=="Madison")%>%
  lm(formula=N1Error~N1-1)

VarN1HFDMode=lm(data=HFGVar,N1Error~N1-1)


VarN1LIMSMode=lm(N1Error~N1,weights=1/N1Error^2,data=LIMSFullDF)
VarN2LIMSMode=lm(N2Error~N2-1,data=LIMSFullDF)

VarN1N2LIMSMode=lm(N1Error~N1+N2-1,data=LIMSFullDF)
# VarN1HFGMode=lm(N1Error~N1-1,data=LIMSFullDF)
# VarN2HFGMode=lm(N2Error~N2-1,data=LIMSFullDF)

UsedModel=VarN1LIMSMode

CriticalPoint=2
LIMSWExpErrorDF=LIMSFullDF%>%
  filter(!is.na(N1))%>%
  mutate(PredN1Var=predict.lm(UsedModel,.))%>%
  mutate(PredN1Var=N1)%>%
  mutate(WeirdVar=ifelse(N1Error/PredN1Var>CriticalPoint,"Unexpected high Varience","Expected range of varience"))



#
```

```{r Model exploration}
LIMSWExpErrorDF%>%
  ggplot()+aes(x=N1)+geom_point(aes(y=N1Error))+
  geom_point(aes(y=PredN1Var),color="red")+
  scale_y_log10()+
  scale_x_log10()+ 
  Header_theme(ConfigOption)+
      theme(axis.text.x = element_text(size = ConfigOption$XAxisLabSiz, colour = "black"),
            axis.title.x = element_text(size = ConfigOption$GenFontSiz, colour = "black"),
            plot.margin = unit(c(.5,0,0,0), "cm"))



LIMSWExpErrorDF%>%
  ggplot()+aes(x=N1)+geom_point(aes(y=N1Error/PredN1Var))+
  geom_point(aes(y=PredN1Var/PredN1Var),color="red")+
  #geom_point(aes(y=PredN1Var/PredN1Var+1),color="red")+
  scale_y_log10()+
  scale_x_log10()+ 
  Header_theme(ConfigOption)+
      theme(axis.text.x = element_text(size = ConfigOption$XAxisLabSiz, colour = "black"),
            axis.title.x = element_text(size = ConfigOption$GenFontSiz, colour = "black"),
            plot.margin = unit(c(.5,0,0,0), "cm"))

LIMSWExpErrorDF%>%
  ggplot()+aes(x=N1)+geom_point(aes(y=PredN1Var-N1Error))+
  #geom_point(aes(y=PredN1Var/PredN1Var),color="red")+
  #scale_y_log10()+
  #scale_x_log10()+ 
  Header_theme(ConfigOption)+
      theme(axis.text.x = element_text(size = ConfigOption$XAxisLabSiz, colour = "black"),
            axis.title.x = element_text(size = ConfigOption$GenFontSiz, colour = "black"),
            plot.margin = unit(c(.5,0,0,0), "cm"))+ylab("residuals")+ggtitle("Predicting varience Residuals")


```


```{r LM boxplot exploration,fig.height = 10, fig.width = 14}
BoxWidth=1
MadBoxData=LIMSWExpErrorDF%>%
  filter(Site =="Madison")%>%
  #filter(WeirdVar=="Unexpected high Varience")%>%
  mutate(ErrorMin=N1-2*N1Error,ErrorMax=N1+2*N1Error)%>%
  mutate(ErrorMin=ifelse(ErrorMin>0,ErrorMin,0))
MadBoxNoWeirdData=MadBoxData%>%
  filter(WeirdVar=="Expected range of varience")

Limits=c(min(MadBoxData$Date,na.rm = TRUE),max(MadBoxData$Date,na.rm = TRUE))

MadBoxPlot=MadBoxData%>%
  ggplot()+#geom_point(aes(x=Date,y=N1))+
  geom_rect(aes(ymin=ErrorMin,ymax=ErrorMax,xmin=Date-BoxWidth,xmax=Date+BoxWidth,fill=WeirdVar),color="Black",alpha=.5)+
  geom_rect(aes(ymin=N1,ymax=N1,xmin=Date-BoxWidth,xmax=Date+BoxWidth),color="black",alpha=.5)+
  geom_smooth(aes(x=Date,y=N1),span=.33,se=FALSE,data=MadBoxNoWeirdData)+
   Header_theme(ConfigOption)


a=MadBoxPlot+
  scale_y_log10(limits=c(1e3,5e6))+
  ggtitle("Madison citys with 2 SE bounds")+
  facet_wrap(~Site,scales = "free_y")
  #scale_x_date(limits=c(N1Start,N1End))+
  


b=MadBoxPlot+
      theme(axis.text.x = element_text(size = ConfigOption$XAxisLabSiz, colour = "black"),
            axis.title.x = element_text(size = ConfigOption$GenFontSiz, colour = "black"),
            plot.margin = unit(c(.5,0,0,0), "cm"))


aalook=ggarrange(a,b,nrow=2,common.legend = TRUE,align="hv")
aa=ggarrange(a,b,nrow=2,common.legend = TRUE,align="hv",legend = "none")

CasePlots=LatCaseDF%>%
  filter(Site=="Madison")%>%
  ggplot()+aes(x=Date,y=Cases)+geom_point()+
  scale_x_date(limits=Limits)

a=CasePlots+
  scale_y_log10()+
  facet_wrap(~Site,scales = "free_y")+
  Header_theme(ConfigOption)+
  ggtitle("Madison Case Data")
b=CasePlots+
  Header_theme(ConfigOption)+
      theme(axis.text.x = element_text(size = ConfigOption$XAxisLabSiz, colour = "black"),
            axis.title.x = element_text(size = ConfigOption$GenFontSiz, colour = "black"),
            plot.margin = unit(c(.5,0,0,0), "cm"))

ab=ggarrange(a,b,nrow=2,align="hv")

ggarrange(aa,ab,nrow=1,align="hv")
```


```{r shiny controlled thresholding}

SiteOptions2=c("Kenosha","Madison", "Sun Prairie","Wausau")

ui <- fluidPage(
  titlePanel("Varience Thresholding"),
  sidebarLayout(
    sidebarPanel(width=2,
      sliderInput(inputId = "Thresh",
                  label = "Threshold ratnio",
                  min = 1,
                  max = 7.5,
                  value = 2),
      selectInput(inputId = "Site",
                  label = "Site",
                  choices=SiteOptions2)
    ),
    mainPanel(
      tabsetPanel(type = "tabs",
       tabPanel("PredictedPlot", plotOutput(outputId = "dotPlot",height = "800px")),
       tabPanel("BoxPlot", plotOutput(outputId = "BoxPlot",height = "800px")),
       tabPanel("Multiboxes", plotOutput(outputId = "Multiboxes",height = "800"))
       )
    )
  )
)
server <- function(input, output) {

  UsedDF = reactive({
    LIMSFullDF%>%
      filter(!is.na(N1))%>%
      mutate(PredN1Var=predict(UsedModel,.))%>%
      mutate(WeirdVar=ifelse(N1Error/PredN1Var>input$Thresh,"Unexpected high Varience","Expected range of varience"))
  })
  
  output$Multiboxes <- renderPlot({
    CompBoxPlot=UsedDF()%>%
      filter(Site =="Madison")%>%
      mutate(ErrorMin=N1-2*PredN1Var,ErrorMax=N1+2*PredN1Var)%>%
      mutate(ErrorMin=ifelse(ErrorMin>0,ErrorMin,0))%>%
      ggplot()+#geom_point(aes(x=Date,y=N1))+
      geom_rect(aes(ymin=ErrorMin,ymax=ErrorMax,xmin=Date,xmax=Date+BoxWidth,fill="Predicted"),color="Black",alpha=.5)+
      geom_rect(aes(ymin=N1-2*N1Error,ymax=N1+2*N1Error,xmin=Date-BoxWidth,xmax=Date,fill="Real Var"),color="black",alpha=.5)+
      geom_rect(aes(ymin=N1,ymax=N1,xmin=Date-BoxWidth,xmax=Date+BoxWidth),color="black",alpha=.5)
    a=CompBoxPlot+
      scale_y_log10()+ggtitle("Pred vs actual boxplots")
      #scale_x_date(limits=c(N1Start,N1End))+
    b=CompBoxPlot
    return(ggarrange(a,b,nrow=2,common.legend = TRUE,align="hv"))
  })
  
  
  output$dotPlot <- renderPlot({
    UsedDF()%>%
    #filter(Site =="Madison")%>%
  ggplot()+aes(x=N1)+geom_point(aes(y=N1Error/PredN1Var,color=WeirdVar))+#geom_point(aes(y=PredN1Var),color="red")+
  geom_hline(yintercept = 1,color="dark green")+
  geom_hline(yintercept = input$Thresh,color="dark green")+
  #scale_y_log10()+
  scale_x_log10()+ 
  Header_theme(ConfigOption)+
      theme(axis.text.x = element_text(size = ConfigOption$XAxisLabSiz, colour = "black"),
            axis.title.x = element_text(size = ConfigOption$GenFontSiz, colour = "black"),
            plot.margin = unit(c(.5,0,0,0), "cm"))
  })
  
  #filter(WeirdVar=="Unexpected high Varience")%>%
  output$BoxPlot <- renderPlot({
    BoxWidth=1
    FilteredMadBoxPlot=UsedDF()%>%
      filter(Site =="Madison")%>%
      filter(WeirdVar!="Unexpected high Varience")
      
    MadBoxPlot=UsedDF()%>%
      filter(Site =="Madison")%>%
      mutate(ErrorMin=N1-2*N1Error,ErrorMax=N1+2*N1Error)%>%
      mutate(ErrorMin=ifelse(ErrorMin>0,ErrorMin,0))%>%
      ggplot()+#geom_point(aes(x=Date,y=N1))+
      geom_rect(aes(ymin=ErrorMin,ymax=ErrorMax,xmin=Date-BoxWidth,xmax=Date+BoxWidth,fill=WeirdVar),color="Black",alpha=.5)+
      geom_rect(aes(ymin=N1,ymax=N1,xmin=Date-BoxWidth,xmax=Date+BoxWidth),color="black",alpha=.5)+
      geom_smooth(aes(x=Date,y=N1),span=.33,se=TRUE,data=FilteredMadBoxPlot)+
      Header_theme(ConfigOption)
    a=MadBoxPlot+
      scale_y_log10(limits=c(1e3,5e6))+
      facet_wrap(~Site,scales = "free_y")+
      ggtitle("N1 curve filtered from weird values")
      #scale_x_date(limits=c(N1Start,N1End))+
    b=MadBoxPlot+
        theme(axis.text.x = element_text(size = ConfigOption$XAxisLabSiz, colour = "black"),
            axis.title.x = element_text(size = ConfigOption$GenFontSiz, colour = "black"),
            plot.margin = unit(c(.5,0,0,0), "cm"))
    
    N1Graphics=ggarrange(a,b,nrow=2,common.legend = TRUE,align="hv")
    
    CasePlots=LatCaseDF%>%
      filter(Site=="Madison")%>%
      ggplot()+aes(x=Date,y=Cases)+geom_point()+
      scale_x_date(limits=Limits)
      
    a=CasePlots+
      scale_y_log10()+
      facet_wrap(~Site,scales = "free_y")+
      Header_theme(ConfigOption)+
      ggtitle("Madison Case Data")
    b=CasePlots+
      Header_theme(ConfigOption)+
      theme(axis.text.x = element_text(size = ConfigOption$XAxisLabSiz, colour = "black"),
        axis.title.x = element_text(size = ConfigOption$GenFontSiz, colour = "black"),
        plot.margin = unit(c(.5,0,0,0), "cm"))
    
    CasesGraphics=ggarrange(a,b,nrow=2,align="hv")

    FinalGraphic=ggarrange(N1Graphics,CasesGraphics,nrow=1,align="hv")
    return(FinalGraphic)

  
    })
}
shinyApp(ui, server)
```


```{r PMMoV Tresh,fig.height = 15, fig.width = 15}
PMMoVUseDF=LIMSFullDF%>%
  filter(Site %in%LargePopAreas)%>%
  mutate(`PMMoV Level`=ifelse(PMMoV<5*10^6,"Low","Medium"))%>%
  mutate(`PMMoV Level`=ifelse(PMMoV>2*10^7,"High",`PMMoV Level`))%>%
  mutate(`PMMoV Level`=factor(`PMMoV Level`,levels=c("High","Medium","Low")))

PMMoVUseDF%>%
  ggplot()+aes(x=PMMoV,y=N1,color=`PMMoV Level`)+geom_point()+scale_y_log10()+
  scale_x_log10()+
  facet_wrap(~Site)+
  ggtitle("N1 Vs PMMoV")+
  xlab("PMMoV (GC/L)")+ylab("N1 (GC/L)")+ 
  Header_theme(ConfigOption)+
      theme(axis.text.x = element_text(size = ConfigOption$XAxisLabSiz, colour = "black"),
            axis.title.x = element_text(size = ConfigOption$GenFontSiz, colour = "black"),
            plot.margin = unit(c(.5,0,0,0), "cm"))

PMMoVUseDF%>%
  ggplot()+aes(x=Date,y=N1,color=`PMMoV Level`)+
  geom_point()+
  ylab("N1 (GC/L)")+ggtitle("PMMoV and N1 appear unrelated")+
  scale_y_log10()+facet_wrap(~Site)+ 
  Header_theme(ConfigOption)+
      theme(axis.text.x = element_text(size = ConfigOption$XAxisLabSiz, colour = "black"),
            axis.title.x = element_text(size = ConfigOption$GenFontSiz, colour = "black"),
            plot.margin = unit(c(.5,0,0,0), "cm"))
```

```{r BCoV Tresh,fig.height = 15, fig.width = 15}
BCoVUseDF=LIMSFullDF%>%
  filter(Site %in%LargePopAreas)%>%
  mutate(`Percent BCoV Recovery`=ifelse(BCoV<1,"Low","Medium"))%>%
  mutate(`Percent BCoV Recovery`=ifelse(BCoV>10,"High",`Percent BCoV Recovery`))%>%
  mutate(`Percent BCoV Recovery`=factor(`Percent BCoV Recovery`,levels=c("High","Medium","Low")))%>%
  filter(BCoV>0)

BCoVUseDF%>%
  ggplot()+aes(x=BCoV,y=N1,color=`Percent BCoV Recovery`)+geom_point()+
  xlab("Percent Bcov Recovery")+
  ylab("N1 (GC/L)")+
  #scale_y_log10()+
  #scale_x_log10()+
  facet_wrap(~Site)+
  ggtitle("N1 Vs %Bcov recovery")+ Header_theme(ConfigOption)+
      theme(axis.text.x = element_text(size = ConfigOption$XAxisLabSiz, colour = "black"),
            axis.title.x = element_text(size = ConfigOption$GenFontSiz, colour = "black"),
            plot.margin = unit(c(.5,0,0,0), "cm"))
#, scales = "free"
#scale_x_log10()+,color=marked

BCoVUseDF%>%
  ggplot()+aes(x=Date,y=N1,color=`Percent BCoV Recovery`)+geom_point()+
  ggtitle("Percent BCoV recovery and N1 appear unrelated")+
  scale_y_log10()+facet_wrap(~Site)+ Header_theme(ConfigOption)+
      theme(axis.text.x = element_text(size = ConfigOption$XAxisLabSiz, colour = "black"),
            axis.title.x = element_text(size = ConfigOption$GenFontSiz, colour = "black"),
            plot.margin = unit(c(.5,0,0,0), "cm"))
```

```{r HFG Data, fig.height = 6, fig.width = 18}
# library(plotly)
# GPlot=LIMSFullDF%>%
#   ggplot()+geom_point(aes(x=Date,y=N1))+facet_wrap(~Site)
# ggplotly(GPlot)
MaskedDataRange="1-4 Cases"
RelData=HFGCaseDF%>%
  filter(Site %in% LargePopAreas)%>%
    mutate(PHI_masking=ifelse(CollectedCases==-999,MaskedDataRange,"Reported values"))%>%
    filter(!is.na(PHI_masking))%>%
    mutate(CollectedCases=ifelse(CollectedCases==-999,2.5,CollectedCases))
RelRollData=HFGCaseDFRoll%>%
  filter(Site %in% LargePopAreas)

Date_lim_HFG=c(min(RelData$Date)-2,max(RelData$Date)+2)

LIMSHFDF=LIMSFullDF%>%
  filter(Site %in%LargePopAreas)

LIMSHFDFRoll=RollAvg(LIMSHFDF)

LIMSRange=c(min(LIMSFullDF$Date)-1,max(LIMSFullDF$Date)+1)

HFDCasesGraphic=Buildplot_gen("CollectedCases",
  MainDF=RelData,
  ColorType="PHI_masking",
  Loc="Site",
  LineDF=RelRollData,
  WeekDF=HFGDateRangeDF,
  DateLimits=LIMSRange,
  Standards=ConfigOption,
  Xfreq="30 days",
  AxisPos="bottom",
  LineColor="red",
  norm="Population",
  Colplot=T,
  Start=N1Start,
  End=N1End,
  nrow=2,
  Bind=F)+ Header_theme(ConfigOption)+
      theme(axis.text.x = element_text(size = ConfigOption$XAxisLabSiz, colour = "black"),
            axis.title.x = element_text(size = ConfigOption$GenFontSiz, colour = "black"),
            plot.margin = unit(c(.5,0,0,0), "cm"))

#ordered factor
#arrow point to lines
#label span of hf collection
#arrow at bottom
#add text box to explain lines
YMax=max(RelData$CollectedCases/RelData$Population)
  

HFDCasesGraphic+ annotate("text", x = N1Start+11.5, y = YMax, label = "Range of HF collection")




HFDLIMSGraphic=Buildplot_gen(
  "N1",
  MainDF=LIMSHFDF,
  Loc="Site",
  spanN=.3,
  YLabel = "N1 (GC/L)",
  log_scale=T,
  DateLimits=LIMSRange,
  #RMOutliers=T,
  AxisPos="bottom",
  Standards=ConfigOption,
  Start=Date_lim_HFG[1],
  End=Date_lim_HFG[2],
  Xfreq="30 days",
  nrow=2)+ Header_theme(ConfigOption)+
      theme(axis.text.x = element_text(size = ConfigOption$XAxisLabSiz, colour = "black"),
            axis.title.x = element_text(size = ConfigOption$GenFontSiz, colour = "black"),
            plot.margin = unit(c(.5,0,0,0), "cm"))

YMax=max(LIMSHFDF$N1)
  


HFDLIMSGraphic+ annotate("text", x = N1Start+18, y = YMax, label = "Range of HF Case Data")


```



```{r HFG Boxplot,include=FALSE}
# HFGMean=HFGFrame%>%
#   filter(Site %in%LargePopAreas)%>%
#   filter(N1<1e8)%>%
#   group_by(Site,Date)%>%
#   summarize(SD=sqrt(var(N1)),N1=mean(N1))
# HFGFrame=HFGFrame%>%
#   filter(N1<1e8)%>%
#   filter(Site %in%LargePopAreas)
# ggplot()+aes(x=Date)+
# scale_y_log10(limits=c(1e3,5e6))+
# scale_x_date(limits=c(N1Start,N1End))+
# geom_rect(aes(ymin=N1-2*SD,ymax=N1+2*SD,xmin=Date-.5,xmax=Date+.5),fill="light blue",color="Black",alpha=.5,data=HFGMean)+
# geom_point(aes(y=N1,color=`Filter replicates`),data=HFGFrame)+
#   facet_wrap(~Site,scales = "free_y")+
#   Header_theme(ConfigOption)+
#       theme(axis.text.x = element_text(size = ConfigOption$XAxisLabSiz, colour = "black"),
#             axis.title.x = element_text(size = ConfigOption$GenFontSiz, colour = "black"),
#             plot.margin = unit(c(.5,0,0,0), "cm"))
```

