---
title: "ShinyGamaDist"
author: "Marlin"
date: "8/10/2021"
output: html_document
---
```{r setup, include=FALSE}
#library(MASS)
library(shiny)
library(ggpubr)
library(limma)
library(dplyr)
library(lmtest)
library(plotly)

#Data Files and prep work
source("../../Scripts/GenPlotMaking.R")
source("../../Scripts/WasteWaterDataProccess.R")
source("../../Scripts/CasesDataProccess.R")
source("../../Scripts/HelperFunctions.R")
```


```{r}
PathStarter="Z:/"

LatMMSDFN  <-  paste0(PathStarter,"COVID-19_WastewaterAnalysis/data/raw/MMSD_Cases.csv")
LatSpringDormFN  <-  paste0(PathStarter,"COVID-19_WastewaterAnalysis/data/raw/SpringSemester_CasesByDorm.TSV")
LatFallDormFN  <-  paste0(PathStarter,"COVID-19_WastewaterAnalysis/data/raw/FallSemester_CasesByDorm.TSV")

LIMSFN <- paste0(PathStarter,"COVID-19_WastewaterAnalysis/data/raw/WATERMICRO_WW_COVID-2021-06-30 17 40.xlsx")

HFGCasesFN  <-  paste0(PathStarter,"COVID-19_WastewaterAnalysis/data/raw/HighFreq_CaseData_2021-05-07.csv")


LatCaseDF <- CovidDataPARSER(LatSpringDormFN,LatFallDormFN,MMSDFN = LatMMSDFN)%>%
  filter(!is.na(Site))%>%
  select(Date,Site,Cases,Tests,Per_pos)

HFGCaseDF <- HFGCasesPARSER(FN = HFGCasesFN)%>%
  filter(!is.na(Site))%>%
  mutate(Tests=NA,Per_pos=NA)%>%
  select(Date,Site,Cases=ReportedCases,Tests,Per_pos)%>%
  mutate(Cases = ifelse(Cases==-999,2.5,Cases))%>%
  filter(Site!="Madison")

FullCase <- rbind(HFGCaseDF,LatCaseDF)

LIMSFullDF <- LIMSDataPARSER(LIMSFN)%>%
  select(Date,Site, BCoV, N1,N1Error,N2, N2Error,PMMoV,Pop,FlowRate)

```




```{r UI shiny app}
SiteOptions2=c("Madison","Spring UW-Sellery",
                            "Fall UW-Sellery", "Spring UW-LakeShore",
                            "Fall UW-LakeShore")

HighSpan <- .1
MinWeight <- 0
PointSize=1
#"Madison","M Intercepters","hFD Sites"
ui <- fluidPage(
  titlePanel("Gamma Distribution"),
  sidebarLayout(
    sidebarPanel(width=2,
      selectInput(inputId = "Site",
                  label = "Site",
                  choices=SiteOptions2,
                  selected = "Madison"),
      sliderInput(inputId = "scale",
                  label = "scale",
                  min = 1,
                  max = 15,
                  step =.1,
                  value = 5.028338),
      sliderInput(inputId = "shape",
                  label = "shape",
                  min = 1,
                  max = 5,
                  step =.1,
                  value = 2.332779),
      checkboxInput(inputId = "Roll",
                    label="Convolve with 7day Avg", 
                    value=T),
      sliderInput(inputId = "delay",
                  label = "Quarantine length",
                  min = 0,
                  max = 20,
                  step =1,
                  value = 0),
      sliderInput(inputId = "Span",
                  label = "loess span",
                  min = 0,
                  max = .5,
                  step =.01,
                  value = .125)#,
      # checkboxInput(inputId = "Log",
      #               label="log(N1)", 
      #               value=T)
    ),
    mainPanel(
      tabsetPanel(type = "tabs",
       tabPanel("SLDPlot", plotOutput(outputId = "SLDPlot")),
       tabPanel("GammaDist", plotOutput(outputId = "GammaDist")),
       tabPanel("DifSLDPlot", plotOutput(outputId = "DifSLDPlot")))
    )
  )
)

```

```{r Server Shiny app}
DataPrepS <- DormGraphics <- function(Site,shape,scale,delay,Span){
  FullLimsDF <- DataPrep(LIMSFullDF,keep=c("N1","N1Error"),Site)
  FullCase2 <- FullCase%>%
    mutate(Cases=ifelse(Cases<0,2.5,Cases))
  SCPDF <- DFSmoothingFNC(FullCase2,SiteS=Site,
                                Weights=c(rep(0,delay),
                                dgamma(1:21,
                                scale=scale,
                                shape=shape)[(delay+1):21]))
  
  SCPDF2 <- DFSmoothingFNC(FullCase2,PreRoll=TRUE,SiteS=Site,
                                Weights=c(rep(0,delay),
                                dgamma(1:21,
                                scale=scale,
                                shape=shape)[(delay+1):21]))%>%
    mutate(Site=Site)
  
  SCPDF3 <- inner_join(SCPDF,SCPDF2,by=c("Date","Site","Cases"),suffix=c("",".PreRolled"))
  MergedDF <- inner_join(SCPDF3,FullLimsDF, by=c("Date","Site"))
  
  
  MergedDF$LoessN1 <- DFLoessFNC(MergedDF,SiteS=Site,span=Span)
  
  MergedDF <- MergedDF%>%
    select(Date,Site,Cases,Cases2,Cases2.PreRolled,N1,LoessN1,N1Error)%>%
    filter(!is.na(Cases)&!is.na(Cases2.PreRolled),!is.na(N1),!is.na(LoessN1))
  
  TSDF <- ts(MergedDF,start = 18520)
  SLDPreRolledVec <- TSDF[,5]
  SLDCaseVec <- TSDF[,4]
  CaseVec <- TSDF[,3]
  loessN1Vec <- TSDF[,7]
  logN1Vec <- log(TSDF[,6])
  return(MergedDF)
}
#mean = 11.73 days and an sd = 7.68 days

server <- function(input, output) {

  UsedDF <- reactive({
    DataPrepS(input$Site,input$shape,input$scale,input$delay,input$Span)
  })
  
  TSDF <- reactive({
    ts(UsedDF(),start = 18520)
  })
  
  SLDVec <- reactive({
    if(input$Roll){
      return(TSDF()[,5])
    }else{
      return(TSDF()[,4])
    }
  })
  
  output$SLDPlot <- renderPlot({
    #if(input$Log){
      N1logz <- "y"
    # }else{
    #   N1logz <- ""
    # }
    # 
    
    TSPloting2(list(SLDVec(),exp(TSDF()[,7]),TSDF()[,3]),UsedDF(),
                SubTitle=input$Site,SLD=TRUE,input$Span)
  })
  
  output$GammaDist <- renderPlot({

    plot(c(rep(0,input$delay),
                                dgamma(1:21,
                                scale=input$scale,
                                shape=input$shape)[(input$delay+1):21]), 
            main=paste("Gamma Distribution with mean =", round(input$scale*input$shape,3),"days and SD =", round(input$scale*sqrt(input$shape),3)),
            ylab = "Weight",
            xlab = "Lag")
  })
  
  output$DifSLDPlot <- renderPlot({
    TSPloting(list(SLDVec(),exp(TSDF()[,7])),UsedDF(),
                "DepName","IndName",FullPlot=FALSE,SubTitle=NA,FirstDif=TRUE)
  })
}
shinyApp(ui, server)
```
