---
title: "SE Exploration"
output: html_notebook
---
```{r Prep}
library(ggpubr)
library(dplyr)


#Data Files and prep work
source("../../Scripts/GenPlotMaking.R")
source("../../Scripts/WasteWaterDataProccess.R")
source("../../Scripts/CassesDataProccess.R")
source("../../Scripts/HelperFunctions.R")


source("../../Scripts/WasteShiny/PrepData.R", local = TRUE)

```

```{r Needed Functions}
CasePlotMaking = function(SiteS,Method="Cases"){
  SiteCases=LatCaseDF%>%
    filter(Site==SiteS)

  SiteCasesRoll=LatCaseDFRoll%>%
    filter(Site==SiteS)
  
  LIMSSiteDF=LIMSFullDF%>%
   filter(Site==SiteS)


  Date_lim_long=c(min(LIMSSiteDF$Date),max(LIMSSiteDF$Date))
  
  CasePlot <- Buildplot_gen(
      Method,
      MainDF=SiteCases,
      Loc="Site",
      LineDF=SiteCasesRoll,
      Xfreq="30 days",
      DateLimits=Date_lim_long,
      Standards=ConfigOption,
      AxisPos="bottom",
      LineColor="red",
      Colplot=TRUE) #+ theme(ConfigOption)
  return(CasePlot)
}

```


```{r SE reverse}
#instead of grabbing arithmetic mean grab geo mean it could work
# geom mean for 3 n1 is close to arithmetic mean of 3 n1
# closeness of geo mean and arithmetic mean when SE is small
#look into converting arithmetic mean

#sample mean n1 and SE get 3 points and get geo mean
#boot strap to see distribution


#https://math.stackexchange.com/questions/2971315/how-do-i-combine-standard-deviations-of-two-groups
#Correctly Merges two variance into a variance of the two samples
CombinedVar <- function(Mean1,Mean2,Var1,Var2,n1=3,n2=3){
  #New Mean
  meanTot <- (n1*Mean1+n2*Mean2)/(n1+n2)
  #Simple new variance if they had same mean
  WeightedVar <- ((n1-1)*Var1 + (n2-1)*Var2)/(n1+n2-1)
  #extra variance from having different means
  MeanShift <- ((n1*n2)*(Mean1-Mean2)^2)/((n1+n2)*(n1+n2-1))
  return(WeightedVar+MeanShift)
}
#Wraps first variance to be useful feeding in information in LIMS DF
CombinedSE <- function(Mean1,Mean2,SE1,SE2,n1=3,n2=3){
  Var1 <- SE1^2*n1
  Var2 <- SE2^2*n2
  ComVar <- CombinedVar(Mean1,Mean2,Var1,Var2,n1=n1,n2=n2)
  return(sqrt(ComVar/(n1+n2)))
}

LIMSAVGSEDF <- LIMSNoNullDF%>%
  mutate(AVGSE=CombinedSE(N1,N2,N1Error,N2Error))

#Create sample data that represents data with given mean and SE
DataGen3Points <- function(Mean,SE){
  n=3
  A=rnorm(n=1,mean=Mean,sd=SE*sqrt(n))
  B=rnorm(n=1,mean=Mean,sd=SE*sqrt(n))
  C=Mean*3-A-B
  tempSE=sd(c(A,B,C))/sqrt(n)
  A <- Mean+(A-Mean)/tempSE
  B <- Mean+(B-Mean)/tempSE
  C <- Mean+(C-Mean)/tempSE
  return(c(A,B,C))
}

```


```{r N1 vs N2 overview, warning=FALSE,message =FALSE}
#having N1 be a rep to N2 is good

LIMSNoNullDF <- LIMSFullDF%>%
  #filter(Date>mdy("1/1/2021"))%>%
  filter(!is.na(N1),!is.na(N2))

MadLIMS <- LIMSNoNullDF%>%
  filter(Site=="Madison")%>%
  filter(N1>0)%>%
  filter(N2>0)%>%
  filter(!is.na(N1),!is.na(N2))%>%
  mutate(Date=as.numeric(Date))

N1Mod <- loess(log(N1)~Date,span=.2,data=MadLIMS)
N2Mod <- loess(log(N2)~Date,span=.2,data=MadLIMS)
AVGMod <- loess(log(AVG)~Date,span=.2,data=MadLIMS)

MadLIMS$ResidN1 <- resid(N1Mod)
  
MadLIMS$ResidN2 <- resid(N2Mod)

MadLIMS$ResidAVG <- resid(AVGMod)

MadLIMS <- MadLIMS%>%
  mutate(Date=as.Date(Date,origin="1970-01-01"))

MadLIMS%>%
  ggplot()+
  aes(x=Date)+
  #geom_point(aes(y=log(N1),color="N1"))+
  geom_line(aes(y=log(N1)-ResidN1,color="N1"))+
  #geom_point(aes(y=log(N2),color="N2"))+
  geom_line(aes(y=log(N2)-ResidN2,color="N2"))+
  #geom_point(aes(y=log(AVG),color="AVG"))+
  #geom_line(aes(y=log(AVG)-ResidAVG,color="AVG"))+
  facet_wrap(~Site)+
  ylab("Smoothed log concentration")+
  theme(legend.position="bottom")
  
CasePlotMaking("Madison")+
    theme(axis.text.x = element_text(angle=0, hjust = 0,size=10))+                          scale_x_date(date_labels = "%b")+
    theme_grey()


CasePlotMaking("Madison",Method="Per_pos")+
    theme(axis.text.x = element_text(angle=0, hjust = 0,size=10))+                          scale_x_date(date_labels = "%b")+
    theme_grey()

#relationship between N1-N2 should be constant
#is smoothing good? dec jan- suspect - error in N1N2 assay are throwing off

#N1 and N2 are linked - both RNA - within cell N1 N2 are equal in number
#look at N1 N2 ratio when filtering older dates
```

```{r Messuring same thing?}

#not IID: how important for test: correcting for this-
#TS T test?

t.test(log(LIMSNoNullDF$N1),log(LIMSNoNullDF$N2)  ,paired=TRUE)
#+ 0.2730466

LIMSNoNullDF%>%
  ggplot()+
  geom_density(aes(x=log(N1),fill="N1"))+
  geom_density(aes(x=log(N2)+ 0.2730466,fill="N2"),alpha=.5)
#+.2
#/1.1+1.2
#Different distribution imply measuring different things
#todo: gen number and smooth plot
var(log(LIMSNoNullDF$N2))
var(log(LIMSNoNullDF$N1))
mean(log(LIMSNoNullDF$N2))
mean(log(LIMSNoNullDF$N1))

#Don't need to solve N1 N2 problem
#Present smoothing
```


```{r N1 Vs N2}

t.test(log(MadLIMS$ResidN1),log(MadLIMS$ResidN2),paired=TRUE)

MadLIMS%>%
  ggplot(aes(x=Date))+
  geom_point(aes(y=abs(ResidN1),color="N1"))+
  geom_point(aes(y=abs(ResidN2),color="N2"))+
  ggtitle("Residual plot")
MadLIMS%>%
  ggplot(aes(x=Date))+
  geom_point(aes(y=abs(ResidN1)-abs(ResidN2)))+
  ggtitle("Dif of residuals")

# MadLIMS%>%
#   ggplot()+
#   aes(x=Date)+
#   geom_point(aes(y=N1-N2))
# MadLIMS%>%
#   ggplot()+
#   aes(x=Date)+
#   geom_point(aes(y=log(N1)-log(N2)))


#Measuring different signals
#Similar errors
#Data before jan is messy-after more clear
#N1 vs N2 is easier after jan
#HFD  using old data
#defer to get the rest of clean data - look at data after jan otherwise
#plots show that data before jan are to messy to analysis
#
#error happens at sampling process
#
#Sickness, Cases, N1
#Sickness -> N1
#Sickness -> tightness ->Cases

#Cases ->smooth -> N1   :Easier to interpret - inferred infected number of people
#N1 -> tightness -> Cases   :harder to mathout - gives same relationship - if I got N1 for last 7 weeks remove old cases concentrations- if was higher recently: expect to grow- use in loess - better smoothing - gen of loess 

#4 pm 
#get rough idea of where I am going
```






```{r N1 N2 Relation}


LIMSNoNullDF%>%
  select(N1,N1Error,N2,N2Error)%>%
  filter(N1Error>=0)%>%
  mutate(AVGError=CombinedSE(N1,N2,N1Error,N2Error))%>%
  ggplot()+
  geom_point(aes(x=N1,y=N2/N1,color=log(AVGError)),cex=.1)+
  #scale_y_log10()+
  scale_x_log10()

LIMSNoNullDF%>%
  ggplot()+
  aes(x=N2/N1)+
  geom_histogram()+
  scale_x_log10()

LIMSNoNullDF%>%
  summarize(MeanRatio=mean(N2/N1,na.rm=TRUE),meadianRatio=median(N2/N1,na.rm=TRUE))


LIMSNoNullDF%>%
  mutate(Ratio=N2/N1)%>%
  filter(Ratio<2)%>%
  ggplot()+
  geom_point(aes(x=N1,y=Ratio),cex=.1)+
  #scale_y_log10()+
  scale_x_log10()
2924/3483
#NH: N1 and N2 draw from same sample
#Alt Hypothesis: They draw from different samples


LIMSNoNullDF%>%
  ggplot()+
  aes(x=log(N1)-log(N2))+
  geom_histogram()+
  scale_x_log10()


LIMSNoNullDF%>%
  filter(!is.na(N1),!is.na(N2))%>%
  mutate(Ratio=N2/N1)%>%
  summarise(meanRat=mean(Ratio),ratMean=mean(N2)/mean(N1))

LIMSNoNullDF%>%
  ggplot()+
  aes(x=N1,y=N2)+
  geom_point()+
  geom_smooth(method="lm")+
  scale_y_log10()+
  scale_x_log10()



N1N2LM=lm(log(N2)~log(N1),data=LIMSNoNullDF)
LIMSNoNullDF%>%
  mutate(Resid=resid(N1N2LM))%>%
  ggplot()+
  aes(x=log(N2),y=Resid)+
  geom_point()

LIMSNoNullDF%>%
  mutate(Resid=resid(N1N2LM))%>%
  ggplot()+
  aes(x=log(N1),y=Resid)+
  geom_point()

summary(N1N2LM)


LIMSNoNullDF%>%
  select(N1,N2,N1Error)%>%
  mutate(WithinError=abs(N1-N2)<2*N1Error*sqrt(3))%>%
  summarise(mean(WithinError))

LIMSNoNullDF%>%
  select(N1,N2,N2Error)%>%
  mutate(WithinError=abs(N1-N2)<2*N2Error*sqrt(3))%>%
  summarise(mean(WithinError))


#Paired T test

#both samples need to be normal

LIMSNoNullDF%>%
  ggplot()+
  aes(x=log(N1))+
  geom_histogram()

LIMSNoNullDF%>%
  ggplot()+
  aes(x=log(N2))+
  geom_histogram()






```