---
title: "TSAnalysis"
author: "Marlin"
date: "7/9/2021"
output: html_document
---

```{r Start enviroment, message=FALSE, warning=FALSE}
library(ggpubr)
library(dplyr)
library(forecast)
library(lmtest)
library(lubridate)

#Data Files and prep work
source("../../Scripts/GenPlotMaking.R")
source("../../Scripts/WasteWaterDataProccess.R")
source("../../Scripts/CassesDataProccess.R")
source("../../Scripts/HelperFunctions.R")


source("../../Scripts/WasteShiny/PrepData.R", local = TRUE)
A<-LIMSFullDF%>%
  filter(Site=="Madison")
B<-LatCaseDF%>%
  filter(Site=="Madison")
grangertest(A$N1,B$Cases)
#looking for analysis and a number of relationship rigorously with TS
#Get some measure of how good the relationship
#auto.arima()

#three diffrent date options
```

```{r weekend effect proof}
WeekdayDF <- LIMSFullDF%>%
  mutate(weekday=weekdays(Date))%>%
  filter(N1>0,N1Error>0)
WeekdayDF$weekday <- factor(WeekdayDF$weekday,
                        levels= c("Monday", "Tuesday", "Wednesday", "Thursday","Friday","Saturday","Sunday"))

WeekdayDF%>%
  group_by(weekday)%>%
  summarize(N1M=mean(N1),n())
# t.test(filter(WeekdayDF,weekday=="Tuesday")$N1,filter(WeekdayDF,weekday=="Saturday")$N1)

summary(aov(N1~weekday+Site,data=WeekdayDF))
#24/34/45/47/67

WeekdaySmoothedDF <- RollAvg(LIMSFullDF,var=c("N1","N1Error","PMMoV"))%>%
  mutate(weekday=weekdays(Date))%>%
  filter(N1>0,N1Error>0)

WeekdaySmoothedDF$weekday <- factor(WeekdaySmoothedDF$weekday,
                        levels= c("Monday", "Tuesday", "Wednesday", "Thursday","Friday","Saturday","Sunday"))

summary(aov(N1~weekday+Site,data=WeekdaySmoothedDF))

```

```{r smoothed analyis}
WeekdayCaseDF <- LatCaseDF%>%
  mutate(weekday=weekdays(Date))%>%
  filter(Cases>0,Per_pos>0)
WeekdayDF$weekday <- factor(WeekdayDF$weekday,
                        levels= c("Monday", "Tuesday", "Wednesday", "Thursday","Friday","Saturday","Sunday"))

WeekdayCaseDF%>%
  group_by(weekday)%>%
  summarize(CasesM=mean(Cases),Per_posM=mean(Per_pos),n())
#t.test(filter(WeekdayDF,weekday=="Monday")$N1,filter(WeekdayDF,weekday=="Thursday")$N1)

summary(aov(Per_pos~weekday+Site,data=WeekdayCaseDF))
#24/34/45/47/67

WeekdaySmoothedCaseDF <- RollPerPos(LatCaseDF,"Cases","Tests",Facet="Site")%>%
  mutate(weekday=weekdays(Date))%>%
  filter(Cases>0,Per_pos>0)

WeekdaySmoothedCaseDF$weekday <- factor(WeekdaySmoothedCaseDF$weekday,
                        levels= c("Monday", "Tuesday", "Wednesday", "Thursday","Friday","Saturday","Sunday"))

summary(aov(Per_pos~weekday+Site,data=WeekdaySmoothedCaseDF))

```



```{r Start}
library(lmtest)
library(astsa)
# LIMSMadDF=LIMSFullDF%>%
#   filter(Site=="Madison")
# grangertest(formula=log(N1)~log(N2),data=LIMSMadDF)

MadCasedat<-RollPerPos(LatCaseDF,"Cases","Tests",Facet="Site")%>%
  filter(Site=="Madison")

MadLIMsdata<-RollAvg(LIMSFullDF,var=c("N1","N2","PMMoV","BCoV"))%>%
  filter(Site=="Madison")%>%
  select(Site,Date,N1,N2,PMMoV,BCoV)
LIMSFullDFAllRows <- LIMSFullDFAllRows%>%
  select(-N1,-N2,-PMMoV,-BCoV)
MadLIMsdata2 <- inner_join(MadLIMsdata,LIMSFullDFAllRows,by=c("Date","Site"))

Maddata <- inner_join(MadCasedat,MadLIMsdata2,by=c("Date","Site"))


TSMad <- ts(Maddata)
N1TSVec <- TSMad[,6]
N2TSVec <- TSMad[,7]
PMMoVTSVec <- TSMad[,8]
BCoVTSVec <- TSMad[,9]
FlowRateTSVec <- TSMad[,11]
ConductivityTSVec <- TSMad[,21]
temperatureTSVec <- TSMad[,57]
tssTSVec <- TSMad[,59]

CasesTSVec <- TSMad[,3]
TestsTSVec <- TSMad[,4]
Per_posTSVec <- TSMad[,5]


ccf(N1TSVec,FlowRateTSVec)

```

```{r cover testing}
#PH
LIMSFullDFAllRows%>%
  mutate(ph=as.numeric(ph))%>%
  filter(ph<100)%>%
  ggplot()+
  geom_point(aes(x=ph,y=N1,color="N1"))+
  geom_point(aes(x=ph,y=N1Error,color="N1Error"))+
  scale_y_log10()+
  ggtitle("No clear relation between ph and N1/N1Error")

#FlowRate
LIMSFullDFAllRows%>%
  mutate(FlowRate=as.numeric(FlowRate))%>%
  select(FlowRate,!FlowRate)%>%
  group_by(Site)%>%
  summarise(FlowRateS=mean(FlowRate,na.rm=TRUE),Pop=mean(Pop,na.rm=TRUE))%>%
  ggplot()+
  geom_point(aes(x=Pop,y=FlowRateS))+
  ggtitle("Nearly Perfect linear relation between Pop and Flowrate")

LIMSFullDFAllRows%>%
  group_by(Site)%>%
  summarise(SE1=mean(N1Error,na.rm=TRUE),N1S=mean(N1,na.rm=TRUE),Pop=mean(Pop,na.rm=TRUE))%>%
  ggplot()+
  geom_point(aes(x=Pop,y=SE1))+
  scale_x_log10()+
  ggtitle("no clear relationship between N1/N1Error and Pop")

#capacity_mgdS 
LIMSFullDFAllRows%>%
  mutate(capacity_mgd=as.numeric(capacity_mgd))%>%
  select(capacity_mgd,!capacity_mgd)%>%
  group_by(Site)%>%
  summarise(capacity_mgdS=mean(capacity_mgd,na.rm=TRUE),Pop=mean(Pop,na.rm=TRUE))%>%
  ggplot()+
  geom_point(aes(x=Pop,y=capacity_mgdS))+
  ggtitle("Nearly Perfect linear relation between Pop and capacity_mgdS")
#TO DO capacity_mgd variance within Site

#conductivity 
LIMSFullDFAllRows%>%
  mutate(conductivity=as.numeric(conductivity))%>%
  select(conductivity,!conductivity)%>%
  group_by(Site)%>%
  ggplot()+
  geom_point(aes(x=conductivity,y=N1Error))+
  scale_y_log10()+
  ggtitle("no clear relation between N1Error and conductivity")
#TO DO conductivity variance within Site

#sample_collect_time 
LIMSFullDFAllRows%>%
  mutate(sample_collect_time=as.POSIXct(sample_collect_time,format="%H:%M"))%>%
  select(sample_collect_time,!sample_collect_time)%>%
  ggplot()+
  geom_point(aes(x=sample_collect_time,y=N1Error))+
  scale_y_log10()+
  ggtitle("no clear relation between sample_collect_time and N1Se")
#TO DO conductivity variance within Site

LIMSFullDFAllRows%>%
  group_by(sample_type)%>%
  summarise(N1=mean(N1,na.rm=TRUE),N1SE=mean(N1Error,na.rm=TRUE))

LIMSFullDFAllRows%>%
  mutate(tss=as.numeric(tss))%>%
  select(tss,!tss)%>%
  ggplot()+
  geom_point(aes(x=tss,y=N1Error))+
  scale_y_log10()+
  ggtitle("no clear relation between sample_collect_time and N1Se")


LIMSFullDFAllRows%>%
  mutate(temperature=as.numeric(temperature))%>%
  select(temperature,!temperature)%>%
  ggplot()+
  geom_point(aes(x=temperature,y=N1Error))+
  scale_y_log10()+
  ggtitle("no clear relation between sample_collect_time and N1Se")
```


```{r PMMoV&BCoV CCF}
plot(log(N1TSVec))
plot(log(PMMoVTSVec))
plot(log(BCoVTSVec))

ccf(log(PMMoVTSVec),log(N1TSVec),type = c("correlation"),na.action = na.pass)
ccf(log(BCoVTSVec),log(N1TSVec),type = c("correlation"),na.action = na.pass)
ccf(log(PMMoVTSVec),log(BCoVTSVec),type = c("correlation"),na.action = na.pass)

#might be leading one or lagging the other
#what is the relationship between N1 and PMMoV with high ccf
#weighting? of weird values
#window - outliers - trend

#ccf of loess smooth for N1 and PMMoV over values of span
#detrend N1?


#PMMoV trend
acf(PMMoVTSVec,na.action = na.pass)
pacf(PMMoVTSVec,na.action = na.pass)


MadLIMsdata
LIMSFullDF%>%
  filter(Site=="Madison")
```

```{r}

plot(Per_posTSVec)
plot(log(N1TSVec))


ccfvalues1  <-  ccf(Per_posTSVec,log(N1TSVec),type = c("correlation"),na.action = na.pass)

alldata1 <- ts.intersect(Per_posTSVec,log(N1TSVec),
                         N1A=stats::lag(log(N1TSVec),1),
                         N1B=stats::lag(log(N1TSVec),-20),
                         N1C=stats::lag(log(N1TSVec),10),
                         N1D=stats::lag(log(N1TSVec),20))


tryit1  <- lm(Per_posTSVec~N1D+N1C, data = alldata1)

PerN1ModSum <- summary(tryit1)

#PerN1ACFResid <- acf2(residuals(tryit1))
R2=0.2849
#Check for geo mean
#N1 vs %Pos

#not sure on analysis
#look at assumptions
#sliding window package
#many are doing the same things with different goals
#at least same idea
#Other approaches

#should be standard but it seems not to be
#not very complicated - how to pick right simple thing
#Chris - what he knows about TS
```



```{r}
#-stats::lag(CasesTSVec,1)
ccfvalues2  <-  ccf(CasesTSVec,N1TSVec,type = c("correlation"),na.action = na.pass)

alldata2 <- ts.intersect(CasesTSVec,log(N1TSVec),
                         N1A=stats::lag(log(N1TSVec),1),
                         N1B=stats::lag(log(N1TSVec),-8),
                         N1C=stats::lag(log(N1TSVec),-20),
                         N1D=stats::lag(log(N1TSVec),20),
                         N1E=stats::lag(N1TSVec,-20),
                         N1F=stats::lag(N1TSVec,20))


tryit2  <- lm(CasesTSVec~N1C+N1D, data = alldata2)

CaseN1ModSum <- summary(tryit2)

CaseN1ACFResid <- acf2(residuals(tryit2))

R2= 0.4441

plot(CasesTSVec)

plot(log(N1TSVec))

ts.plot(CasesTSVec,(-51.901*stats::lag(log(N1TSVec),-20)+65.434*stats::lag(log(N1TSVec),20)-60.471),
        col=c("red","blue"), #auto.legend = TRUE,
        gpars=list(xlab="Time (Days)", ylab="Cases"))
legend("bottomleft", legend=c("N1 TS Model","Cases"), col=1:3, lty=1, cex=1)

ts.plot(CasesTSVec-(-51.901*stats::lag(log(N1TSVec),-20)+65.434*stats::lag(log(N1TSVec),20)-60.471))


#library(SlidingWindows)
#plot(dmca.SlidingWindows(CasesTSVec,N1TSVec)$dmca)

# Maddata2 <- Maddata%>%
#   filter(!is.na(N1),!is.na(Cases))
# TSMad2 <- ts(Maddata2)
# N1TSVec2 <- TSMad2[,6]
# CasesTSVec2 <- TSMad2[,3]
# library(testcorr)
# cc.test(x=N1TSVec2,y=CasesTSVec2, max.lag=14)

# library(marima)
# ar<-c(1:20)
# ma<-c(1:20)
# Model3 <- define.model(kvar=2, ar=ar, ma=ma, rem.var=c(0), reg.var=c(0))
# 
# MarimaMod <- marima(TSMad[,c(3,6)],means=1, ar.pattern=Model3$ar.pattern,
#   ma.pattern=Model3$ma.pattern, Check=FALSE, Plot=TRUE, penalty=1)
# 
# MarimaMod$ma.fvalues
```



```{r}
#CasesTSVec2 <- TSSellCase[,3]
#PMMoVTSVec2 <- TSSellLIMS[,4]
#BCoVTSVec2 <- TSSellLIMS[,5]


SellCasedat <- RollPerPos(LatCaseDF,"Cases","Tests",Facet="Site")%>%
  filter(Site=="UW-Sellery")

SellLIMsdata <- RollAvg(LIMSFullDF,var=c("N1","N2","PMMoV"))%>%
  filter(Site=="UW-Sellery")%>%
  select(Date,N1,N2,PMMoV,BCoV)


Selldata <- inner_join(SellCasedat,SellLIMsdata,by=c("Date"))

TSSell <- ts(Selldata)
N1TSVecSell <- TSSell[,6]
Per_posTSVecSell <- TSSell[,5]

plot(Per_posTSVecSell)
plot(log(N1TSVecSell))

ccfvaluesSell  <-  ccf(Per_posTSVecSell,log(N1TSVecSell),type = c("correlation"),na.action = na.pass)


#lag2.plot(Per_posTSVec,N1TSVec, 5)

alldataSell <- ts.intersect(Per_posTSVecSell,N1TSVecSell,
                         N1A=stats::lag(log(N1TSVecSell),-3),
                         N1B=stats::lag(N1TSVecSell,-12),
                         N1C=stats::lag(log(N1TSVecSell),-11),
                         N1D=stats::lag(log(N1TSVecSell),13))


tryitSell  <-  lm(Per_posTSVecSell~N1C+N1D+N1A, data = alldataSell)

summary(tryitSell)

acf2(residuals(tryitSell))
R2=.4758


ts.plot(Per_posTSVecSell,( -0.02383*stats::lag(log(N1TSVecSell),-3)
                           -0.35840*stats::lag(log(N1TSVecSell),-11)
                           +0.10305*stats::lag(log(N1TSVecSell),13)
                           +4.25384))
ts.plot(Per_posTSVecSell-( -0.02383*stats::lag(log(N1TSVecSell),-3)
                           -0.35840*stats::lag(log(N1TSVecSell),-11)
                           +0.10305*stats::lag(log(N1TSVecSell),13)
                           +4.25384))
```


```{r by season}
MinConc=min(LIMSFullDF$Date)
MaxConc=max(LIMSFullDF$Date)
  
FallRange=c(MinConc,mdy("12/11/2020"))
SpringRange=c(mdy("1/25/2021"),MaxConc)

SellSpringdata <- Selldata%>%
    filter(Date >= SpringRange[1] & Date <= SpringRange[2])


TSSellSpring <- ts(SellSpringdata)
N1TSVecSellSpring <- TSSellSpring[,6]
Per_posTSVecSellSpring <- TSSellSpring[,5]

plot(Per_posTSVecSellSpring)
plot(log(N1TSVecSellSpring))

ccfvaluesSellSpring  <-  ccf(Per_posTSVecSellSpring,log(N1TSVecSellSpring),type = c("correlation"),na.action = na.pass)

alldataSellSpring <- ts.intersect(Per_posTSVecSellSpring,N1TSVecSellSpring,
                         N1A=stats::lag(N1TSVecSellSpring,-13),
                         N1B=stats::lag(N1TSVecSellSpring,6),
                         N1C <- stats::lag(N1TSVecSellSpring,-11),
                         N1D=stats::lag(N1TSVecSellSpring,-8))


tryitSellSpring  <-  lm(Per_posTSVecSellSpring~N1A+N1B, data = alldataSellSpring)

summary(tryitSellSpring)

acf2(residuals(tryitSellSpring))


R2=0.439
#small numbers mean low confidence in results
#Stationary
#

```

```{r by season Fall}
FallSpringdata <- Selldata%>%
    filter(Date >= FallRange[1] & Date <= FallRange[2])


TSSellSpring <- ts(SellSpringdata)
N1TSVecSellFall <- TSSellSpring[,6]
Per_posTSVecSellFall <- TSSellSpring[,5]

plot(Per_posTSVecSellFall)
plot(log(N1TSVecSellFall))

ccfvaluesSellFall  <-  ccf(Per_posTSVecSellFall,log(N1TSVecSellFall),type = c("correlation"),na.action = na.pass)

alldataSellFall <- ts.intersect(Per_posTSVecSellFall,N1TSVecSellFall,
                         N1A=stats::lag(N1TSVecSellFall,8),
                         N1B=stats::lag(N1TSVecSellFall,-6),
                         N1C <- stats::lag(N1TSVecSellFall,-11),
                         N1D=stats::lag(N1TSVecSellFall,-8))


tryitSellFall  <-  lm(Per_posTSVecSellFall~N1A, data = alldataSellFall)

summary(tryitSellFall)

acf2(residuals(tryitSellFall))

R2=0.227
```











```{r}
# SimpleMerge<-inner_join(MadLIMsdata,MadCasedat,by=c("Date"))
# SimpleMerge%>%
#   ggplot()+
#     geom_point(aes(x=Cases,y=N1/PMMoV))+
#   scale_y_log10()+
#   scale_x_log10()
# SimpLM<-lm(Cases~log(N1),data=SimpleMerge)
# summary(SimpLM)
# SimpleMerge$Resid<-residuals(SimpLM)
# 
# 
# acf2(ts(residuals(SimpLM)))
# summary(sarima (residuals(SimpLM), 1,0,0, no.constant=F))
```





```{r}
# acf(log(MadLIMsdata$N1))
# pacf(log(MadLIMsdata$N1))
# cor(log(MadLIMsdata$N1),log(MadLIMsdata$N2))
# ccfvalues <- ccf(log(N1TSVec),log(N2TSVec),type = c("correlation"))
#covariance
#correlation

# MadLIMsdata%>%
#   ggplot()+
#   geom_point(aes(x=Date,y=N1-lag(N1)))
```




```{r}
HFGFrame%>%
  filter(!is.na(N1),!is.na(Date),!is.na(`Filter replicates`),!is.na(Site))%>%
  group_by(Site,Date,`Filter replicates`)%>%
  summarize(var=var(N1))%>%
  filter(!is.na(var))%>%
  ungroup()%>%
  summarize(meanvar=mean(var))
2.5075450674e+10


HFGFrame%>%
  filter(!is.na(N1),!is.na(Date),!is.na(Site))%>%
  group_by(Site,Date)%>%
  summarize(var=var(N1))%>%
  filter(!is.na(var))%>%
  ungroup()%>%
  summarize(meanvar=mean(var))
2.756624e+12				


HFGFrame%>%
  group_by(Date,Site)%>%
  summarize(N1=mean(N1))%>%
  mutate(Pre1=lag(N1,n=1),Nxt1=lead(N1,n=1))%>%
  filter(!is.na(Nxt1),!is.na(Pre1))%>%
  pivot_longer(N1:Nxt1)%>%
  summarize(var=var(value))%>%
  filter(!is.na(var))%>%
  ungroup()%>%
  summarize(meanvar=mean(var))
5.5569708129e+10

# library(nlme)
# interaction.plot (HFGFrame$Date, factor(HFGFrame$Site), HFGFrame$N1, lty=c(1:3),lwd=2,ylab="mean of Y", xlab="time", trace.label="Treatment")
# nestinginfo <- groupedData(N1 ~ Site | `Filter replicates`, data= HFGFrame)
```
