---
title: "HFG Variance"
author: "Marlin"
date: "7/9/2021"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r warning = FALSE, message = FALSE,echo = FALSE}
library(ggpubr)
library(dplyr)

library(lubridate)

#Data Files and prep work
source("../../Scripts/GenPlotMaking.R")
source("../../Scripts/WasteWaterDataProccess.R")
source("../../Scripts/CassesDataProccess.R")
source("../../Scripts/HelperFunctions.R")

PathStarter="Z:/"
HFGCasesFN  <-  paste0(PathStarter,"COVID-19_WastewaterAnalysis/data/raw/HighFreq_CaseData_2021-05-07.csv")
HFGWasteFN <-  paste0(PathStarter,"COVID-19_WastewaterAnalysis/data/raw/HFG data for stats corrected 071421.xlsx")
HFGPop <- paste0(PathStarter,"COVID-19_WastewaterAnalysis/data/raw/HFGPop.csv")

HFGWasteDF <- HFGWastePARSER(HFGWasteFN)
HFGCaseDF <- HFGCasesPARSER(HFGCasesFN)
  #mutate(across(c("ReportedCases", "EpisodeCases","",""), scale2))


```


```{r fig.width=8, fig.height=8,echo = FALSE}

HFGWasteDF%>%
  ggplot()+
  aes(x=Date,y=N1GC)+
  geom_point(aes(color=as.factor(Well),shape=as.factor(Filter )))+
  facet_wrap(~Plant,scales = "free_y")

library(forecast)
library(zoo)
HFGWasteUSEDF <- HFGWasteDF%>%
  filter(Plant!="River Falls")%>%
  select(Date,Plant,N1GC,Filter)

LoessHFG <- HFGWasteUSEDF%>%
  group_by(Date,Plant)%>%
  summarise(N1Date=exp(mean(log(N1GC),na.rm=TRUE)))%>%
  ungroup()%>%
  arrange(Plant, Date) %>%
  mutate(RealN1=predict(loess(N1Date~as.numeric(Date),span=.7)))

HFGSumFilter <- HFGWasteUSEDF%>%
  group_by(Date,Plant,Filter)%>%
  summarise(N1Filt=exp(mean(log(N1GC),na.rm=TRUE)))

HFGDataMod <- full_join(full_join(LoessHFG,HFGWasteDF,by=c("Date","Plant")),
          HFGSumFilter,by=c("Date","Plant","Filter"))%>%
  select(Date,Plant,RealN1,N1Date,N1Filt,N1GC)

SSM <- function(Messured,Real){
  return(sum((log(Messured)-log(Real))^2,na.rm=TRUE)/(length(Real)-1))
}

SSM(HFGDataMod$N1GC,HFGDataMod$RealN1)



```
