---
title: "HFGAnalysis"
author: "Marlin"
date: "7/23/2021"
output: html_document
---

```{r}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r Start enviroment, message=FALSE, Warning =FALSE}
library(ggpubr)
library(dplyr)
library(forecast)
library(lmtest)
library(lubridate)

#Data Files and prep work
source("../../Scripts/GenPlotMaking.R")
source("../../Scripts/WasteWaterDataProccess.R")
source("../../Scripts/CassesDataProccess.R")
source("../../Scripts/HelperFunctions.R")

```

```{r DF Set Up, warning=FALSE,message=FALSE}


PathStarter="Z:/"

HFGWasteFN  <-  paste0(PathStarter,"COVID-19_WastewaterAnalysis/data/raw/HFG data for stats corrected 071421.xlsx")
HFGCaseFN <- paste0(PathStarter,"COVID-19_WastewaterAnalysis/data/raw/HighFreq_CaseData_2021-05-07.csv")
#Z:\COVID-19_WastewaterAnalysis\data\raw

#Reads Transformed HFG Data
HFGFrame <- HFGWastePARSER(HFGWasteFN)%>%
  rename(Site=Plant,N1=N1GC,N2=N2GC,PMMoV=PMMOVGC,Pct_BCoV=BCoV)%>%
  mutate(Filter=as.character(Filter),Well=as.character(Well))%>%
  rename(`Filter replicates`=Filter)



HFGCaseDFNoReported <- HFGCasesPARSER(HFGCaseFN)

#Reported Cases match census level case data
HFGCaseDFReportedOnly <- HFGCaseDFNoReported%>%
  mutate(Date=Date+1,ReportedCases=ConfirmedCases)%>%
  select(Date,Site,ReportedCases)

HFGCaseDF  <-  full_join(HFGCaseDFReportedOnly,HFGCaseDFNoReported,by=c("Date","Site"))


HFGCaseDFRoll <- HFGCaseDF%>%
  mutate(EpisodeCases=ifelse(EpisodeCases==-999,2.5,EpisodeCases),
         CollectedCases=ifelse(CollectedCases==-999,2.5,CollectedCases),
         ConfirmedCases=ifelse(ConfirmedCases==-999,2.5,ConfirmedCases),
         ReportedCases=ifelse(ReportedCases==-999,2.5,ReportedCases))%>%
  RollAvg(Facet="Site")%>%
  select(Date,Site,ends_with("Cases"))

HFGPop <- read.csv("../../../UntrackedData/HFGPop.csv.txt")%>%
  select(Site=wwtp_name,Population=pop_served)%>%
  mutate(Population=Population/100000)

HFGCaseDF <- full_join(HFGPop,HFGCaseDF,by="Site")

HFGCaseDFRoll <- full_join(HFGPop,HFGCaseDFRoll,by="Site")

#Generating the weekends starts and end dates
#TO DO:Capture the weekend if the data intersects with it
HFGDateRangeDF <- WeekendGen(HFGCaseDF$Date)
```

