---
title: "HFGUpdatedData"
author: "Marlin"
date: "7/16/2021"
output: html_document
---

```{r}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r Start enviroment, message=FALSE, Warning=FALSE}
library(ggpubr)
library(dplyr)
library(forecast)
library(lmtest)
library(lubridate)

#Data Files and prep work
source("../../Scripts/GenPlotMaking.R")
source("../../Scripts/WasteWaterDataProccess.R")
source("../../Scripts/CassesDataProccess.R")
source("../../Scripts/HelperFunctions.R")

```

```{r DF Set Up, warning=FALSE,message=FALSE}


PathStarter="Z:/"

HFGWasteFN  <-  paste0(PathStarter,"COVID-19_WastewaterAnalysis/data/raw/HFG data for stats corrected 071421.xlsx")
HFGCaseFN <- paste0(PathStarter,"COVID-19_WastewaterAnalysis/data/raw/HighFreq_CaseData_2021-05-07.csv")
#Z:\COVID-19_WastewaterAnalysis\data\raw

#Reads Transformed HFG Data
HFGFrame <- HFGWastePARSER(HFGWasteFN)%>%
  rename(Site=Plant,N1=N1GC,N2=N2GC,PMMoV=PMMOVGC,Pct_BCoV=BCoV)%>%
  mutate(Filter=as.character(Filter),Well=as.character(Well))%>%
  rename(`Filter replicates`=Filter)



HFGCaseDFNoReported <- HFGCasesPARSER(HFGCaseFN)

#Reported Cases match census level case data
HFGCaseDFReportedOnly <- HFGCaseDFNoReported%>%
  mutate(Date=Date+1,ReportedCases=ConfirmedCases)%>%
  select(Date,Site,ReportedCases)

HFGCaseDF  <-  full_join(HFGCaseDFReportedOnly,HFGCaseDFNoReported,by=c("Date","Site"))


HFGCaseDFRoll <- HFGCaseDF%>%
  mutate(EpisodeCases=ifelse(EpisodeCases==-999,2.5,EpisodeCases),
         CollectedCases=ifelse(CollectedCases==-999,2.5,CollectedCases),
         ConfirmedCases=ifelse(ConfirmedCases==-999,2.5,ConfirmedCases),
         ReportedCases=ifelse(ReportedCases==-999,2.5,ReportedCases))%>%
  RollAvg(Facet="Site")%>%
  select(Date,Site,ends_with("Cases"))

HFGPop <- read.csv(paste0(PathStarter,"COVID-19_WastewaterAnalysis/data/raw/HFGPop.csv"))%>%
  select(Site=wwtp_name,Population=pop_served)

HFGCaseDF <- full_join(HFGPop,HFGCaseDF,by="Site")

HFGCaseDFRoll <- full_join(HFGPop,HFGCaseDFRoll,by="Site")

#Generating the weekends starts and end dates
#TO DO:Capture the weekend if the data intersects with it
HFGDateRangeDF <- WeekendGen(HFGCaseDF$Date)
```



```{r, message=FALSE, Warning =FALSE}
  missing_codes <- c("","NA","0","Undetected","Not Detected",
                     "Field Parameters to be filled in", 
                     "Inhibited-to be re-ran", "#DIV/0!",
                     "Undetermined", "LA")


OldHFG <- read_excel("../../../UntrackedData/HFG data for stats preliminary 3-18-21.xlsx",
                                                 na = missing_codes,
                                                 col_types = c("text","text", "date", rep("numeric", 4),"text",rep("numeric", 2),"text",rep("numeric", 3)),
                                                 sheet = 1)%>%
    rename(repName="...2",
           Date="Collection Date",
           N1Ct="N1 CT",
           N1GC="N1 GC/L",
           N1LOD="N1 <LOD",
           N2Ct="N2 CT",
           N2GC="N2 GC/L",
           N2LOD="N2 <LOD",
           PMMOVCT="PMMOV CT",
           PMMOVGC="PMMOV GC/L",
           BCoV="BCoV% recovery",
           Filter = "Filter Rep",
           Well = "Well Rep")%>%
    mutate(N1LOD=N1LOD=="Y",
           N2LOD=N2LOD=="Y",
           Date=as.Date(Date),
           AVG = AVGGenFN(N1GC, N2GC))%>%
  select(Date,Site=Plant,Filter,Well,N1=N1GC,N2=N2GC)%>%
  mutate(Filter=as.character(Filter),Well=as.character(Well))

HFGFrameUp <- HFGFrame%>%
  select(Date,Site,Well,N1,N2,PMMoV,Pct_BCoV,AVG,`Filter replicates`)


HFGFrameUp%>%
  group_by(Date,Site)%>%
  summarize(geoN1=exp(mean(log(N1))),geoN2=exp(mean(log(N2))),geoAVG=exp(mean(log(AVG))),
            SEN1=sqrt(var(log(N1))/n()),SEN2=sqrt(var(log(N2))/n()),SEAVG=sqrt(var(log(AVG))/n()),
            SEN1N=sqrt(var(N1)/n()),SEN2N=sqrt(var(N2)/n()),SEAVGN=sqrt(var(AVG)/n()))%>%
  ggplot()+
  geom_point(aes(x=geoN1,y=SEN1N))+
  scale_y_log10()+scale_x_log10()



modeltransform <- function(Vector){
  return(log(Vector))
}

HFGTran <- HFGFrameUp%>%
  group_by(Site,Date)%>%
  mutate(GeoMean=exp(mean(log(N1))),
         ArthMean=mean(N1))

HFGTran%>%
  ggplot()+
  aes(x=modeltransform(GeoMean),y=modeltransform(N1))+
  geom_point()+
  geom_smooth(method="lm")


HFGTranSummer <- HFGTran%>%
  summarise(GeoMean=exp(mean(log(modeltransform(N1)))),
            SE=sqrt(var(modeltransform(N1))/n()))
            
HFGTranSummer%>%
  ggplot()+
  aes(x=GeoMean,y=SE)+
  geom_point()+
  geom_smooth(method="lm")


summary(lm(SE~GeoMean,data=HFGTranSummer))



#Vector auto regressive models
```

```{r HFG Lims Comp,message=FALSE}
HFGFrameMad <- HFGFrameUp%>%
  filter(Site == "Madison")%>%
  select(Date,Site,Filter=`Filter replicates`,Well,N1,N2)%>%
  group_by(Date,Site)%>%
  filter(!is.na(N1))%>%
  mutate(N=n())%>%
  filter(Filter!="4")#,N==9)
LIMSMadDF <- LIMSFullDF%>%
  filter(Site == "Madison")%>%
  select(-PMMoV,-BCoV,-FlowRate,-Pop)

ggplot()+
  aes(x=Date,y=N1)+
  geom_point(aes(color = Filter),data = HFGFrameMad)+
  geom_line(data = LIMSMadDF)+
  facet_wrap(~Site)+
  scale_y_log10()+
  scale_x_date(limits = c(mdy("1/20/2021"),mdy("3/14/2021")))
  #geom_vline(xintercept=ymd("2021-02-12"))
#mdy("1/20/2021"),mdy("3/14/2021")
#mdy("2/10/2021"),mdy("2/18/2021")



HFGFrameMadSum <- HFGFrameMad%>%
  group_by(Date,Site)%>%
  summarize(MN1=mean(N1,na.rm = TRUE),MN2=mean(N2,na.rm = TRUE),
            seN1=sqrt(var(N1,na.rm = TRUE)/n()),seN2=sqrt(var(N2,na.rm = TRUE)/n()),N=n())

# HFGFrameMad%>%
#   filter(Date>mdy("2/10/2021"),Date<mdy("2/18/2021"))


HFGLimsComp <- inner_join(HFGFrameMadSum,LIMSMadDF,by=c("Date","Site"))%>%
  mutate(difN1=round(MN1)-N1,difN2=round(MN2)-N2,
         diffN1Error=round(seN1)-N1Error,diffN2Error=round(seN2)-N2Error)%>%
  filter(abs(difN1)>10)
  #select(Date,Site,difN1,diffN1Error,difN2,diffN2Error)

HFGLimsComp

HFGLimsComp%>%
  ggplot()+
  aes(x=Date)+
  geom_point(aes(y=abs(difN1),color="N1 concentration Difference"))+
  geom_point(aes(y=abs(diffN1Error),color="N1Error concentration Difference"))+
  ggtitle("Difference between HFG and LIMS")

#try to understand correlation of data
#use geometric line instead: bounce less?
#weight by error
#loess smoothing better idea of weights?
```


```{r PMMoV Analysis}
SiteOptions2=c("Kenosha","Madison", "Sun Prairie","Wausau")




PMMoVUseDF=HFGFrameUp%>%
  filter(Site %in% SiteOptions2)%>%
  mutate(`PMMoV Level`=ifelse(PMMoV<1*10^7,"Low","Medium"))%>%
  mutate(`PMMoV Level`=ifelse(PMMoV>1*10^8,"High",`PMMoV Level`))%>%
  mutate(`PMMoV Level`=factor(`PMMoV Level`,levels=c("High","Medium","Low")))

PMMoVUseDF%>%
  ggplot()+aes(x=PMMoV,y=N1,color=`PMMoV Level`)+geom_point()+scale_y_log10()+
  scale_x_log10()+facet_wrap(~Site)+ggtitle("N1 Vs PMMoV")+
  xlab("PMMoV (GC/L)")+ylab("N1 (GC/L)")

PMMoVUseDF%>%
  ggplot()+aes(x=Date,y=N1,color=`PMMoV Level`)+geom_point()+
  ylab("N1 (GC/L)")+ggtitle("PMMoV and N1 appear unrelated")+
  scale_y_log10()+facet_wrap(~Site)

cor(log(HFGFrameUp$N1),log(HFGFrameUp$PMMoV),use="pairwise.complete.obs")
```


```{r PMMoV Analysis 2}

BCoVUseDF=HFGFrame%>%
  filter(Site %in% SiteOptions2)%>%
  filter(N1<2e6)%>%
  mutate(`Percent BCoV Recovery`=ifelse(Pct_BCoV<.5,"Low","Medium"))%>%
  mutate(`Percent BCoV Recovery`=ifelse(Pct_BCoV>10,"High",`Percent BCoV Recovery`))%>%
  mutate(`Percent BCoV Recovery`=factor(`Percent BCoV Recovery`,levels=c("High","Medium","Low")))

BCoVUseDF%>%
  ggplot()+aes(x=Pct_BCoV,y=N1,color=`Percent BCoV Recovery`)+geom_point()+
  xlab("Percent Bcov Recovery")+
  ylab("N1 (GC/L)")+
  scale_y_log10()+
  scale_x_log10()+
  facet_wrap(~Site)+
  ggtitle("N1 Vs %Bcov recovery")


BCoVUseDF%>%
  ggplot()+aes(x=Date,y=N1,color=`Percent BCoV Recovery`)+geom_point()+
  ggtitle("Percent BCoV recovery and N1 appear unrelated")+
  scale_y_log10()+
  facet_wrap(~Site)

cor(log(HFGFrameUp$N1),log(HFGFrameUp$Pct_BCoV),use="pairwise.complete.obs")


```

```{r}
HFGSEPop <- full_join(HFGPop,HFGFrame, by=c("Site"))%>%
  group_by(Site,Date)%>%
  summarise(seN1=sqrt(var(N1)/n()),seN2=sqrt(var(N2)/n()),seAVG=sqrt(var(AVG)/18),Pop=mean(Population,na.rm=TRUE))%>%
  ungroup()%>%
  group_by(Site)%>%
  summarise(SeMean=mean(seN1,na.rm=TRUE),Pop=mean(Pop,na.rm=TRUE))%>%
  arrange(Pop)

HFGSEPop

HFGSEPop%>%
  ggplot()+
  aes(x=Pop,y=SeMean)+
  geom_point()


#no clear relationship between population and variation of the 9 samples

```

```{r N1vN2vAVG}

SEHFGDF <- HFGFrameUp%>%
  group_by(Site,Date)%>%
  mutate(seN1=sqrt(var(N1)/n()),seN2=sqrt(var(N2)/n()),seAVG=sqrt(var(AVG)/18))



Alp=.5
SEHFGDF%>%
  ggplot()+
  geom_histogram(aes(x=seN1,fill="N1"),alpha=Alp)+
  geom_histogram(aes(x=seN2,fill="N2"),alpha=Alp)+
  geom_histogram(aes(x=seAVG,fill="AVG"),alpha=Alp)+
  scale_y_log10()+
  scale_x_log10()



SEHFGDFSum <- HFGFrameUp%>%
  group_by(Site,Date)%>%
  summarise(seN1=sqrt(var(N1)/n()),seN2=sqrt(var(N2)/n()),seAVG=sqrt(var(AVG)/18))

SEHFGDFSum%>%
  ggplot()+
  geom_histogram(aes(x=log(seN1)-log(seN2)))

  

SEHFGDFSum%>%
  ungroup()%>%
  summarise(mean(log(seN1),na.rm = TRUE),mean(log(seN2),na.rm = TRUE),mean(log(seAVG),na.rm = TRUE))

t.test(log(SEHFGDFSum$seN1),log(SEHFGDFSum$seN2))
t.test(log(SEHFGDFSum$seN1),log(SEHFGDFSum$seAVG))
t.test(log(SEHFGDFSum$seAVG),log(SEHFGDFSum$seN2))

```


```{r cases}
MaskedDataRange="1-4 Cases"
inner_join(HFGFrame,HFGCaseDF,by=c("Site","Date"))%>%
  mutate(PHI_masking = ifelse(ReportedCases<0,MaskedDataRange,"Reported values"),
          ReportedCases = ifelse(ReportedCases<0,2.5,ReportedCases))%>%
  filter(!is.na(PHI_masking))%>%
  group_by(Site)%>%
  filter(sum(PHI_masking=="Reported values")>120)%>%
  ggplot()+
  geom_rect(aes(xmin=Date-.5,xmax=Date+.5,ymin=0,ymax=ReportedCases/(Population),fill=PHI_masking),color="black")+
  geom_point(aes(x=Date,y=log(N1)))+
  facet_wrap(~Site,scales = "free", nrow=3)+ 
      scale_fill_manual(values=c("light blue","gray"))

```


```{r include=FALSE}
# HFGFrameUp%>%
#   group_by(Date,Site)%>%
#   mutate(N=n())%>%
#   filter(N!=9)#,N!=12)%>%
#   #filter(Site=="Madison")
```

```{r covarients}

CoverHFG <- HFGFrame%>%
  select(-N1Ct,-N2Ct,-PMMOVCT)

CoverHFG%>%
  ggplot()+
  geom_point(aes(x=Date,y=N1,color=N1LOD))+
  scale_y_log10()+
  geom_hline(yintercept = 4*10e3)
  facet_wrap(~Site)


# CoverHFG%>%
#   filter(N1LOD==TRUE)%>%
#   filter(N1>4*10e3)
# CoverHFG%>%
#   filter(N1LOD==FALSE)%>%
#   filter(N1<4*10e3)

4*10e3
```


```{r Comp data,message=FALSE}

HFGFrameUp <- HFGFrameUp%>%
  rename(Filter = `Filter replicates`)

MergedFullData <- full_join(OldHFG,HFGFrameUp,by=c("Date","Site","Filter","Well"),suffix=c(".Old",".New"))%>%
  mutate(Diff=abs(N1.Old-N1.New))

  
  
MergedFullData%>%
  group_by(Date,Site)%>%
  summarize(N1.Old=mean(log10(N1.Old)),N1.New=mean(log10(N1.New)))%>%
  # ungroup()%>%
  # filter(!is.na(N1.Old),!is.na(N1.New))%>%
  # summarize(max(N1.Old),max(N1.New))
  ggplot()+
  aes(x=Date)+
  geom_point(aes(y=N1.Old,color="old"),size=1)+
  geom_point(aes(y=N1.New,color="new"),size=1)+
  # aes(x=Date,color=Filter)+
  # geom_point(aes(y=Diff))+
  labs(y="N1",color="Data")+
  facet_wrap(~Site)

MergedFullDataTD <- MergedFullData%>%
  pivot_longer(N1.Old:N1.New,values_to="N1")

#+name+Site:Date:Filter:name+Date:Site:name
anovaModel <- aov(terms(N1~Site+Site:Date+Site:Date:Filter, keep.order = TRUE),data=MergedFullDataTD)

summary(anovaModel)



```

```{r}
DaySum <- MergedFullData%>%
  group_by(Date,Site)%>%
  summarize(DayMean.Old=mean(log(N1.Old)),DayVar.Old=var(log(N1.Old)),
            DayMean.New=mean(log(N1.New)),DayVar.New=var(log(N1.New)))%>%
  ungroup()
FillterSum <- MergedFullData%>%
  group_by(Date,Site,Filter)%>%
  summarize(DayMean.Old=mean(log(N1.Old)),DayVar.Old=var(log(N1.Old)),
            DayMean.New=mean(log(N1.New)),DayVar.New=var(log(N1.New)))%>%
  ungroup()

t.test(DaySum$DayVar.Old,DaySum$DayVar.New,paired=T)

t.test(FillterSum$DayVar.Old,FillterSum$DayVar.New,paired=T)
```

```{r}
DaySum <- HFGFrameUp%>%
  filter(N2>0)%>%
  group_by(Date,Site)%>%
  summarize(DayVarN1=var(log(N1)),DayVarN2=var(log(N2)),
            DayMeanN1=mean(log(N1)),DayMeanN2=var(log(N2)))%>%
  ungroup()

FillterSum <- HFGFrameUp%>%
  filter(N2>0)%>%
  group_by(Date,Site,Filter)%>%
  summarize(DayVarN1=var(log(N1)),DayVarN2=var(log(N2)),
            DayMeanN1=mean(log(N1)),DayMeanN2=var(log(N2)))%>%
  ungroup()


t.test(DaySum$DayMeanN1,DaySum$DayMeanN2,paired=T,alternative="greater")

t.test(FillterSum$DayMeanN1,FillterSum$DayMeanN2,paired=T,alternative="greater")



DaySumNorm <- DaySum%>%
  mutate(DayVarN1=DayVarN1/DayMeanN1,DayVarN2=DayVarN2/DayMeanN2)

FillterSumNorm <- FillterSum%>%
  mutate(DayVarN1=DayVarN1/DayMeanN1,DayVarN2=DayVarN2/DayMeanN2)

t.test(DaySum$DayVarN1,DaySum$DayVarN2,paired=T,alternative="less")

t.test(FillterSum$DayVarN1,FillterSum$DayVarN2,paired=T,alternative="less")
```

