---
title: "DHS analysis compering the base analysis to Diffrent Smoothing"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{DHS analysis compering the base analysis to Diffrent Smoothings}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


```{r load packages}
library(DSIWasteWater)
library(dplyr)
```


```{r create worksheet4}
data(Data_wastewater, package = "DSIWasteWater")

#TODO abstract saved data -> workset4? save workset4 instead?
#Filter number of sites for faster kniting time?

df <- Data_wastewater

## format data as DHS code expects
df <- df %>% 
  select(
    wwtp_name,sample_collect_date,population_served,  ## site data
    n1_sars_cov2_conc, n2_sars_cov2_conc,             ## N1, N2 measurement
    average_flow_rate                                 ## sample covariates
  ) %>% 
  rename(WWTP = wwtp_name, date = sample_collect_date) %>% 
  mutate(date = as.Date(date,format="%m/%d/%Y"))

### Note: Replacement small values with LOD/2 (as per 5/20/2022 discussion w/DHS)
##   in bin/cleanData.pl

## dependent regression variable: log of normalized average SARS-COV-2 level
workset4 <- df %>% 
  filter(average_flow_rate != "NA") %>% 
  mutate (geoMean = sqrt(n1_sars_cov2_conc*n2_sars_cov2_conc)) %>% 
  mutate(sars_cov2_adj_load_log10 = log10(
    geoMean*average_flow_rate/population_served    
  )
  )


## filter out sites with too few measurements
##  and sort by date;
workset4 <- workset4 %>% 
  group_by(WWTP) %>% 
  mutate(n = n()) %>% 
  arrange(date, .by_group = TRUE) %>% 
  ungroup %>% 
  filter(n >= 150)#To reduce knitting time
```

```{r flag outlier}
VecModOn <- "sars_cov2_adj_load_log10"

df.created <- workset4%>%
    rename(Date=date, Site = WWTP)%>%
    group_by(Site)%>%
    group_split()%>%
    lapply(LoessSmoothMod, VecModOn, "Loess", "guess")%>%
    lapply(ExpSmoothMod, VecModOn, "EXP")%>%
    lapply(sgolaySmoothMod, VecModOn, "sgolay")%>%
    bind_rows()%>%
    rename(date=Date, WWTP = Site)

```

```{r run package code}

reg_estimates <- BuildRegressionEstimateTable(df.created, 
                                     c("sars_cov2_adj_load_log10",
                                     "Loess",
                                     "EXP",
                                     "sgolay")
                                    )
head(reg_estimates)
```


```{r temp explore,fig.width=6}
library(ggplot2)




ConfMatrix(reg_estimates, "Catagory", "sars_cov2_adj_load_log10", "Loess")


reg_estimates%>%
  group_by(Method,Catagory)%>%
  summarise(n = n())%>%
  ggplot(aes(x=Catagory,y=n))+
           geom_col(aes(fill=Method),position = "dodge")+ 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

```{r make DHS plot, fig.height=5,fig.width=78}



DHSTopLevelPlots(reg_estimates, df.created, 
                 PointVal = c( "sars_cov2_adj_load_log10"),
                 LineVal = c("Loess",
                                     "EXP",
                                     "sgolay"))
```