---
title: "Untitled"
author: "Marlin"
date: '2022-06-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
ZZZ <- data.frame(x = c(1,2,3,4,5),
           y = c(3,6,7,13,16))

```

```{r}
ZZZ <- data.frame(x = c(1,2,3,4,5),
           y = c(3,6,7,13,16))

sum.lm_tester <- function(){
  lm.subset.sum <- summary(lm(y~x,data = ZZZ))
  lmreg_slope = lm.subset.sum$coefficients[2,1]
           
  lmreg_sig = lm.subset.sum$coefficients[2,4]
  
  return(c(lmreg_slope,lmreg_sig))
}
```

```{r pressure, echo=FALSE}
library(dplyr)

lm.fit_tester <- function(){
  m <- ZZZ%>%
    mutate(n=1)
  X <- as.matrix(m[c(1,3)])
  y <- c(3,6,7,13,16)

  la <- .lm.fit(X,y)
  RetA <- la$coefficients[1]
  
  rss <- sum(la$residuals^2)
  rdf <- length(y) - 2
  resvar <- rss/rdf
  R <- chol2inv(la$qr)
  se <- sqrt(diag(R) * resvar)
  RetB <- 2*pt(abs(la$coef/se),rdf,lower.tail=FALSE)[1]
  return(c(RetA,RetB))
}
```

```{r tests}
library(microbenchmarkCore)
microbenchmark(
  sum.lm_tester(),
  lm.fit_tester(),
  times=1000)
```

