---
title: "TSBestPredCorrelation"
author: "Marlin"
date: "7/22/2021"
output:
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: inline
---

```{r set up markdown settings, echo=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)

```

```{r Start enviroment, message=FALSE, warning=FALSE}
library(ggpubr)
library(forecast)
library(lmtest)
library(lubridate)
library(limma)
library(zoo)
library(dplyr)
library("robets")

#Data Files and prep work
source("../../Scripts/GenPlotMaking.R")
source("../../Scripts/WasteWaterDataProccess.R")
source("../../Scripts/CasesDataProccess.R")
source("../../Scripts/HelperFunctions.R")

```

```{r DF Set Up, include=TRUE}
PathStarter="Z:/"

LatMMSDFN  <-  paste0(PathStarter,"COVID-19_WastewaterAnalysis/data/raw/MMSD_Cases.csv")
LatSpringDormFN  <-  paste0(PathStarter,"COVID-19_WastewaterAnalysis/data/raw/SpringSemester_CasesByDorm.TSV")
LatFallDormFN  <-  paste0(PathStarter,"COVID-19_WastewaterAnalysis/data/raw/FallSemester_CasesByDorm.TSV")

LIMSFN <- paste0(PathStarter,"COVID-19_WastewaterAnalysis/data/raw/WATERMICRO_WW_COVID-2021-06-30 17 40.xlsx")

HFGCasesFN  <-  paste0(PathStarter,"COVID-19_WastewaterAnalysis/data/raw/HighFreq_CaseData_2021-05-07.csv")


LatCaseDF <- CovidDataPARSER(LatSpringDormFN,LatFallDormFN,MMSDFN = LatMMSDFN)%>%
  filter(!is.na(Site))%>%
  select(Date,Site,Cases,Tests,Per_pos)

HFGCaseDF <- HFGCasesPARSER(FN = HFGCasesFN)%>%
  filter(!is.na(Site))%>%
  mutate(Tests=NA,Per_pos=NA)%>%
  select(Date,Site,Cases=ReportedCases,Tests,Per_pos)%>%
  mutate(Cases = ifelse(Cases==-999,2.5,Cases))%>%
  filter(Site!="Madison")

FullCase <- rbind(HFGCaseDF,LatCaseDF)

FullCaseRoll <- RollPerPos(FullCase,"Cases","Tests",Facet="Site",n = 14)

LIMSFullDF <- LIMSDataPARSER(LIMSFN)%>%
  select(Date,Site, BCoV, N1,N1Error,N2, N2Error,PMMoV,Pop,FlowRate)

CaseSum=FullCase%>%
  filter(!is.na(Cases))%>%
  group_by(Site)%>%
  summarise(NCase=n())

N1Sum=LIMSFullDF%>%
  filter(!is.na(N1))%>%
  group_by(Site)%>%
  summarise(NN1=n())

DataComp <- inner_join(CaseSum,N1Sum,by=c("Site"))%>%
  mutate(Dif=NCase-NN1,min=ifelse(NCase<NN1,NCase,NN1))
LowCaseDataPoints <- DataComp%>%
  filter(Dif<0)

```




 
```{r Ploting Fnc, include=FALSE} 
#library(dynlm)

IsFull <- function(DF){
  return(length(DF$Date)==max(DF$Date)-min(DF$Date)+1)
}


```

```{r Madison Prep, fig.height=3,include=FALSE}
MergedDF <- BestCorDFGen("Madison")
```

```{r}
#TODO:collection date
#.0131


MethodPlot <- function(DF){
  
  DF2 <- DF
  DF2$RobMod <- fitted.values(robets((DF$"N1Filtered"),
                           alpha=.0131,model="AAN"))
  
  DF2 <- DF2%>%
    filter(!is.na(Cases2))
  
  plot(DF2$RobMod,type="l",yaxt='n', ann=FALSE)
  par(new = TRUE)
  plot((DF2$"Cases2"),col="Red",type="l",yaxt='n', ann=FALSE)
  par(new = TRUE)
  plot((zoo::rollapply(data=DF2$"N1Filtered",
                      width=35,FUN=mean,align="right",fill=NA)),
       col="Green",type="l",yaxt='n', ann=FALSE)
  par(new = TRUE)
  plot((zoo::rollapply(data=DF2$"N1Filtered",
                      width=3,FUN=median,align="center",fill=NA)),
       col="Blue",type="l",yaxt='n', ann=FALSE)
  par(new = TRUE)
  plot((DF2$"LoessN1"),col="pink",type="l",yaxt='n', ann=FALSE)
  legend(x="topright", legend=c("SLD Cases","Robust ES","35 day MA","3 day meadian N1","loess"),fill=c("Red","Black","Green","Blue","pink"),cex=.75)
  title(unique(DF2$Site))
}
MethodPlot(MergedDF)
```


```{r Dorm}
Intercepters <- c("MMSD-P7" ,"MMSD-P2" ,               
"MMSD-P8","MMSD-P11",                
"MMSD-P18")

IntercepterDFList <- lapply(Intercepters,BestCorDFGen,DateFilt=mdy("2/1/2021"))

lapply(IntercepterDFList,MethodPlot)
#Slide Madison->interceptors
#investigate p18
#good sanity check
```

```{r All Sites}
Sites <- c("Hudson","Kenosha","Oshkosh","River Falls","Sun Prairie","Wausau")

SitesDFList <- lapply(Sites,BestCorDFGen,DateFilt=mdy("10/1/2020"))

lapply(SitesDFList,MethodPlot)
```
}
