---
params:
  BaseDir: "Z:/"
  ##BaseDir: "/Volumes/byandell/"
title: "TSBestCorrelation"
author: "Marlin"
date: "7/22/2021"
output:
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: inline
---

```{r set up markdown settings, echo=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)

```

```{r Start enviroment, message=FALSE, warning=FALSE}
library(ggpubr)
library(forecast)
library(lmtest)
library(lubridate)
library(limma)
library(zoo)
library(dplyr)
library(robets)

#Data Files and prep work
source("../../lib/GenPlotMaking.R")
source("../../lib/WastewaterDataProccess.R")
source("../../lib/CasesDataProccess.R")
source("../../lib/HelperFunctions.R")
library(readxl)
```

```{r DF Set Up, include=TRUE}
BaseDir <- params$BaseDir

LatMMSDFN  <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/MMSD_Cases.csv")
LatSpringDormFN  <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/SpringSemester_CasesByDorm.TSV")
LatFallDormFN  <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/FallSemester_CasesByDorm.TSV")

LIMSFN <- paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/WATERMICRO_WW_COVID-2021-06-30 17 40.xlsx")

HFGCasesFN  <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/HighFreq_CaseData_2021-05-07.csv")


LatCaseDF <- CovidDataPARSER(LatSpringDormFN,LatFallDormFN,MMSDFN = LatMMSDFN)%>%
  filter(!is.na(Site))%>%
  select(Date,Site,Cases,Tests,Per_pos)

HFGCaseDF <- HFGCasesPARSER(FN = HFGCasesFN)%>%
  filter(!is.na(Site))%>%
  mutate(Tests=NA,Per_pos=NA)%>%
  select(Date,Site,Cases=ReportedCases,Tests,Per_pos)%>%
  mutate(Cases = ifelse(Cases==-999,2.5,Cases))%>%
  filter(Site!="Madison")

FullCase <- rbind(HFGCaseDF,LatCaseDF)

FullCaseRoll <- RollPerPos(FullCase,"Cases","Tests",Facet="Site",n = 14)

LIMSFullDF <- LIMSDataPARSER(LIMSFN)%>%
  select(Date,Site, BCoV, N1,N1Error,N2, N2Error,PMMoV,Pop,FlowRate)
```

```{r Madison Prep, fig.height=3,include=FALSE}
#MergedDF <- BestCorDFGen("Madison",FullCase,LIMSFullDF)
Site="Madison"
Rolling="Cases"

SiteLimsDF <- DataPrep(LIMSFullDF,
                         keep=c("N1","N2"),
                       Site=Site)

  
  SCPDF <- DFSmoothingFNC(FullCase,Site=Site,Rolling=Rolling)%>%
    mutate(Site=Site)
  
  SCPDF2 <- DFSmoothingFNC(FullCase,PreRoll=TRUE,Site=Site,Rolling=Rolling)%>%
    mutate(Site=Site)
  
  SCPDF3 <- inner_join(SCPDF,SCPDF2,by=c("Date","Site",Rolling),suffix=c("",".PreRolled"))
  
  MergedDF <- full_join(SCPDF3,SiteLimsDF, by=c("Date","Site"))
  
  MergedDF <- MergedDF%>%
    filter(Date>mdy("9/15/2020"))%>%
    select(Date,Site,Cases,SLDCases,SLDCases.PreRolled,N1,N2)
```


```{r Best Fit of N1 and SLD}
#TODO:collection date
#.0131
MergedDF <- MergedDF%>%
  filter(Site=="Madison")

RobMod <- c(fitted.values(robets(MergedDF$N1,
                           alpha=.0131,model="AAN"))[31:282],rep(NA,30))
MAMod <- c(zoo::rollapply(data=MergedDF$N1,
                    width=35,FUN=mean,align="right",fill=NA)[31:282],
           rep(NA,30))

LoessMod <- c(MergedDF$LoessN1[16:282],
           rep(NA,15))
CaseMod <- MergedDF$SLDCases


plot(RobMod,type="l",yaxt='n', ann=FALSE)
par(new = TRUE)
plot((CaseMod),col="Red",type="l",yaxt='n', ann=FALSE)
par(new = TRUE)
#plot((MAMod),
#     col="Green",type="l",yaxt='n', ann=FALSE)
#par(new = TRUE)
#plot((zoo::rollapply(data=MergedDF$N1Filtered,
#                    width=3,FUN=median,align="center",fill=NA)),
#     col="Blue",type="l",yaxt='n', ann=FALSE)
#par(new = TRUE)
#plot((LoessMod),col="pink",type="l",yaxt='n', ann=FALSE)
#legend(x="topright", legend=c("Robust ES","SLD Cases","35 day MA","3 day meadian N1","loess"),fill=c("Black","Red","Green","Blue","pink"))
#robust ES with offset 30 fits cases best

plot(diff(MergedDF$SLDCases),col="Red",type="l")
par(new = TRUE)
plot(diff(RobMod),type="l")




```



```{r Madison Prep, fig.height=3,include=FALSE}
Intercepters <- c("MMSD-P7" ,"MMSD-P2" ,               
"MMSD-P8","MMSD-P11",                
"MMSD-P18")

IntercepterDFList <- lapply(Intercepters,BestCorDFGen)
```
