---
params:
  BaseDir: "Z:/"
  ##weights: "Default"
  weights: "Default"
  ##BaseDir: "/Volumes/byandell/"
title: "SheddingLagDistribution"
author: "Marlin"
date: "7/22/2021"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_file = "./test/output/SheddingLagDistribution01.Sin.html", params = "ask")})
editor_options:
  chunk_output_type: inline
---



```{r set up markdown settings, echo=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r Start enviroment, message=FALSE, warning=FALSE}
library(ggpubr)
library(forecast)
library(lmtest)
library(lubridate)
library(limma)
library(zoo)
library(dplyr)
library(readxl)

#Data Files and prep work
source("../../../lib/GenPlotMaking.R")
#source("../../../lib/WasteWaterDataProccess.R")
#source("../../../lib/CasesDataProccess.R")
source("../../../lib/DataProccess.R")
source("../../../lib/HelperFunctions.R")

```

```{r DF Set Up, include=TRUE}
BaseDir <- params$BaseDir

MadisonCaseFN  <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/processed/MMSD_Cases_processed.csv")
LIMSFN <- paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/processed/LIMSWasteData_2021-06-30_17-40.csv")

LatCaseDF <- ParseData(MadisonCaseFN)%>% 
  filter(!is.na(Site)) %>%
  select(Date,Site,Cases,Tests,Per_pos)

LatCaseDFRoll <- RollPerPos(LatCaseDF,"Cases","Tests",Facet="Site",n = 14)

FullLatCaseDFRoll <- full_join(LatCaseDF,LatCaseDFRoll,by=c("Date","Site"),suffix=c("",".Rolled"))

LIMSFullDF <- ParseData(LIMSFN)%>%
  select(Date,Site, BCoV, N1,N1Error,N2, N2Error,PMMoV,Pop,FlowRate)
```

```{r}
#5.028338
scale =5.028338
#2.332779
shape =2.332779

weights <- dgamma(1:21,scale = scale,shape = shape)
if(params$weights!="Default"){
  weights <- eval(parse(text=params$weights))
}
```



```{r CaseSmoothing, include=TRUE}

if(params$weights=="Default"){
  plot(weights, 
            main=paste("Gamma Distribution with mean = 11.73 days, and SD = 7.68"),
            ylab = "Weight",
            xlab = "Lag")


  plot(c(rep(0,10),weights[11:21]), 
            main="Gamma Distribution with mean = 11.73 days, and SD = 7.68",
            ylab = "Weight",
            xlab = "Lag")
}else{
  plot(weights, 
            main=paste("Chosen weights"),
            ylab = "Weight",
            xlab = "Lag")
}
```


```{r SLD Case comp}
SLDDF <- SLDSmoothing(FullLatCaseDFRoll,"Cases",Weights=weights)%>%
  filter(Site %in% c("Madison"))
SLDDF%>%
  ggplot(aes(x=Date))+
  geom_point(aes(y=Cases,color="Cases"))+
  geom_point(aes(y=Cases.Rolled,color="Cases.Rolled"))+
  geom_point(aes(y=SLDCases,color="SLDCases"))+
  facet_wrap(~Site)
```

```{r SLD Case N1 comp}
MinMaxNormal <- function(Vec){
  #print((1-min(Vec,na.rm=TRUE)/(max(Vec,na.rm=TRUE)-min(Vec,na.rm=TRUE))))
  
  Val=(Vec-min(Vec,na.rm=TRUE))/(max(Vec,na.rm=TRUE)-min(Vec,na.rm=TRUE))
  return(Val)
}

Medianmean <- function(Vec,Nremoved=2){
  OrderedVec <- sort(Vec)
  if((length(Vec)-length(OrderedVec))>=2*Nremoved){
    return(mean(OrderedVec,na.rm=TRUE))
  }
  ReducedVec <- OrderedVec[(1+Nremoved):(length(OrderedVec)-Nremoved)]
  return(mean(ReducedVec,na.rm=TRUE))
}


SLDN1DF <- full_join(SLDDF,LIMSFullDF)%>%
  filter(Site=="Madison")%>%
  mutate(N1Roll=c(rep(NA,8),rollapply(N1,width=9,FUN=Medianmean)))
SLDN1DF$LoessN1 <- DFLoessFNC(SLDN1DF,Var="N1Roll",span=.15)

SLDN1DF%>%
  ggplot(aes(x=Date))+
  geom_point(aes(y=MinMaxNormal(Cases),color="Cases.Rolled"))+
  geom_point(aes(y=MinMaxNormal(SLDCases),color="SLDCases"))+
  geom_point(aes(y=MinMaxNormal(LoessN1),color="LoessN1"))+
  facet_wrap(~Site)
```

```{r}
TSSLDN1 <- SLDN1DF%>%
  tidyr::fill(everything(), .direction = "down")%>%
  filter(!is.na(Cases),!is.na(SLDCases),!is.na(LoessN1))


TSDF <- ts(TSSLDN1,start = 18520)
CasesTS <- TSDF[,3]
SLDCasesTS <- TSDF[,9]
N1TS <- TSDF[,11]
LoessN1TS <- TSDF[,19]

par(mfrow=c(2,2))
ccf(CasesTS,N1TS)
ccf(SLDCasesTS,N1TS)
ccf(CasesTS,LoessN1TS)
ccf(SLDCasesTS,LoessN1TS)
par(mfrow=c(1,1))
ts.plot(MinMaxNormal(SLDCasesTS),MinMaxNormal(LoessN1TS))
```
```{r diff ccf,eval=FALSE,echo=FALSE}
par(mfrow=c(2,2))
ccf(diff((CasesTS)),diff(N1TS))
ccf(diff((CasesTS)),diff(LoessN1TS))
ccf(diff((SLDCasesTS)),diff(N1TS))
ccf(diff((SLDCasesTS)),diff(LoessN1TS))
par(mfrow=c(1,1))
ts.plot(MinMaxNormal(diff((SLDCasesTS))),MinMaxNormal(diff(LoessN1TS)))
```


```{r VARMA,eval=FALSE,echo=FALSE}
library(MTS)
Fit <- VARMA(cbind(CasesTS,N1TS),p=5,q=1)
  Eccm(cbind(CasesTS,N1TS))

plot.ts(VARMApred(Fit, h = 5, orig = 0)$pred,)

```


