
---
title: "DHS analysis compering the base analysis to outlier Filtering"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{DHS analysis compering the base analysis to outlier Filtering}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r load packages}
library(DSIWasteWater)
library(dplyr)
```


```{r create worksheet4}
data(Data_wastewater, package = "DSIWasteWater")

#TODO abstract saved data -> workset4? save workset4 instead?
#Filter number of sites for faster kniting time?

df <- Data_wastewater

## format data as DHS code expects
df <- df %>% 
  select(
    wwtp_name,sample_collect_date,population_served,  ## site data
    n1_sars_cov2_conc, n2_sars_cov2_conc,             ## N1, N2 measurement
    average_flow_rate                                 ## sample covariates
  ) %>% 
  rename(WWTP = wwtp_name, date = sample_collect_date) %>% 
  mutate(date = as.Date(date,format="%m/%d/%Y"))

### Note: Replacement small values with LOD/2 (as per 5/20/2022 discussion w/DHS)
##   in bin/cleanData.pl

## dependent regression variable: log of normalized average SARS-COV-2 level
workset4 <- df %>% 
  filter(average_flow_rate != "NA") %>% 
  mutate (geoMean = sqrt(n1_sars_cov2_conc*n2_sars_cov2_conc)) %>% 
  mutate(sars_cov2_adj_load_log10 = log10(
    geoMean*average_flow_rate/population_served    
  )
  )


## filter out sites with too few measurements
##  and sort by date;
workset4 <- workset4 %>% 
  group_by(WWTP) %>% 
  mutate(n = n()) %>% 
  arrange(date, .by_group = TRUE) %>% 
  ungroup %>% 
  filter(n >= 5)
```

```{r flag outlier}

df <- computeJumps(workset4)
df.ranked <- rankJumps(df)
df.ranked.quantile <- computeRankQuantiles(df.ranked)
df.classied <- flagOutliers(df.ranked.quantile, 9)
df.created <- RemoveOutlier(df.classied)

```

```{r run package code}

reg_estimates <- DHSTopLevelAnalysis(df.created, 
                                     c("sars_cov2_adj_load_log10",
                                     "sars_adj_log10_Filtered")
                                    )
head(reg_estimates)
```


```{r temp explore}

ConfMatrix(reg_estimates, "Catagory", "sars_cov2_adj_load_log10", "sars_adj_log10_Filtered")


reg_estimates%>%
  group_by(Method,Catagory)%>%
  summarise(n = n())%>%
  ggplot(aes(x=Catagory,y=n))+
           geom_col(aes(fill=Method),position = "dodge")+ 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

```{r make DHS plot, fig.height=5,fig.width=316}
#TODO restructure so it can accept 2 point vars
#underlying function can already do this, just not the wrapper
DHSTopLevelPlots(reg_estimates, df.created, 
                 PointVal = c("sars_cov2_adj_load_log10", "sars_adj_log10_Filtered"))
```