---
title: "case_flags"
author: "Marlin"
date: '2022-07-27'
output: pdf_document
editor_options: 
  chunk_output_type: inline
---


```{r set up markdown settings, echo=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	echo = FALSE
)
```

```{r assemble case dataframe}
#TODO
#get all data frames to have the same names
#Separate classification from regression
#quantile 
#
#code for Case flag
#code for waste flag
#how to best explore the relationship

library(ggplot2)
```

```{r create case data in right format}
library(DSIWastewater)
data(Case_data, package = "DSIWastewater")

Case_DF <- buildCaseAnalysisDF(Case_data)

Case_DF <- Case_DF[Case_DF$Site == "Madison",]

Case_DF <- Case_DF[Case_DF$date  >= as.Date("2021-02-01"),]

```

```{r create case flags}

#add pipe level comments
#break up pipes?
#create case flags
#add tokeep parameter
#current process:

#prep -> regression -> classification

#get 7 day slope of data
CaseFlagOutput <- buildRegressionEstimateTable(DataMod = Case_DF,
                             RunOn = "FirstConfirmed.Per100K",
                             SplitOn = "Site",
                             DaysRegressed = 7,
                             PSigTest = FALSE)

CaseFlagOutput <- ClassifyCaseRegression(CaseFlagOutput)
```


```{r waste flags}

WindowingQuantFunc <- function(DF, column){
  mindate <- min(DF$date)
  maxdate <- max(DF$date)
  FuncWindow <- min(DF$window, na.rm = TRUE)
  FuncQuant <- min(DF$quant, na.rm = TRUE)
  dateTOMERGEVec <- data.frame(date = seq(mindate, maxdate, 1),
                               WWTP = unique(DF$WWTP),
                               window = FuncWindow,
                               quant = FuncQuant)
  K = 3
  RetDF <- full_join(DF, dateTOMERGEVec)%>%
    arrange(date)%>%
    mutate(ntile = rollapply(!!sym(column), 
                              width = FuncWindow,
                             FUN = quantile, 
                              probs  = FuncQuant,
                             align = "right", 
                              na.rm=T, fill=NA, 
                              names = FALSE),
           pastKavg.wwlog10 = rollmean(!!sym(column),
                                       K, align = "right",
                                       na.pad = T,
                                       na.rm=T))%>%
    filter(!is.na(population_served))
  return(RetDF)
}

MakeQuantileColumns <- function(DF, column, quants, windows){
  Method_DF <- expand.grid(windows, 
                         quants, 
                         unique(DF$WWTP))

  colnames(Method_DF) <- c("window", "quant", "WWTP")

  Quantiles_DF <- left_join(DF,Method_DF)%>%
    split(Quantiles_DF, ~WWTP+window+quant)%>%
    lapply(Quantiles_DF_list, WindowingQuantFunc,
                              column = column)%>%
    bind_rows(Quantiles_DF_list)
  return(Quantiles_DF)
}

ClassifyQuantileFlagRegression <- function(DF){
  DF%>%
    mutate(cdc_flag = case_when(Catagory == "major increase"~ 1,
                              TRUE ~ 0),
         flag_ntile = case_when(
           pastKavg.wwlog10 > ntile & cdc_flag ~ 1,
                              TRUE ~ 0),
         flag_ntile_pval = case_when(
           flag_ntile & lmreg_sig < pval ~ 1,
                              TRUE ~ 0))%>%
  mutate(across(where(is.numeric), ~ ifelse(is.na(.x), 0, .x)))
}
```

  
```{r}
data(WasteWater_data, package = "DSIWastewater")

baseWaste_data <- buildWasteAnalysisDF(WasteWater_data)

baseWaste_data <- baseWaste_data[
  baseWaste_data$date  >= as.Date("2021-02-01"),]

baseWaste_data <- baseWaste_data[
  baseWaste_data$WWTP == "Madison MSD WWTF",]

windows <- c(14, 30, 60 , 90)
quants <- c(5:9)/10

Quantiles_DF <- MakeQuantileColumns(baseWaste_data,
                                    "sars_cov2_adj_load_log10",
                                    quants, windows)

Quantiles_DF <- select(Quantiles_DF, WWTP, date, pastKavg.wwlog10,
                       window, quant, ntile)


CDCMethod <- buildRegressionEstimateTable(baseWaste_data,
                                          PSigTest=FALSE)

CDCMethod <- select(CDCMethod, WWTP, date,lmreg_sig,  Catagory)

pval = .3

FULL_reg_DF <- full_join(Quantiles_DF, CDCMethod,
                         by = c("WWTP", "date"))

FULL_reg_DF <- ClassifyQuantileFlagRegression(FULL_reg_DF)
```



```{r Merge flag data frames}
CaseFlags <- rename(CaseFlagOutput, WWTP = Site)
  
CaseFlags <- select(CaseFlags, WWTP, date, case_flag,
                    case_flag_plus_comm.threshold, slope_switch_flag)

Full_wasteFlags <- mutate(FULL_reg_DF,
                          WWTP = ifelse(
                            WWTP == "Madison MSD WWTF",
                            "Madison",WWTP))
  
Full_wasteFlags <- select(Full_wasteFlags, WWTP, date, window,
                          quant, cdc_flag, flag_ntile,
                          flag_ntile_pval)

Full_Flag_DF <- inner_join(Full_wasteFlags, CaseFlags,
                           by = c("WWTP", "date"))
Full_Flag_DF
```

```{r plot case and waste flags}
A <- Case_DF%>%
  ggplot(aes(x = date))+
  geom_point(aes(y=FirstConfirmed.Per100K), size = .5) +
  geom_vline(aes(xintercept = date, color = "Case flag"),
             data = filter(Full_Flag_DF, slope_switch_flag==1, 
                           quant == .8, window == 90, flag_ntile == 0))+
  geom_vline(aes(xintercept = date, color = "Waste flag"),
             data = filter(Full_Flag_DF, slope_switch_flag==0, 
                           quant == .8, window == 90, flag_ntile == 1))+
  geom_vline(aes(xintercept = date, color = "Both"),
             data = filter(Full_Flag_DF, slope_switch_flag==1, 
                           quant == .8, window == 90, flag_ntile == 1))+
  ylab("Case data") +
  ggtitle("Case data with slope_switch flags")+
  scale_y_continuous(limits = c(0, 700))+
  scale_y_log10()

B <- baseWaste_data%>%
  ggplot(aes(x = date))+
  geom_point(aes(y=sars_cov2_adj_load_log10), size = .5) +
  geom_vline(aes(xintercept = date, color = "Case flag"),
             data = filter(Full_Flag_DF, slope_switch_flag==1, 
                           quant == .8, window == 90, flag_ntile == 0))+
  geom_vline(aes(xintercept = date, color = "Waste flag"),
             data = filter(Full_Flag_DF, slope_switch_flag==0, 
                           quant == .8, window == 90, flag_ntile == 1))+
  geom_vline(aes(xintercept = date, color = "Both"),
             data = filter(Full_Flag_DF, slope_switch_flag==1, 
                           quant == .8, window == 90, flag_ntile == 1))+
  ylab("WasteData")#+
  #scale_y_log10()
patchwork::wrap_plots(A,B, ncol = 1)
```


```{r shiny view of the problem, eval = FALSE}
#in package
#createCaseflag
#createWasteflag
#call common regression code
#wastedata/some smoothing of waste data
#how well does the case flags/waste flags work
#for madison for state
#how well do they do, at predicting own goals, each other


library(shiny)
windows <- c(14, 30, 60 , 90)
quants <- c(5:9)/10
ui <- fluidPage(
    selectInput(inputId = "Window", 
              label = "choose Wastewater Window", 
              choices = windows,
              selected = 90),
    selectInput(inputId = "quants", 
              label = "choose Wastewater quants", 
              choices = quants,
              selected = .8),
    dateRangeInput("daterange", "Select date range:", start = min(Full_Flag_DF$date), end = max(Full_Flag_DF$date), min = min(Full_Flag_DF$date), max = max(Full_Flag_DF$date), startview = "year"),
  plotOutput(outputId = "Flag_Compare_plot", width="100%")#, height="")

)

server <- function(input, output, session) {
  
  output$Flag_Compare_plot <- renderPlot({
    A <- Case_DF%>%
      filter(date >= input$daterange[1] & date <= input$daterange[2])%>% #filter using date range
  ggplot(aes(x = date))+
  geom_point(aes(y=FirstConfirmed.Per100K), size = .5) +
  geom_vline(aes(xintercept = date, color = "Case flag"),
             data = filter(Full_Flag_DF, slope_switch_flag==1, 
                           quant == input$quants, window == input$Window, flag_ntile == 0))+
  geom_vline(aes(xintercept = date, color = "Waste flag"),
             data = filter(Full_Flag_DF, slope_switch_flag==0, 
                           quant == input$quants, window == input$Window, flag_ntile == 1))+
  geom_vline(aes(xintercept = date, color = "Both"),
             data = filter(Full_Flag_DF, slope_switch_flag==1, 
                           quant == input$quants, window == input$Window, flag_ntile == 1))+
  ylab("Case data") +
  ggtitle("Case data with slope_switch flags")+
  scale_y_continuous(limits = c(0, 700))+
  scale_y_log10()

B <- baseWaste_data%>%
  filter(date >= input$daterange[1] & date <= input$daterange[2])%>% #filter using date range
  ggplot(aes(x = date))+
  geom_point(aes(y=sars_cov2_adj_load_log10), size = .5) +
  geom_vline(aes(xintercept = date, color = "Case flag"),
             data = filter(Full_Flag_DF, slope_switch_flag==1, 
                           quant == input$quants, window == input$Window, flag_ntile == 0))+
  geom_vline(aes(xintercept = date, color = "Waste flag"),
             data = filter(Full_Flag_DF, slope_switch_flag==0, 
                           quant == input$quants, window == input$Window, flag_ntile == 1))+
  geom_vline(aes(xintercept = date, color = "Both"),
             data = filter(Full_Flag_DF, slope_switch_flag==1, 
                           quant == input$quants, window == input$Window, flag_ntile == 1))+
  ylab("WasteData")#+
  #scale_y_log10()
patchwork::wrap_plots(A,B, ncol = 1)
  })
}

shinyApp(ui = ui, server = server)


```