---
title: "DHSAnalysisCaseCompare"
author: "Marlin"
date: "5/30/2022"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(limma)
library(tidyr)
library(patchwork)
library(zoo)
```



```{r Set up DFs}


DHSAnalysisResults <- read.csv("results_table.csv")%>%
  mutate(date = as.Date(date))%>%
  rename(Date = date, Site = WWTP)%>%
  group_by(Site)%>%
  filter(n() > 800)

DHSCaseData <- read.csv("../../data/processed/DHSCaseData-4_21_2022.csv")%>%
  group_by(Site)%>%
  arrange(Date)%>%
  mutate(Date = as.Date(Date),
         SevenDayMACases = rollapply(data = FirstConfirmed, width = 7, FUN = mean, 
                                       partial = TRUE))%>%
  mutate(Site = ifelse(Site=="Madison","Madison MSD WWTF",Site))
```



```{r, fig.width=12}
Cat.map <- c("major increase" = 2, "moderate increase" = 1, 
              "fluctuating" = 0, "no change" = 0,
              "moderate decrease" = -1, "major decrease" = -2)    

Full_DF <- full_join(DHSAnalysisResults, DHSCaseData, by = c("Date", "Site"))%>%
  mutate(Cat = Cat.map[Catagory])


sameLengthPerChange <- function(x, lag = 1){
  
  n = length(x)
  if(n <= lag){return(rep(NA, n))}
  Lx = x[(1+lag):n]
  Rx = x[1:(n-lag)]
  PerChange = (Lx-Rx)/Rx
  return(c(rep(NA, lag), PerChange))
         
}

CompareFunc <- function(lag , DF, CaseVar){
  
  if(nrow(DF)>lag){
  
    DF <- DF%>%
      arrange(Date)%>%
      mutate(LagCases = sameLengthPerChange(SevenDayMACases, lag = lag),
           LagCases_Cat = cut(LagCases, c(-Inf, 0, Inf),
                          labels =FALSE))
    
    
  
    try({
      Dist = paste(unique(DF$Site) , unique(DF$Method))
      RSeq <- summary(lm(LagCases_Cat ~ Cat, data = DF))$r.squared
      RetDF <- data.frame(Site = unique(DF$Site),
                        Method = unique(DF$Method),
                        lag = lag,
                        Effect = RSeq )
      
        return(RetDF)
       })
  }
      RetDF <- data.frame(Site = unique(DF$Site),
                      Method = unique(DF$Method),
                      lag = lag,
                      Effect = NA)
      return(RetDF)
}


MultiNFunc <- function(DF, lag, Inter = 1){
  UsedSeq <- (1:floor(lag/Inter))*Inter
  RetDF <- lapply(UsedSeq, CompareFunc, DF)%>%
    bind_rows()
  return(RetDF)
}

ResultDF <- Full_DF%>%
  filter(!is.na(Method))%>%
  group_by(Site, Method)%>%
  group_split()%>%
  lapply(MultiNFunc, 42)%>%
  bind_rows()


SavePlot <- ResultDF%>%
  ggplot(aes(x = lag, y = Effect, color = Method))+
  geom_line()+
  facet_wrap(~Site)


Dim = length(unique(ResultDF$Site))

ggsave("SevenDayMACasesLinePlot.PDF",plot = SavePlot,
         width = 8*floor(sqrt(Dim)), height = 5*ceiling(sqrt(Dim)),units="cm",limitsize =FALSE)
```



