---
title: "EXP_Smoothing"
author: "Marlin"
date: '2022-07-08'
output: html_document
---

```{r load packages}
library(DSIWastewater)
```

```{r exp}
ParameterGuess <- function(DF,InVar, Base, max){
  temp <- DF%>%
    filter(!is.na((!!sym(InVar))))%>%
    summarise(n=n())
  span <- min(c(Base/temp$n, max))#More can be done here
  return(span)
}

ExpSmoothMod <- function(DF,InVar="sars_cov2_adj_load_log10",
                         OutVar="EXP",alpha="guess",beta="guess",
                         Filter = NULL ){
  
  if(alpha=="guess"){
    alpha <- ParameterGuess(DF,InVar, 35.6, .4)
  }
  if(beta=="guess"){
    beta <- ParameterGuess(DF,InVar, 8.9, .4)
  }
  if(!is.null(Filter)){
    OutDF <- DF%>%
      filter((!!sym(Filter)) | is.na(!!sym(InVar)))%>%
      mutate(!!OutVar := NA)
    
    DF <- DF%>%
      filter(!(!!sym(Filter))  & !is.na(!!sym(InVar)))
  }else{
    OutDF <- DF%>%
      filter(is.na(!!sym(InVar)))%>%
      mutate(!!OutVar := NA)
    
    DF <- DF%>%
      filter(!is.na(!!sym(InVar)))
  }
  
  DF <- DF%>%
    arrange(date)
  
  DF[[OutVar]] <- robets::robets(y=DF[[InVar]],
                          model = "AAN",
                          beta  = beta,
                          alpha=alpha)$fitted#2 iterations remove some bad patterns
  DF <- DF%>%
    bind_rows(OutDF)
  
  return(DF)
}
```

```{r create worksheet4}
data(wastewater_data, package = "DSIWastewater")

workset4_data <- buildWorkSheet4(wastewater_data)

#Only show Site with more than 180 measurements for vignette for brevity
workset4_data <- workset4_data[workset4_data$n >= 180,]
workset4_data <- workset4_data[workset4_data$WWTP == "Madison MSD WWTF",]


workset4_Smooth_data <- do.call(rbind,
                              lapply(
                                split(workset4_data,~WWTP),
                                LoessSmoothMod))

workset4_Smooth_data <- do.call(rbind,
                              lapply(
                                split(workset4_Smooth_data,~WWTP),
                                ExpSmoothMod))


```

```{r run regression analysis}
reg_estimates_data <- buildRegressionEstimateTable(workset4_Smooth_data,
                               RunOn = c("sars_cov2_adj_load_log10",
                                "EXP",
                                "Loess"))
head(reg_estimates_data)
```


```{r Compare methods,fig.width=6, eval = FALSE}

createConfMatrix_Plot(reg_estimates_data, 
                      "sars_cov2_adj_load_log10",
                      "Loess")
createConfMatrix_Plot(reg_estimates_data, 
                      "Loess",
                      "EXP")

createMethodCompareBar_Plot(reg_estimates_data)
```

```{r make DHS plot, fig.height=15,fig.width=14.25, warning = FALSE}
createDHSMethod_Plot(reg_estimates_data, workset4_Smooth_data, 
                 PointVal = c( "sars_cov2_adj_load_log10"),
                 LineVal = c("Loess","EXP"))
```