---
title: "FullDFSiteAnalysis"
author: "Marlin"
date: "5/5/2022"
output:
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Prep Data}

#?add parm script functionality
BaseDir <- "./../../"
#Var1 <- ""

library(dplyr)
library(ggplot2)
library(limma)
library(tidyr)
library(patchwork)
#Data Files and prep work
source("../../lib/DataPathName.R")#merged?
source("../../lib/DataProccess.R")
source("../../lib/TSTrendGen.R")
source("DHSAlgo.R")
library(zoo)

#Importing the waste water data
LIMSFullDF <- read.csv("../../../tempa/workset4.csv")%>%
  mutate(date = as.Date(date))


SiteDFList <- LIMSFullDF%>%
    rename(Date=date)%>%
    group_by(WWTP)%>%
    filter(n()>135)%>%
    group_split()


DataMod <- SiteDFList%>%
  lapply(LoessSmoothMod, "sars_cov2_adj_load_log10", "Loess", "guess")%>%
  lapply(ExpSmoothMod, "sars_cov2_adj_load_log10", "EXP")%>%
  lapply(sgolaySmoothMod, "sars_cov2_adj_load_log10", "sgolay")%>%
  bind_rows()%>%
    rename(date=Date)



LIMSFullDF%>%
  group_by(WWTP)%>%
  summarise(n = n())%>%
  arrange(n)
```


```{r AllSite Loop, Warning = FALSE}
LMfited <- c(as.formula("sars_cov2_adj_load_log10 ~ date"),
                                    as.formula("Loess ~ date"))#,
                                   # as.formula("EXP ~ date"),
                                   # as.formula("sgolay ~ date")

reg_estimates = DataMod%>%
                  OuterLoop(LMfited)

#reg_estimates2 = DataMod%>%
#                  OuterLoop(c(
#                    as.formula("sars_cov2_adj_load_log10 ~ date")),
#                    robust = TRUE)


# reg_estimates = rbind(reg_estimates1,reg_estimates2)%>%
#   mutate(Method = ifelse(LMmethod, "robust_cov2", Method))%>%
#   select(-LMmethod)%>%
#   mutate(Method = factor(Method,c("Loess","sgolay","EXP","robust_cov2","sars_cov2_adj_load_log10")))
StevesTable <- read.csv("../../../tempa/regressionTable.csv")

MarlinTable <- reg_estimates%>%
  filter(Method == "sars_cov2_adj_load_log10")%>%
  select(-LMmethod,-Catagory, -Method)%>%
  arrange(WWTP, date)

StevesTable <- read.csv("../../../tempa/regressionTable.csv")%>%
  filter(WWTP %in% unique(MarlinTable$WWTP))%>%
  arrange(WWTP, date)%>%
  mutate(date = as.Date(date))

identical(MarlinTable,StevesTable)
CompDF <- full_join(MarlinTable, StevesTable, by=c("date","WWTP"))



CompDF%>%
  mutate(DIF = abs(modeled_percentchange.x - modeled_percentchange.y))%>%
  summarise(SumDif = sum(DIF))

#modeled_percentchange: 2.523447e-09
#lmreg_slope: 6.105628e-13	
#lmreg_sig:  1.040768e-11	
```



```{r Edge Include, include = FALSE}
ModProFiltN <- function(n){
  reg_estimates%>%
  group_by(WWTP)%>%
  filter(n()>n)%>%
  ungroup()%>%
  mutate(WWTP = as.character(WWTP))%>%
  filter(WWTP != "Portage WWTF"  & WWTP != "Cedarburg WWTF")%>%
  mutate(Catagory = as.numeric(Catagory),
    Catagory = ifelse(Catagory == 6,3,Catagory))%>%
  select(WWTP,date,Method,Catagory)%>%
  pivot_wider(names_from = Method, values_from = Catagory)%>%
  mutate(EXPLoss = abs(EXP-Loess),
         sgolayLoss = abs(sgolay-Loess),
         BaseLoss = abs(sars_cov2_adj_load_log10 - Loess),
         RobustLoss = abs(robust_cov2-Loess))%>%
  summarise(EXPError = mean(EXPLoss),
            sgolayLoss = mean(sgolayLoss),
            BaseError = mean(BaseLoss),
            robustError = mean(RobustLoss,na.rm=TRUE))%>%
    mutate(n = n)
}

lapply((0:60)*10, ModProFiltN)%>%
  bind_rows()%>%
  ggplot(aes(x = n))+
  geom_line(aes(y = EXPError, color = "EXPError"))+
  geom_line(aes(y = BaseError, color = "BaseError"))+
  geom_line(aes(y = robustError, color = "robustError"))+
  geom_line(aes(y = robustError, color = "sgolayLoss"))


ConfMatrix <- function(DF,Cat,x,y){
  DF%>%
    filter(Method %in% c(x,y))%>%
    select(WWTP,date,Method,Catagory)%>%
    filter(WWTP != "Portage WWTF"  & WWTP != "Cedarburg WWTF")%>%
    pivot_wider(id_cols=c(WWTP,date),names_from = Method, values_from = !!sym(Cat))%>%
    group_by(!!sym(x),!!sym(y))%>%
    summarise(n = n())%>%
  filter(!is.na(!!sym(y)))%>%
  ggplot(aes(x=!!sym(x),y=!!sym(y)))+
  geom_tile(aes(fill = n))+
  scale_fill_gradient(low="blue", high="red")
}
ConfMatrix(reg_estimates,"Catagory","Loess","robust_cov2")+ 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
ConfMatrix(reg_estimates,"Catagory","Loess","sars_cov2_adj_load_log10")+ 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
ConfMatrix(reg_estimates,"Catagory","Loess","EXP")+ 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
ConfMatrix(reg_estimates,"Catagory","Loess","sgolay")+ 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

reg_estimates%>%
  group_by(Method,Catagory)%>%
  summarise(n = n())%>%
  ggplot(aes(x=Catagory,y=n))+
           geom_col(aes(fill=Method),position = "dodge")+ 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```

```{r MergePlot}

Dim = ceiling(length(unique(reg_estimates$WWTP))/4)

BarGridSmoothRaw <- CreateHeatMaps(reg_estimates, ToMerge=TRUE)
 
Gplt <- FactorVecByNumPoints(DataMod,"WWTP","EXP")%>%
  filter(WWTP %in% unique(reg_estimates$WWTP))%>%
  mutate(Data = "Data")%>%
  ggplot(aes(x=date))+
  geom_point(aes(y = sars_cov2_adj_load_log10), size = .5)+
  #geom_line(aes(y = EXP, color = "EXP"))+
  geom_line(aes(y = Loess, color = "Loess"))+
  #geom_line(aes(y = sgolay, color = "sgolay"))+
  facet_grid(Data~WWTP)+
  scale_x_date(date_labels = "%b %y") +
  theme(
  strip.background = element_blank(),
  strip.text.x = element_blank()
)

SavePlot <- BarGridSmoothRaw/Gplt + plot_layout(heights = c(2, 1))



ggsave("ClassCompare2.PDF",plot=SavePlot,
         width = 32*Dim,height = 15,units="cm",limitsize =FALSE)

```
