title: "Thresholding Exploration"
author: "Marlin"
date: "5/28/2021"
output:
  pdf_document: default
  html_document: default
---
```{r}

library(shiny)
library(ggpubr)
library(dplyr)
library(shinydashboard)
library(shinyjqui)
library(shinycssloaders)

#Data Files and prep work
source("../Scripts/GenPlotMaking.R")
source("../Scripts/WasteWaterDataProccess.R")
source("../Scripts/CassesDataProccess.R")
source("../Scripts/HelperFunctions.R")
LatWasteFN <- "../../UntrackedData/WW SARS-COV-2 Data V5.xlsx"
LatSpringCaseFN="../../UntrackedData/SpringSemester_CasesByDorm.tsv"
LatFallCaseFN="../../UntrackedData/FallSemester_CasesByDorm.tsv"
HFGWasteFN = "../../UntrackedData/HFG data for stats preliminary 3-18-21.xlsx"
HFGCaseFN="../../UntrackedData/HighFreq_CaseData_2021-05-07.csv"
LatMMSDFN = "../../UntrackedData/MMSD_Cases.2021-05-21.csv"
```

```{r}
HFGFrame=HFGInfo(HFGWasteFN)%>%
  select(Date,Site=Plant,Filter,Well,N1=N1GC,N2=N2GC,PMMoV=PMMOVGC,Pct_BCoV=BCoV,everything())%>%
  mutate(Filter=as.character(Filter),Well=as.character(Well))%>%
  mutate(Date=as.Date(Date))%>%
  na.omit()%>%
  rename(`Filter replicates`=Filter)


HFGCaseDF=HFGCasesPARSER(HFGCaseFN)
Fullday=data.frame(Date=seq.Date(min(HFGCaseDF$Date),max(HFGCaseDF$Date),1))
HFGCaseDF=full_join(HFGCaseDF,Fullday,by=c("Date"))

```

```{r}
HFGCaseDF2=HFGCaseDF%>%
      mutate(isna=ifelse(EpisodeCases==-999,"True","false"))%>%
      mutate(EpisodeCases=ifelse(EpisodeCases==-999,NA,EpisodeCases))%>%
      mutate(CollectedCases=ifelse(CollectedCases==-999,NA,CollectedCases))%>%
      mutate(ConfirmedCases=ifelse(ConfirmedCases==-999,NA,ConfirmedCases))

HFGCaseDFroll2=HFGCaseDF2%>%
      arrange(Site,Date)%>%
      group_by(Site)%>%
      mutate(CollectedCases=RollAvg(CollectedCases),EpisodeCases=RollAvg(EpisodeCases),ConfirmedCases=RollAvg(ConfirmedCases))%>%
      ungroup()%>%
      filter(!is.na(Site))
HFGFrame2=HFGFrame%>%
  group_by(Site,Date)%>%
  summarize(N1=median(N1),PMMoV=median(PMMoV),Pct_BCoV=median(Pct_BCoV))
```

```{r diffrent case datas, fig.height = 8, fig.width = 15}
HFGCaseDFroll2%>%
  ggplot()+aes(x=Date)+geom_point(aes(y=ConfirmedCases,x=Date-2,color="ConfirmedCases"))+
  geom_point(aes(y=CollectedCases,x=Date-1,color="CollectedCases"))+scale_x_date(limits=c(mdy("1/10/2021"),mdy("4/1/2021")))+
  facet_wrap(~Site,scales = "free")+geom_point(aes(y=EpisodeCases,color="EpisodeCases"))
#Site=="Wausau",
HFGCaseDFroll2%>%
  filter(!is.na(CollectedCases),!is.na(EpisodeCases),!is.na(ConfirmedCases))%>%
  ggplot()+aes(x=Date)+geom_point(aes(y=ConfirmedCases,x=Date,color="ConfirmedCases"),size=3)+
  geom_point(aes(y=CollectedCases,x=Date,color="CollectedCases"),size=3)+scale_x_date(limits=c(mdy("1/10/2021"),mdy("4/1/2021")))+
  facet_wrap(~Site,scales = "free")+geom_point(aes(y=EpisodeCases,color="EpisodeCases"),size=3)


HFGCaseDFroll2%>%
  filter(!is.na(EpisodeCases))
```



```{r Cases auto corrolation, fig.height = 8, fig.width = 15}
HFGCaseDFroll2%>%
  ggplot()+geom_point(aes(x=CollectedCases,y=ConfirmedCases,color=Site))+geom_abline(slope=1,intercept = 10,color="red")+
  geom_abline(slope=1,intercept = 0)+geom_abline(slope=1,intercept = -10,color="red")#+ scale_y_log10()+scale_x_log10()
HFGCaseDFroll2%>%
  ggplot()+aes(x=CollectedCases,y=EpisodeCases,color=Site)+geom_point()+geom_abline(slope=1,intercept = 10,color="red")+
  geom_abline(slope=1,intercept = 0)+geom_abline(slope=1,intercept = -10,color="red")
HFGCaseDFroll2%>%
  ggplot()+aes(x=ConfirmedCases,y=EpisodeCases,color=Site)+geom_point()+geom_abline(slope=1,intercept = 10,color="red")+
  geom_abline(slope=1,intercept = 0)+geom_abline(slope=1,intercept = -10,color="red")

```

```{r case self corilation shifting}
shiftedCor = function(vecter1,vector2,MaxNumShifted){
  goal=vector(length=2*MaxNumShifted+1)
    for(i in 1:MaxNumShifted){
    Cor1=c(rep(NA,MaxNumShifted-i+1),vector2)
    Cor2=c(vecter1,rep(NA,MaxNumShifted-i+1))
    goal[i]=cor(Cor1,Cor2,use="pairwise.complete.obs")
    }
  goal[MaxNumShifted+1]=cor(vecter1,vector2,use="pairwise.complete.obs")
  for(i in 1:MaxNumShifted){
    Cor1=c(rep(NA,i),vecter1)
    Cor2=c(vector2,rep(NA,i))
    goal[i+MaxNumShifted+1]=cor(Cor1,Cor2,use="pairwise.complete.obs")
  }
  return(goal)
}

DF=data.frame(shifted=-5:5)
DF$EpisodeCasesANDCollectedCases=shiftedCor(HFGCaseDFroll2$EpisodeCases,HFGCaseDFroll2$CollectedCases,5)
DF$EpisodeCasesANDConfirmedCases=shiftedCor(HFGCaseDFroll2$EpisodeCases,HFGCaseDFroll2$ConfirmedCases,5)
DF

```

```{r Weird values, fig.height = 6, fig.width = 13}
HFGFrame%>%
  filter(Site=="Madison")%>%
  mutate(marked=ifelse(PMMoV<1*10^7,"Low PMMoV","MAIN G"))%>%
  ggplot()+aes(x=PMMoV,y=N1,color=marked)+geom_point()+scale_y_log10()+
  scale_x_log10()+facet_wrap(~Site)

HFGFrame%>%
  filter(Site=="Madison")%>%
  mutate(marked=ifelse(PMMoV<1*10^7,"Low PMMoV","MAIN G"))%>%
  ggplot()+aes(x=Date,y=N1,color=marked)+geom_point()+
  scale_y_log10()+facet_wrap(~Site)


HFGFrame%>%
  filter(Site=="Kenosha")%>%
  mutate(marked=ifelse(PMMoV>5*10^7,"Large PMMoV","MAIN G"))%>%
  ggplot()+aes(x=PMMoV,y=N1,color=marked)+geom_point()+scale_y_log10()+
  scale_x_log10()+facet_wrap(~Site)

HFGFrame%>%
  filter(Site=="Kenosha")%>%
  mutate(marked=ifelse(PMMoV>5*10^7,"Large PMMoV","MAIN G"))%>%
  ggplot()+aes(x=Date,y=N1,color=marked)+geom_point()+
  scale_y_log10()+facet_wrap(~Site)

```


```{r Force fit, fig.height = 8, fig.width = 18, fig.align = "center"}
HFGCaseDFroll2=HFGCaseDF2%>%
      arrange(Site,Date)%>%
      group_by(Site)%>%
      mutate(CollectedCases2=RollAvg(CollectedCases),EpisodeCases2=RollAvg(EpisodeCases),ConfirmedCases2=RollAvg(ConfirmedCases))%>%
      ungroup()%>%
      filter(!is.na(Site))
N1Start=min(HFGFrame$Date)
N1End=max(HFGFrame$Date)
Start=mdy("1/1/2021")
End=mdy("4/1/2021")
shift=0
shift2=14
#print(paste("N1 leads by",shift,"Days"))
looking=c("Kenosha","Madison")
#"Kenosha","Madison","Wausau","Sun Prairie","Oshkosh"

#+geom_point(aes(x=Date+shift2),size=3,color="red",)+
#  geom_point(aes(x=Date-shift2),size=3,color="blue")


p1=HFGFrame2%>%
  #filter(N1<10e6)%>%
  filter(Site %in% looking)%>%
  group_by(Site)%>%
  #mutate(N1roll=RollAvg(N1,n=3))%>%
  ggplot()+aes(y=N1)+geom_point(aes(x=Date),size=2)+facet_wrap(~Site,nrow=1)+
  scale_x_date(limits=c(Start,End))+scale_y_log10()
p2=HFGCaseDFroll2%>%
  filter(Site %in% looking)%>%
  ggplot(aes(x=Date))+geom_point(aes(y=ConfirmedCases),size=2)+
  #scale_x_date(limits=c(start,end))+
  scale_x_date(limits=c(Start,End))+
  #geom_line(aes(y=ConfirmedCases2))+
  geom_vline(xintercept = N1Start+7,color="red")+
  geom_vline(xintercept = N1End+7,color="red")+
  geom_vline(xintercept = N1Start)+
  geom_vline(xintercept = N1End)+
  geom_vline(xintercept = N1Start-7,color="blue")+
  geom_vline(xintercept = N1End-7,color="blue")+
  facet_wrap(~Site,scales = "free_y",nrow=1)
p3=HFGCaseDFroll2%>%
  filter(Site %in% looking)%>%
  ggplot(aes(x=Date))+geom_point(aes(y=CollectedCases),size=2)+
  #scale_x_date(limits=c(start,end))+
  scale_x_date(limits=c(Start,End))+
  #geom_line(aes(y=CollectedCases2))+
  #geom_vline(xintercept = N1Start+7,color="red")+
  #geom_vline(xintercept = N1End+7,color="red")+
  geom_vline(xintercept = N1Start)+
  geom_vline(xintercept = N1End)+
  #geom_vline(xintercept = N1Start-7,color="blue")+
  #geom_vline(xintercept = N1End-7,color="blue")+
  facet_wrap(~Site,scales = "free_y",nrow=1)
p4=HFGCaseDFroll2%>%
  filter(Site %in% looking)%>%
  ggplot(aes(x=Date))+geom_point(aes(y=EpisodeCases),size=2)+
  #scale_x_date(limits=c(start,end))+
  scale_x_date(limits=c(Start,End))+
  #geom_line(aes(y=EpisodeCases2))+
  #geom_vline(xintercept = N1Start+7,color="red")+
  #geom_vline(xintercept = N1End+7,color="red")+
  geom_vline(xintercept = N1Start)+
  geom_vline(xintercept = N1End)+
  #geom_vline(xintercept = N1Start-7,color="blue")+
  #geom_vline(xintercept = N1End-7,color="blue")+
  facet_wrap(~Site,scales = "free_y",nrow=1)

ggarrange(p1,p2,nrow = 2,align="hv")

p1
p2
p3
p4


p1=HFGFrame%>%
  filter(N1<10e6)%>%
  filter(Site == "Kenosha")%>%
  group_by(Site)%>%
  #mutate(N1roll=RollAvg(N1,n=3))%>%
  ggplot()+aes(y=N1)+geom_point(aes(x=Date),size=2)+facet_wrap(~Site,nrow=1)+
  scale_x_date(limits=c(N1Start,N1End))+scale_y_log10()
```

```{r Data length}

HFGFrame2%>%
  filter(!is.na(N1))%>%
  group_by(Site)%>%
  summarize(leng=max(Date)-min(Date))

```

```{r Visualization and reserching, fig.height = 8, fig.width = 15,warning=FALSE}
FullData=inner_join(HFGCaseDF,HFGFrame,by=c("Site","Date"))


DatesDF=HFGCaseDF%>%
  filter(is.na(EpisodeCases))
Dates=DatesDF$Date
DatesD2F=HFGCaseDF%>%
  filter(EpisodeCases==-999)
Dates2=DatesD2F$Date



prepData=FullData%>%
  mutate(State=ifelse(EpisodeCases==-999,"1-5","Temp"))%>%
  mutate(State=ifelse(EpisodeCases>0,"NormalData",State))%>%
  mutate(State=ifelse(is.na(EpisodeCases),"0",State))


prepData%>%
  #filter(!(Date %in% (ymd("2021/2/5")+-1:4)))%>%
  ggplot()+aes(x=Date,y=N1)+geom_point(aes(color=State))+facet_wrap(~Site,scales = "free")#+scale_y_log10()#+geom_smooth()


```


```{r Dorms Data analysis, fig.height = 8, fig.width = 15}
LatCaseDF=CovidDataPARSER(LatSpringCaseFN,LatFallCaseFN,LatMMSDFN)%>%
  select(Date,Site,Cases,Tests,Per_pos,rollingPer_pos,SevCases)

LatWasteDF=WasteWater(LatWasteFN)%>%
  mutate(Date=as.Date(Date))%>%
  filter(!is.na(Date),!is.na(N1),!is.na(Site))%>%
  filter(Date<mdy("6/5/2021"))%>%
  select(Date,Site,N1,N2,PMMoV,Pct_BCoV,AVG)


shift=-7
LeftDate=min(LatWasteDF$Date)
RightDate=max(LatWasteDF$Date)
p1=LatWasteDF%>%
  filter((Site=="UW-Sellery")|(Site=="UW-LakeShore"))%>%
  ggplot()+aes(x=Date,y=N1)+geom_point(aes(color=N1<5e4),show.legend=F)+#scale_y_log10()+#geom_smooth(span=.42)+
  facet_wrap(~Site,scales="free_y")+
  scale_x_date(limits=c(LeftDate,RightDate))

p2=LatCaseDF%>%
  filter((Site=="UW-Sellery")|(Site=="UW-LakeShore"))%>%
  ggplot()+aes(x=Date)+geom_point(aes(y=Cases),show.legend=F)+
  geom_line(aes(y=SevCases))+facet_wrap(~Site,scales="free_y")+
  scale_x_date(limits=c(LeftDate+shift,RightDate+shift))
ggarrange(p1,p2,nrow = 2,align="hv")



shift=0
LeftDate=min(LatWasteDF$Date)
RightDate=max(LatWasteDF$Date)
p1=LatWasteDF%>%
  filter((Site=="Madison"))%>%
  ggplot()+aes(x=Date,y=N1)+geom_point(aes(color=N1<5e4),show.legend=F)+#scale_y_log10()+#geom_smooth(span=.42)+
  facet_wrap(~Site,scales="free_y")+
  scale_x_date(limits=c(LeftDate,RightDate))

p2=LatCaseDF%>%
  filter((Site=="Madison"))%>%
  ggplot()+aes(x=Date)+geom_point(aes(y=Cases),show.legend=F)+
  geom_line(aes(y=SevCases))+facet_wrap(~Site,scales="free_y")+
  scale_x_date(limits=c(LeftDate+shift,RightDate+shift))


p1=LatWasteDF%>%
  filter((Site=="Madison"))
p2=HFGFrame%>%
  filter((Site=="Madison"))


ggplot()+geom_point(aes(y=N1,color=Filter,x=Date),data=p2)+
  geom_point(aes(y=N1,x=Date),data=p1,size=3)+
  scale_x_date(limits=c(N1Start,N1End))
ggarrange(p1,p2,nrow = 2,align="hv")
#just HFG datapoint
#take overlap and put on same plot

```

```{r varience messure`,fig.height = 15, fig.width = 15}
HFGWeird=HFGFrame%>%
  mutate(DateSite=paste(Date,Site))
HFGWeird2=HFGWeird%>%
  group_by(Date,Site)%>%
  summarise(MN1=median(N1),MPMM=median(PMMoV))%>%
  mutate(DateSite=paste(Date,Site))
  

ggplot()+geom_point(data=HFGWeird,aes(y=N1,x=Date,color=DateSite),alpha=.2,show.legend = F)+
  geom_point(data=HFGWeird2,aes(y=MN1,x=Date,color=DateSite),size=3,show.legend = F)+scale_y_log10()+
  facet_wrap(~Site)
  scale_x_log10()



```
