---
title: "Variant Data Vignette"
author: "Kyllan Wunder"
vignette: >
  %\VignetteIndexEntry{Variant Data Vignette}
  \usepackage[utf8]{inputenc}
  %\VignetteEngine{knitr::rmarkdown}
output:
  pdf_document: default
  html_document: default
urlcolor: blue

---
# Variant Data

This data is from [https://github.com/hodcroftlab/covariants/tree/master](https://github.com/hodcroftlab/covariants/tree/master).
It reports the proportion of cases that are each variant every 2 weeks for the state of Wisconsin. 
Below there are 2 methods the first shows the proportion of each variant all together and the second shows only variants that are over 50% (i.e. the dominant variants)

```{r load packages}
library(DSIWastewater)
library(data.table)
library(dplyr)
library(ggplot2)
data(Covariants_data, package = "DSIWastewater")

Covariants_data$category <- row.names(Covariants_data)
onlycovar <- Covariants_data[-c(1,2)]
mdfr <- melt(onlycovar, id.vars = "category")

```

```{r Variant data head}
head(Covariants_data)
```


```{r Variant data percentages}
percentages <- mdfr %>%
  group_by(category) %>%
  mutate(sum = sum(value), percent = value/sum, majority = case_when(percent > .5 ~ paste(variable)))

per <- percentages %>% 
  tidyr::drop_na(majority)

dates <- Covariants_data[c("week","category")]

perDates <- merge(per,dates,by="category")
```




```{r Variant data graph, fig.height = 6}
VariantPercentage <- ggplot(mdfr, aes(factor(category,levels = c(1:69)), value, fill = variable)) +
    geom_bar(position = "fill", stat = "identity") +
    xlab("bi-weekly (2020-08-17 to 2022-12-05)") +
    ylab("Covariant Percent")+
    theme(legend.position="bottom") +
    title("All variants by percentage of cases reported")


VariantPercentage

#Run this for interactive graph
#ggplotly(VariantPercentage)
```

```{r Variant data percentages graph}
ggplot(perDates, aes(x=week, y=percent,fill=majority)) +
  geom_col() +
  xlab("bi-weekly") +
  ylab("Percent of total cases") +
  theme(axis.text.x = element_text(angle = 90, hjust=1)) +
  title("Variants over 50% of reported cases")

```

