---
title: "Comparing address and census level case data"
author: "Marlin Lee"
date: "6/13/2021"
output:
  pdf_document: default
  html_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```


```{r Importing, include=FALSE}
library(shiny)
library(ggpubr)
library(dplyr)

#Data Files and prepwork
source("../Scripts/GenPlotMaking.R")
source("../Scripts/WastewaterDataProccess.R")
source("../Scripts/CasesDataProccess.R")
source("../Scripts/HelperFunctions.R")
LatWasteFN <- "../../UntrackedData/WW SARS-COV-2 Data V5.xlsx"
LatSpringCaseFN="../../UntrackedData/SpringSemester_CasesByDorm.tsv"
LatFallCaseFN="../../UntrackedData/FallSemester_CasesByDorm.tsv"
HFGWasteFN = "../../UntrackedData/HFG data for stats preliminary 3-18-21.xlsx"
HFGCaseFN="../../UntrackedData/HighFreq_CaseData_2021-05-07.csv"
LatMMSDFN = "../../UntrackedData/MMSD_Cases.2021-05-21.csv"


source("../Scripts/WasteShiny/PrepData.R", local = TRUE)
```


```{r Comp cases}
HFGCaseDF2=HFGCaseDF%>%
  filter(Site=="Madison")%>%
  filter(ConfirmedCases!=-999)%>%
  filter(CollectedCases!=-999)
LatCaseDF2=LatCaseDF%>%
  filter(Site=="Madison")

ggplot() + geom_point(aes(x=Date,y=Cases,color="cases"),data=LatCaseDF2) + 
  geom_point(aes(x=Date,y=ConfirmedCases,color="ConfirmedCases"),data=HFGCaseDF2)+
  scale_x_date(limits=c(min(HFGCaseDF2$Date),max(HFGCaseDF2$Date)))+
  facet_wrap(~Site)

inner_join(HFGCaseDF2,LatCaseDF2,by=c("Date","Site"))%>%
  ggplot()+aes(x=Cases,y=ConfirmedCases)+geom_point()+
  geom_abline()

inner_join(HFGCaseDF2,LatCaseDF2,by=c("Date","Site"))%>%
  mutate(Diff=abs(ConfirmedCases-Cases))%>%
  ggplot()+
  geom_point(aes(x=Date,y=Diff))+
  #geom_point(aes(x=Date,y=ConfirmedCases,color=Diff>75))+
  geom_abline()



ggplot() + geom_point(aes(x=Date,y=Cases,color="cases"),data=LatCaseDF2) + 
  geom_point(aes(x=Date,y=ReportedCases,color="ReportedCases"),data=HFGCaseDF2)+
  scale_x_date(limits=c(min(HFGCaseDF2$Date),max(HFGCaseDF2$Date)))+
  facet_wrap(~Site)

inner_join(HFGCaseDF2,LatCaseDF2,by=c("Date","Site"))%>%
  ggplot()+aes(x=Cases,y=ReportedCases)+geom_point()+
  geom_abline()

inner_join(HFGCaseDF2,LatCaseDF2,by=c("Date","Site"))%>%
  mutate(Diff=abs(ReportedCases-Cases))%>%
  ggplot()+
  geom_point(aes(x=Date,y=Diff))+
  #geom_point(aes(x=Date,y=ConfirmedCases,color=Diff>75))+
  geom_abline()

```


```{r}
head(HFGCaseDF)
#EpisodeCases: A metric that counts when people first have symptoms
#CollectedCases: counts when people report they have Covid
#ConfirmedCases: counts when test results come back saying they have Covid
#ReportedCases: A day delayed Confirmed cases that match's what the government reports

#-999 means that the number of cases was between 1 and 5
MainHFGCaseDF <- HFGCaseDF%>%
  mutate(EpisodeCases=ifelse(EpisodeCases==-999,2.5,EpisodeCases),
         CollectedCases=ifelse(CollectedCases==-999,2.5,CollectedCases),
         ConfirmedCases=ifelse(ConfirmedCases==-999,2.5,ConfirmedCases),
         ReportedCases=ifelse(ReportedCases==-999,2.5,ReportedCases))

MainHFGCaseDF%>%
  ggplot()+
  aes(x=Date)+
  geom_smooth(aes(y=ReportedCases,color="ReportedCases"),span =.4,se=FALSE)+
  geom_smooth(aes(y=EpisodeCases,color="EpisodeCases"),span =.4,se=FALSE)+
  geom_smooth(aes(y=CollectedCases,color="CollectedCases"),span =.4,se=FALSE)+
  geom_smooth(aes(y=ConfirmedCases,color="ConfirmedCases"),span =.4,se=FALSE)+
  scale_x_date(limits=c(mdy("1/1/2021"),mdy("4/1/2021")))+
  facet_wrap(~Site,scales="free")


MainHFGCaseDF%>%
  summarise(ReportedCases=mean(ReportedCases,na.rm=TRUE),
            EpisodeCases=mean(EpisodeCases,na.rm=TRUE),
            CollectedCases=mean(CollectedCases,na.rm=TRUE),
            ConfirmedCases=mean(ConfirmedCases,na.rm=TRUE))


full_join(MainHFGCaseDF,MainHFGWasteDF)%>%
  filter(Site %in% c("Kenosha","Madison","Oshkosh","Sun Prairie","Wausau"),Filter=="1")%>%
  ggplot()+
  aes(x=Date)+
  geom_smooth(aes(y=EpisodeCases,color="EpisodeCases"),span =.4,se=FALSE)+
  geom_smooth(aes(y=CollectedCases,color="CollectedCases"),span =.4,se=FALSE)+
  geom_smooth(aes(y=ConfirmedCases,color="ConfirmedCases"),span =.4,se=FALSE)+
  geom_smooth(aes(y=N1/10000,color="N1"),span =.4,se=FALSE)+
  scale_x_date(limits=c(mdy("1/20/2021"),mdy("3/1/2021")))+
  facet_wrap(~Site)
```
