---
title: "Intercepter Shape"
author: "Marlin"
date: "7/6/2021"
output: html_document
---

```{r Prep}
library(ggpubr)
library(dplyr)
library(limma)

#Data Files and prep work
source("../../Scripts/GenPlotMaking.R")
source("../../Scripts/WasteWaterDataProccess.R")
source("../../Scripts/CasesDataProccess.R")
source("../../Scripts/HelperFunctions.R")
library("TTR")

source("../../Scripts/WasteShiny/PrepData.R", local = TRUE)
```

```{r Needed Functions}
```


```{r,warning=FALSE}

MadSites <- c("Madison","MMSD-P2","MMSD-P7","MMSD-P8","MMSD-P11","MMSD-P18")

LIMSMADDF <- LIMSFullDF%>%
  filter(Site %in% MadSites)
LatMadCaseDF <- LatCaseDF%>%
  filter(Site %in% MadSites)
RollLatMadCaseDF <- LatCaseDFRoll%>%
  filter(Site %in% MadSites)

PlotListN1 <- LIMSMADDF%>%
  ggplot()+
  aes(x=Date,y=N1)+
  geom_point()+
  geom_smooth(se=FALSE)+
  facet_wrap(~Site)+
  scale_y_log10()+
  scale_x_date(limits=c(mdy("1/1/2021"),mdy("7/1/2021")))


PlotListCases <- LatMadCaseDF%>%
  ggplot()+
  geom_rect(aes(ymin=0,ymax=Cases,xmin=Date-.5,
                            xmax=Date+.5),
                            alpha=.4,
                            size=5,na.rm=TRUE)+
  facet_wrap(~Site)+
  scale_x_date(limits=c(mdy("1/1/2021"),mdy("7/1/2021")))+
  coord_cartesian(ylim=c(0,100))+
  geom_line(aes(x=Date,y=Cases),color="red",data=RollLatMadCaseDF)

PlotListPer <- LatMadCaseDF%>%
  ggplot()+
  geom_rect(aes(ymin=0,ymax=Per_pos,xmin=Date-.5,
                            xmax=Date+.5),
                            alpha=.4,
                            size=5,na.rm=TRUE)+
  facet_wrap(~Site)+
  scale_x_date(limits=c(mdy("1/1/2021"),mdy("7/1/2021")))+
  coord_cartesian(ylim=c(0,50))+
  geom_line(aes(x=Date,y=Per_pos),color="red",data=RollLatMadCaseDF)


PlotListN1

PlotListCases

PlotListPer
```
