---
params:
  BaseDir: "Z:/"
  ##BaseDir: "/Volumes/byandell/"
title: "Overview Of Data"
author: "Marlin"
output: html_document
---

##HFG Covid concentration data***
```{r File name, include=FALSE}
BaseDir <- params$BaseDir
HFGWasteFN <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/HFG data for stats corrected 071421.xlsx")
```

```{r Gen need functions}

AVGGenFN <- function(N1, N2) {
  AVG <- sqrt(N1 * N2)
  AVG <- ifelse(is.na(N1), N2, AVG)
  AVG <- ifelse(is.na(N2), N1, AVG)
}

```

```{r parse data}
#needs: readxl, tidyverse, lubridate
library(readxl)
library(tidyverse)
library(lubridate)
MissingCode <-c("","NA","0","Undetected","Not Detected",
           "Field Parameters to be filled in", 
           "Inhibited-to be re-ran", "#DIV/0!","-","In progress","Undetermined","LA")

HFGWasteDF <- read_excel(HFGWasteFN, na = MissingCode,
                         col_types = c(rep("text", 5), rep("numeric", 2),"text",rep("numeric", 2),"text",rep("numeric", 3)),
                                                 sheet = 1)%>%
    rename(repName="qpCR Sample Name",
           Site="Plant",
           Date="Collection Date",
           N1Ct="N1 CT",
           N1="N1 GC/L",
           N1LOD="N1 <LOD",
           N2Ct="N2 CT",
           N2="N2 GC/L",
           N2LOD="N2 <LOD",
           PMMOVCT="PMMOV CT",
           PMMOV="PMMOV GC/L",
           BCoV="BCoV% recovery",
           Filter = "Filter Rep",
           Well = "Well Rep")%>%
    mutate(N1LOD=N1LOD=="Y",
           N2LOD=N2LOD=="Y",
           AVG = AVGGenFN(N1, N2),
           wt = 2 - is.na(N1) - is.na(N2),
           Date=coalesce(suppressWarnings(as.numeric(Date))-1+ymd("1900-01-01"),
                           suppressWarnings(mdy(Date))))
```

```{r top level data exploration}
head(HFGWasteDF)

MainHFGWasteDF <- HFGWasteDF%>%
  select(Site,Date,Filter,Well,N1,N2,AVG,PMMOV,BCoV)

MainHFGWasteDF%>%
  ggplot()+
  geom_point(aes(x=Date,y=N1,color=Filter))+
  scale_y_log10()+
  facet_wrap(~Site)


MainHFGWasteDF%>%
  ggplot()+
  geom_point(aes(x=N1,y=BCoV))+
  scale_x_log10()+
  #scale_y_log10()+
  facet_wrap(~Site)

MainHFGWasteDF%>%
  ggplot()+
  geom_point(aes(x=N1,y=PMMOV))+
  scale_x_log10()+
  scale_y_log10()+
  facet_wrap(~Site)

MainHFGWasteDF%>%
  ggplot()+
  geom_point(aes(x=N1,y=N2))+
  scale_x_log10()+
  scale_y_log10()+
  facet_wrap(~Site)
```


```{r Case Data Parsing}
HFGCasesFN  <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/HighFreq_CaseData_2021-05-07.csv")


HFGCaseDFNoReported <- read.csv(HFGCasesFN)%>%
  rename(Site=wwtp_name)%>%
  filter(!is.na(Site))%>%
  mutate(Date=ymd(Date))%>%
  mutate(Site=ifelse(Site=="SunPrairie","Sun Prairie",Site))%>%
  mutate(Site=ifelse(Site=="RiverFalls","River Falls",Site))
  
HFGCaseDFReportedOnly <- HFGCaseDFNoReported%>%
  mutate(Date=Date+1,ReportedCases=ConfirmedCases)%>%
  select(Date,Site,ReportedCases)
  
HFGCaseDF  <-  full_join(HFGCaseDFReportedOnly,HFGCaseDFNoReported,by=c("Date","Site"))
```

```{r}
head(HFGCaseDF)
#EpisodeCases: A metric that counts when people first have symptoms
#CollectedCases: counts when people report they have Covid
#ConfirmedCases: counts when test results come back saying they have Covid
#ReportedCases: A day delayed Confirmed cases that match's what the government reports

#-999 means that the number of cases was between 1 and 5
MainHFGCaseDF <- HFGCaseDF%>%
  mutate(EpisodeCases=ifelse(EpisodeCases==-999,2.5,EpisodeCases),
         CollectedCases=ifelse(CollectedCases==-999,2.5,CollectedCases),
         ConfirmedCases=ifelse(ConfirmedCases==-999,2.5,ConfirmedCases),
         ReportedCases=ifelse(ReportedCases==-999,2.5,ReportedCases))

MainHFGCaseDF%>%
  ggplot()+
  aes(x=Date)+
  geom_smooth(aes(y=ReportedCases,color="ReportedCases"),span =.4,se=FALSE)+
  geom_smooth(aes(y=EpisodeCases,color="EpisodeCases"),span =.4,se=FALSE)+
  geom_smooth(aes(y=CollectedCases,color="CollectedCases"),span =.4,se=FALSE)+
  geom_smooth(aes(y=ConfirmedCases,color="ConfirmedCases"),span =.4,se=FALSE)+
  scale_x_date(limits=c(mdy("1/1/2021"),mdy("4/1/2021")))+
  facet_wrap(~Site,scales="free")


MainHFGCaseDF%>%
  summarise(ReportedCases=mean(ReportedCases,na.rm=TRUE),
            EpisodeCases=mean(EpisodeCases,na.rm=TRUE),
            CollectedCases=mean(CollectedCases,na.rm=TRUE),
            ConfirmedCases=mean(ConfirmedCases,na.rm=TRUE))


full_join(MainHFGCaseDF,MainHFGWasteDF)%>%
  filter(Site %in% c("Kenosha","Madison","Oshkosh","Sun Prairie","Wausau"),Filter=="1")%>%
  ggplot()+
  aes(x=Date)+
  geom_smooth(aes(y=EpisodeCases,color="EpisodeCases"),span =.4,se=FALSE)+
  geom_smooth(aes(y=CollectedCases,color="CollectedCases"),span =.4,se=FALSE)+
  geom_smooth(aes(y=ConfirmedCases,color="ConfirmedCases"),span =.4,se=FALSE)+
  geom_smooth(aes(y=N1/10000,color="N1"),span =.4,se=FALSE)+
  scale_x_date(limits=c(mdy("1/20/2021"),mdy("3/1/2021")))+
  facet_wrap(~Site)
```

```{r LIMS Data}
LIMSFN <- paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/WATERMICRO_WW_COVID-2021-06-30 17 40.xlsx")

NumericVars=c("average_flow_rate","avg_sars_cov2_conc","bcov_rec_rate",
                "bcov_spike_conc","capacity_mgd","conductivity",
                "equiv_sewage_amt","n1_lod","n1_loq","n1_num_no_target_control",
                "n1_sars_cov2_conc","n1_sars_cov2_error","n1_sars_cov2_lod",
                "n2_lod","n2_loq","n2_num_no_target_control","n2_sars_cov2_conc",
                "n2_sars_cov2_error","ph","pmmov_conc","population_served",
                "temperature","tss")
  
LIMSDF <- read_excel(LIMSFN,na  =  MissingCode,col_types = c(rep("text",61)))
LIMSDF <- suppressWarnings(mutate(LIMSDF,
      across(all_of(NumericVars),as.numeric),
      test_result_date=as.POSIXlt(test_result_date,format="%m/%d/%Y %H:%M"),
      sample_collect_date=mdy(sample_collect_date)
    ))%>%
    rename(
      Site=wwtp_name,
      FlowRate=average_flow_rate,
      Cov1_below_lod=avg_sars_cov2_below_lod,
      cov2_conc=avg_sars_cov2_conc,
      BCoV=bcov_rec_rate,
      BCoVConc=bcov_spike_conc,
      county=county_names,
      Date=sample_collect_date,
      RepDate=test_result_date,
      N1=n1_sars_cov2_conc,
      N1Error=n1_sars_cov2_error,
      N2=n2_sars_cov2_conc,
      N2Error=n2_sars_cov2_error,
      PMMoV=pmmov_conc,
      Pop=population_served
    )%>%
    mutate(#Standardizing the Site names names
      Site=ifelse(Site=="Madison Metro","Madison",Site),
      Site=ifelse(Site=="Covid Sewage UW DORM","UW-LakeShore",Site),
      Site=ifelse(Site=="Covid Sewage UW Sell","UW-Sellery",Site),
      Site=ifelse(Site=="Madison-P2-Central","MMSD-P2",Site),
      Site=ifelse(Site=="Madison-P7-SE","MMSD-P7",Site),
      Site=ifelse(Site=="Madison-P8-West","MMSD-P8",Site),
      Site=ifelse(Site=="Madison-P11-SW","MMSD-P11",Site),
      Site=ifelse(Site=="Madison-P18-NE","MMSD-P18",Site),
      AVG = AVGGenFN(N1, N2),
      wt = 2 - is.na(N1) - is.na(N2),
      #Giving the different semesters unique names
      isDorm = ifelse(Site %in% c("UW-LakeShore","UW-Sellery"),TRUE,FALSE),
      Site = ifelse(isDorm&Date>=ymd("2021-01-11"),paste("Spring",Site),Site),
      Site = ifelse(isDorm&Date<=ymd("2020-12-25"),paste("Fall",Site),Site),
      Site = ifelse(isDorm&Date>ymd("2020-12-25")&
                      Date<ymd("2021-01-11"),paste("Break",Site),Site)
    )%>%
    select(-isDorm)%>%
    #converting -1 meaning missing data to NA
    mutate(N1=ifelse(N1==-1,NA,N1),
           N2=ifelse(N2==-1,NA,N2),
           PMMoV=ifelse(PMMoV==-1,NA,PMMoV),
           BCoV=ifelse(BCoV==-1,NA,BCoV))%>%
    mutate(AVG = AVGGenFN(N1, N2),
           wt = 2 - is.na(N1) - is.na(N2))
```

```{r LIMS top level data exploration,fig.height=20,fig.width=20}
head(LIMSDF)

MainLIMSDFWasteDF <- LIMSDF%>%
  select(Site,Date,N1,N1Error,N2,AVG,PMMoV,BCoV)

MainLIMSDFWasteDF%>%
  ggplot()+
  geom_point(aes(x=Date,y=N1))+
  scale_y_log10()+
  facet_wrap(~Site)


MainLIMSDFWasteDF%>%
  ggplot()+
  geom_point(aes(x=N1,y=BCoV))+
  scale_x_log10()+
  #scale_y_log10()+
  facet_wrap(~Site)

MainLIMSDFWasteDF%>%
  ggplot()+
  geom_point(aes(x=N1,y=PMMoV))+
  scale_x_log10()+
  scale_y_log10()+
  facet_wrap(~Site)

MainLIMSDFWasteDF%>%
  ggplot()+
  geom_point(aes(x=N1,y=N2))+
  scale_x_log10()+
  scale_y_log10()+
  facet_wrap(~Site)

MainLIMSDFWasteDF%>%
  ggplot()+
  geom_point(aes(x=N1,y=N1Error))+
  scale_x_log10()+
  scale_y_log10()+
  facet_wrap(~Site)

MainLIMSDFWasteDF%>%
  ggplot()+
  geom_point(aes(x=PMMoV,y=N1Error))+
  scale_x_log10()+
  scale_y_log10()+
  facet_wrap(~Site)

MainLIMSDFWasteDF%>%
  ggplot()+
  geom_point(aes(x=BCoV,y=N1Error))+
  scale_x_log10()+
  scale_y_log10()+
  facet_wrap(~Site)
```

```{r Madison Case Data}
LIMSCaseMMSDFN  <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/MMSD_Cases.csv")
LIMSSpringDormFN  <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/SpringSemester_CasesByDorm.TSV")
LIMSFallDormFN  <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/FallSemester_CasesByDorm.TSV")

SpringDorms <- read.csv(LIMSSpringDormFN,sep = "",header = T)%>%
    mutate(Tests=Negative	+ Positive,Per_pos=100*Positive/Tests,
           Site = ifelse(Site == "UW_D", "UW-LakeShore", Site),
           Site = ifelse(Site == "UW_S", "UW-Sellery", Site),
           Date=mdy(Date),
           Site = ifelse(Date>=ymd("2021-01-11"),paste("Spring",Site),Site),
           Site = ifelse(Date<=ymd("2020-12-25"),paste("Fall",Site),Site),
           Site = ifelse(Date>ymd("2020-12-25")&
                           Date<ymd("2021-01-11"),paste("Break",Site),Site))%>%
    rename(Cases=Positive)%>%
    select(-Negative)%>%
    mutate(Population=NA)
FallDorms <- read.csv(LIMSFallDormFN,sep = "",header = T)%>%
    mutate(Tests=Negative	+ Positive,Per_pos=100*Positive/Tests,
           Site = ifelse(Site == "UW_D", "UW-LakeShore", Site),
           Site = ifelse(Site == "UW_S", "UW-Sellery", Site),
           Date=mdy(Date),
           Site = ifelse(Date>=ymd("2021-01-11"),paste("Spring",Site),Site),
           Site = ifelse(Date<=ymd("2020-12-25"),paste("Fall",Site),Site),
           Site = ifelse(Date>ymd("2020-12-25")&
                           Date<ymd("2021-01-11"),paste("Break",Site),Site))%>%
    rename(Cases=Positive)%>%
    select(-Negative)%>%
    mutate(Population=NA)

lag=1
MMSDdata  <-  read.csv(LIMSCaseMMSDFN)%>%
  rename(Site=ServiceID)%>%
  mutate(Site = ifelse(Site=="MMSD","Madison",paste("MMSD-P",Site,sep="")),
  Date = as.Date(Date))%>%
  group_by(Site)%>%
  mutate(Cases=Cases - lag(Cases, n=lag,default = NA),
    Tests=Tests- lag(Tests, n=lag,default = NA))%>%
  mutate(Per_pos=100*Cases/Tests)%>%
  mutate(Site = ifelse(Site == "MMSD P18", "MMSD-P18", Site),
          Site = ifelse(Site == "MMSD P11", "MMSD-P11", Site),
          Site = ifelse(Site == "MMSD P2", "MMSD-P2", Site),
          Site = ifelse(Site == "MMSD P7", "MMSD-P7", Site),
          Site = ifelse(Site == "MMSD P8", "MMSD-P8", Site))


MadisonCaseDF <- rbind(rbind(MMSDdata,SpringDorms,FallDorms))
```

```{r Madison Case Top level exploration}

head(MadisonCaseDF)

MadisonCaseDF%>%
  ggplot()+
  aes(x=Date)+
  geom_point(aes(y=Tests,color="Tests"))+
  geom_point(aes(y=Cases,color="Cases"))

MadisonCaseDF%>%
  ggplot()+
  geom_point(aes(x=Cases,y=Tests))+
  scale_y_log10()+
  scale_x_log10()
```

```{r Case format comperison}
ColsName <- c(colnames(MadisonCaseDF),
#colnames(LIMSDF),
#colnames(HFGWasteDF),
colnames(HFGCaseDF))

UniqueColsName <- unique(ColsName)

length(ColsName)
length(UniqueColsName)

UniqueColsName
```

```{r WasteWater format comperison}
ColsName <- c(
colnames(LIMSDF),
colnames(HFGWasteDF))

UniqueColsName <- unique(ColsName)

length(ColsName)
length(UniqueColsName)

UniqueColsName
```
