---
params:
  BaseDir: "Z:/"
  ##BaseDir: "/Volumes/byandell/"
title: "NoTSCorrelationShiny"
author: "Marlin"
date: "8/30/2021"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r set up markdown settings, echo=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)

```

```{r Start enviroment, message=FALSE, warning=FALSE}

library(ggpubr)
library(forecast)
library(lmtest)
library(lubridate)
library(limma)
library(zoo)
library(dplyr)
library(RColorBrewer)
library(shiny)

#Data Files and prep work
source("../../Scripts/GenPlotMaking.R")
source("../../Scripts/WasteWaterDataProccess.R")
source("../../Scripts/CasesDataProccess.R")
source("../../Scripts/HelperFunctions.R")

```

```{r DF Set Up, include=TRUE}
BaseDir <- params$BaseDir
LatMMSDFN  <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/MMSD_Cases.csv")
LatSpringDormFN  <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/SpringSemester_CasesByDorm.TSV")
LatFallDormFN  <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/FallSemester_CasesByDorm.TSV")

LIMSFN <- paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/WATERMICRO_WW_COVID-2021-06-30 17 40.xlsx")

HFGCasesFN  <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/HighFreq_CaseData_2021-05-07.csv")


LatCaseDF <- CovidDataPARSER(
  LatSpringDormFN, LatFallDormFN,MMSDFN = LatMMSDFN
  ) %>% 
  
  filter(!is.na(Site)) %>%
  select(Date,Site,Cases,Tests,Per_pos)


FullCase <- LatCaseDF

FullCaseRoll <- RollPerPos(FullCase,"Cases","Tests",Facet="Site",n = 14)

LIMSFullDF <- LIMSDataPARSER(LIMSFN)%>%
  select(Date,Site, BCoV, N1,N1Error,N2, N2Error,PMMoV,Pop,FlowRate)

WeightVec <- unlist(lapply((split(dgamma(1:21,scale =5.028338,shape =2.332779),c(rep(1,7),rep(2,7),rep(3,7))
              )),mean))
```

```{r}
MergedDF <- BestCorDFGen("Madison")
```

```{R Shiny}
WasteUI  <-  fluidPage(
  titlePanel("No TS modeling"),
  sidebarLayout(
    sidebarPanel(
      sliderInput(inputId = "Lag",
                  label = "Cases Offset",
                  min = -7,
                  max = 7,
                  value = 0),
      sliderInput(inputId = "Start",
                  label = "Day of week start",
                  min = 0,
                  max = 7,
                  value = 0),
      selectInput(inputId = "BinSize",
                  label = "Bin Size",
                  choices = c(7,14),
                  selected = 7),
      checkboxInput(inputId = "Log",
                  label = "Log Comparison"),
      selectInput(inputId = "MatType",
                  label = "Heatmap value",
                  choices = c("R2","PVal","COR"),
                  selected = "R2"),
      selectInput(inputId = "CaseType",
                  label = "Case used",
                  choices = c("Cases3","Cases4","CasesM"),
                  selected = "R2")

    ),
    mainPanel(
      tabsetPanel(type = "tabs",
        tabPanel("HeatMap", plotOutput("Matrix")),
        tabPanel("Table", tableOutput('Table')),
        tabPanel("Plot", plotOutput("Plot")))
    )
  )
)
```


```{r Cop}
WasteServer <- function(input, output, session) {
  

  MainDF <- reactive({
    if(input$Log){
      FinDF <- MergedDF%>%
        mutate(Cases=log(Cases),Cases2=log(Cases2),N1=log(N1))
    }else{
      return(MergedDF)
    }
  })
  
  HeatmapData <- reactive({
    CheckFunction(DF=MainDF(),DaySmoothing=c(7,14), Mat=TRUE,
                  Ret=input$MatType,CasesUsed=input$CaseType)[[1]]
  })

  output$Matrix<-renderPlot(width=700,height=600,{
    #Store StartDate somewhere more changeable
    DayOfWeekData <- weekdays(seq(mdy("10/1/2020"), by=1,
                                    len=8))
    xAxisPlot <- expand.grid(c(7,14), -2:2)
    xAxisPlot <- xAxisPlot[order(xAxisPlot$Var1),]
    
    AxisPattern<- apply(xAxisPlot, 1, paste, collapse=" ")
    Site=unique(MainDF()$Site)
    
    HeatMapMaker(HeatmapData(),8,AxisPattern,
                 DayOfWeekData,Site=Site, 
                 "R2 relationship",ColorName="YlOrRd")
  })
  
  
  output$Plot<-renderPlot(width=700,height=600,{
    PlotingOptions(MainDF(),as.numeric(input$Start),
                   as.numeric(input$BinSize),as.numeric(input$Lag),
                   Ret="Plot",Show=TRUE)
  })
  
  output$Table <-  renderTable({
    Vector <-     CheckFunction(DF=MainDF(),DaySmoothing=c(7,14),
                            Mat=TRUE, Ret="ALL", 
                            CasesUsed=input$CaseType)[[1]]
    R2DF <- VecToDF(R2Vec,Val="R2")
    CORDF <- VecToDF(CORVec,Val="COR")
    PValDF <- VecToDF(PValVec,Val="PVal")
    return(inner_join(inner_join(R2DF,CORDF),PValDF))
  })
}
```

```{r}
shinyApp(ui = WasteUI, server = WasteServer)


# CheckFunction(DF=MergedDF,DaySmoothing=c(7,14),
#                             Mat=TRUE, Ret="All", 
#                             CasesUsed="Cases4")[[1]]
```