---
title: "DiffExplore"
author: "Marlin"
date:  "`r format(Sys.time(), '%d %B, %Y, %H:%M')`"
output: 
  bookdown::html_document2: 
    code_folding: hide
    df_print: paged
params:
  BaseDir: Z:/
  #~/Box/DSI/Projects/wastewater/RD/
knit: (
  function(inputFile, encoding) { 
    FileComp = strsplit(inputFile,"/")[[1]];
    File = FileComp[length(FileComp)];
    File = substr(File,1,nchar(File)-4);
    pSubTitle <- paste0('RmdOutput/',Sys.Date(),"_",File);
    rmarkdown::render( 
      input       = inputFile, 
      encoding    = encoding, 
      output_file = pSubTitle) })
 
---


```{r set up markdown settings, echo=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE
)

```


```{r}
library(tidyr)
library(dplyr)
library(lubridate)
library(zoo)
library(ggplot2)
library(limma)
library(ggpubr)
library(grid)
library(plotly)

#Data Files and prep work
source("../../lib/DataProccess.R")
source("../../lib/NormFuncs.R")
source("../../lib/OutlierDetectionFuncs.R")
source("../../lib/DataPathName.R")
BaseDir <- params$BaseDir#get the root of the directory where the data is stored
```

```{r, echo=FALSE}
SiteNames <- c("MMSD-P11","MMSD-P18","MMSD-P2","MMSD-P7","MMSD-P8")

#Importing the Madison waste water data
LIMSFullDF <- ParseData(LIMSWastePath(BaseDir))%>%
  filter(Site %in% SiteNames)%>%
  mutate(N1Pure = ifelse(is.na(N1),N1,N1),
         N1Pure = ifelse(is.na(N1),N1,N1),
         GeoMeanN12 = exp((log(N1Pure)+log(N1Pure))/2))%>%
  mutate(SC2_mass = (3.785*1e6)*FlowRate*N1)%>%
  select(Date, Site, N1, BCoV , N2 , SC2_mass, PMMoV,
         GeoMeanN12,FlowRate,temperature,equiv_sewage_amt, everything())


DifDF <- LIMSFullDF%>%
  filter(!is.na(N1))%>%
  group_by(Site)%>%
  arrange(Date)%>%
  mutate(LeadN1 = lead(N1) - N1,
         LagN1 = lag(N1) - N1,
         RankHighN1 = rank(LeadN1),
         RankLowN1 = rank(LagN1),
         LeadN2 = lead(N2) - N2,
         LagN2 = lag(N2) - N2,
         RankHighN2 = rank(LeadN2),
         RankLowN2 = rank(LagN2))%>%
  select(Site,Date,LeadN1,LagN1,RankHighN1,RankLowN1,RankHighN2,RankLowN2,everything())%>%
  arrange(Site,desc(RankHighN1))

DifRatDF <- LIMSFullDF%>%
  filter(!is.na(N1))%>%
  group_by(Site)%>%
  arrange(Date)%>%
  mutate(LeadN1 = lead(N1)/N1,
         LagN1 = lag(N1)/N1,
         RankHighN1 = rank(LeadN1),
         RankLowN1 = rank(LagN1),
         LeadN2 = lead(N2)/N2,
         LagN2 = lag(N2)/N2,
         RankHighN2 = rank(LeadN2),
         RankLowN2 = rank(LagN2))%>%
  select(Site,Date,LeadN1,LagN1,RankHighN1,RankLowN1,RankHighN2,RankLowN2,everything())%>%
  arrange(Site,desc(RankHighN1))

```

"Files Used: "

`r LIMSWastePath("")`

```{r, include=FALSE, echo=FALSE}
hist((DifDF$LagN1))
hist(log(DifDF$LagN1))


hist((DifRatDF$LagN1))
hist(log(DifRatDF$LagN1))

```


```{r, include=FALSE, echo=FALSE}
#DifRatDF
#DifDF
hist((DifDF$LagN1))
hist((DifRatDF$LagN1))

DiffPlot <- DifDF%>%
  ggplot()+
  geom_point(aes(x = Date,y = LagN1, color = LagN2))
ggplotly(DiffPlot)

DiffPlot <- DifRatDF%>%
  ggplot()+
  geom_point(aes(x = Date,y = log(LagN1), color = LagN2))
ggplotly(DiffPlot)


DifDF%>%
  ggplot()+
  geom_point(aes(x = log(PMMoV), y = LagN1,color = Site))+
  facet_wrap(~Site, scales = "free")
  
  DifDF%>%
  ggplot()+
  geom_point(aes(x = equiv_sewage_amt, y = LagN1,color = Site))#+
  #facet_wrap(~Site, scales = "free")
#PMMoV, FlowRate, equiv_sewage_amt
#

DifDF%>%
  #filter(Site != "Madison")%>%
  ggplot()+
  geom_point(aes(x = N1Error,y = RankLowN1))+
  facet_wrap(~Site, scales = "free")

#Come up with list top 10, 20, 50
```


```{r Interactive highlighting, include=FALSE, echo=FALSE}
#Create GGPlotly object with consistent scale for alpha, size, color
GGPlotlyWithScaling <- function(GGPlotObject, FactorSize, Display = c("Date","N1","N2")){
  AlphaScalling <- scale_alpha_manual(values = seq(.3,1, length.out = FactorSize))
  SizeScalling <- scale_size_manual(values = seq(.7,2, length.out = FactorSize))
  #ColorScalling <- scale_color_manual(values = 
  #                                c("#fee391", "#fec44f", "#fe9929",
  #                                "#d95f0e", "#993404", "#6f2f04")[(7-FactorSize):6])
  PlotlyObject <- GGPlotObject+
    AlphaScalling+
    SizeScalling#+
    #ColorScalling
  return(ggplotly(PlotlyObject, tooltip = Display))
}

#Helper Function To create bins
SumQuint <- function(Vec,Thresh){
  return(sum(Vec>Thresh))
}

#Break Data into bins based on ranking and given threshold
QuintileBound <- function(DF,VecName,Threshold,Name){
  ReturnedDF <- DF%>%
    #group_by(Site)%>%
    mutate(TempRanking = rank(!!sym(VecName))/n(),
           !!Name := factor(sapply(TempRanking, SumQuint, Thresh = Threshold)))
  ReturnedDF <- ReturnedDF%>%
    select(-TempRanking)%>%
    select(Date,Site,!!Name,everything())
  return(ReturnedDF)
}
```


```{r PlotlyView function, include=FALSE, echo=FALSE}
#Generate two plotly objects to view the Method 
#and a data table communicating classes
PlotlyView <- function(DF,ChangeVar, FlagMethod,...){
  #Creates the bin from given function
  MainDF <- FlagMethod(DF, VecName = ChangeVar, Name = "FlagScheme", ...)
  
  #Create shared GGplot object that both use
  CorePlot <- MainDF%>%
    ggplot(aes(x = Date))+
    theme(panel.spacing.y = unit(2, "lines"))
  
  #Create plot where The scheme is plotted
  #DiffPlot <- CorePlot+
  #  geom_point(aes(y = !!sym(ChangeVar), color = FlagScheme,
  #                 alpha = FlagScheme, size = FlagScheme))+
  #  facet_wrap(~Site)
  
  #Needed for correct manual scaling in GGPlotlyWithScaling
  FactorSize <- length(unique(MainDF[["FlagScheme"]]))
  
  #Create plot where The CoreVector is plotted
  DiffPlotNormN1 <- CorePlot+
    geom_point(aes(y = N1, color = FlagScheme,
                   alpha = FlagScheme, size = FlagScheme))+
    facet_wrap(~Site)
  #Create plot where The CoreVector is plotted
  DiffPlotNormN2 <- CorePlot+
    geom_point(aes(y = N2, color = FlagScheme,
                   alpha = FlagScheme, size = FlagScheme))+
    facet_wrap(~Site)
  
  #Return The Two plots
  #print(GGPlotlyWithScaling(DiffPlotNormN1, FactorSize))
  #print(GGPlotlyWithScaling(DiffPlotNormN2, FactorSize))
  #print(GGPlotlyWithScaling(DiffPlot, FactorSize))
  
  #Create DataFrame showing The bounds for the binning
  DiffDFRange <- MainDF%>%
    group_by(FlagScheme, Site)%>%
    summarise(MinBound = min(!!sym(ChangeVar), na.rm = TRUE),
              MaxBound = max(!!sym(ChangeVar), na.rm = TRUE),
              NumInBin = n())
  #print(DiffDFRange)
  RetDF <- MainDF%>%
    filter(FlagScheme!=0)
    
  return(list(GGPlotlyWithScaling(DiffPlotNormN1, FactorSize),GGPlotlyWithScaling(DiffPlotNormN2, FactorSize),RetDF))
}
```


```{r PlotlyView}

RankingDF <- LIMSFullDF%>%
  filter(Date<mdy("10/31/2021"))%>%
  group_by(Site)%>%
  arrange(Date)%>%
  mutate(N1 = ifelse(!is.na(N1),N1,0))%>%
  mutate(N2 = ifelse(!is.na(N2),N2,0))%>%
  mutate(N1RankLeft = rank(desc(N1 - lag(N1))),
         N1RankRight = rank(desc(N1 - lead(N1))),
         N2RankLeft = rank(desc(N2 - lag(N2))),
         N2RankRight = rank(desc(N2 - lead(N2))))%>%
  select(Date,Site,N1RankLeft,N1RankRight,N2RankLeft,N2RankRight,N1,N2)%>%
  mutate(MaxN1Rank = -pmax(N1RankLeft,N1RankRight,N2RankLeft,N2RankRight))


BreakUsed <- c(.90,.95)
Vec <- PlotlyView(RankingDF, "MaxN1Rank", QuintileBound, Threshold = BreakUsed)
Vec[[1]]
Vec[[2]]


RankingDF%>%
  filter(-MaxN1Rank<=10)%>%
  arrange(Date,Site)


  
    #Instead Max 10, Max 20
  #Rolling SD Vs Rolling mean
  
  #1) Show everthing for clear outliers
  #2) Show soft with 25

```


```{r ViewOutlier}

Vec[[3]]%>%
  arrange(FlagScheme)%>%
  #select(-)%>%
  rename(ErrorLevel = FlagScheme, Rank = `MaxN1Rank`)%>%
  mutate(Rank = -Rank)%>%
  arrange(ErrorLevel, Rank)#%>%
  #write.csv("RmdOutput/PossibleOutliers.csv")


LIMSFullDF%>%
  #filter(Date<mdy("10/31/2021"))%>%
  #group_by(Site)%>%
  arrange(Date)%>%
  mutate(N1 = ifelse(!is.na(N1),N1,0))%>%
  mutate(N2 = ifelse(!is.na(N2),N2,0))%>%
  mutate(N1RankLeft = rank(desc(N1 - lag(N1))),
         N1RankRight = rank(desc(N1 - lead(N1))),
         N2RankLeft = rank(desc(N2 - lag(N2))),
         N2RankRight = rank(desc(N2 - lead(N2))))%>%
  select(Date,Site,N1RankLeft,N1RankRight,N2RankLeft,N2RankRight,N1,N2)%>%
  mutate(MaxN1Rank = -pmax(N1RankLeft,N1RankRight,N2RankLeft,N2RankRight))%>%
  write.csv("RmdOutput/PossibleOutliersFullGrouped.csv")

```


```{r OvertOutliers}

ThresholdFlagDF <- RankingDF%>%
  mutate(ThresholdOutlier= -MaxN1Rank<=4)%>%
  arrange(Date,Site)%>%
    ggplot(aes(x = Date))+
    theme(panel.spacing.y = unit(2, "lines"))+
    geom_point(aes(y = N1, color = Site, shape = "N1", info = -MaxN1Rank,
                   alpha = ThresholdOutlier, size = ThresholdOutlier))+
  geom_point(aes(y = N2, color = Site, shape = "N2", info = -MaxN1Rank,
                   alpha = ThresholdOutlier, size = ThresholdOutlier))
  GGPlotlyWithScaling(ThresholdFlagDF,2, Display = c("N1","N2", "Date", "info"))
```

```{r SubtleOutliers, fig.height=20, fig.width=9}

ThresholdFlagDF <- RankingDF%>%
  mutate(MaxN1Rank = -MaxN1Rank, ThresholdOutlier = ifelse(MaxN1Rank<=47,"BFlagged","ANotFlagged"),
         ThresholdOutlier= ifelse(MaxN1Rank<=12, "CFlaggedRestrictive", ThresholdOutlier))%>%
  arrange(Date,Site)%>%
    ggplot(aes(x = Date))+
    theme(panel.spacing.y = unit(1, "lines"))+
    geom_point(aes(y = N1, color = ThresholdOutlier, shape = "N1",
                   alpha = ThresholdOutlier, size = ThresholdOutlier, info = MaxN1Rank))+
  geom_point(aes(y = N2, color = ThresholdOutlier, shape = "N2",
                   alpha = ThresholdOutlier, size = ThresholdOutlier, info = MaxN1Rank))+
  facet_wrap(~Site, ncol = 1, scales = "free")
#
  GGPlotlyWithScaling(ThresholdFlagDF,3, Display = c("N1","N2", "Date", "info"))
```


```{r }
DoRanking <- function(DF,IsGrouped,isFiltered){
  UsedDF <- DF%>%
    filter(!is.na(N1),!is.na(N2))
  if(IsGrouped){
    UsedDF <- UsedDF%>%
      group_by(Site)
  }
  if(isFiltered){
    UsedDF <- UsedDF%>%
      filter(Date<mdy("10/31/2021"))
  }
  RetDF <- UsedDF%>%
    arrange(Date)%>%
    mutate(N1 = ifelse(!is.na(N1),N1,0))%>%
    mutate(N2 = ifelse(!is.na(N2),N2,0))%>%
    mutate(N1RankLeft = rank(desc(N1 - lag(N1))),
         N1RankRight = rank(desc(N1 - lead(N1))),
         N2RankLeft = rank(desc(N2 - lag(N2))),
         N2RankRight = rank(desc(N2 - lead(N2))))%>%
    select(Date,Site,N1RankLeft,N1RankRight,N2RankLeft,N2RankRight,N1,N2)%>%
    mutate(MaxN1Rank = pmax(N1RankLeft,N1RankRight,N2RankLeft,N2RankRight))%>%
    select(Date,Site,MaxN1Rank,N1,N2)
  return(RetDF)
}

RankingDFUngroupedEarlyDay <- DoRanking(LIMSFullDF,FALSE,TRUE)
RankingDFgroupedEarlyDay <- DoRanking(LIMSFullDF,TRUE,TRUE)
RankingDFUngrouped <- DoRanking(LIMSFullDF,FALSE,FALSE)
RankingDFgrouped <- DoRanking(LIMSFullDF,TRUE,FALSE)

JoinDFFromList <- function(DFList, ByOptions, Names,CombVec){
  FullDF <- full_join(DFList[[1]],DFList[[2]], by = ByOptions)
  for (i in 3:length(DFList)){
    FullDF <- full_join(FullDF,DFList[[i]], by = ByOptions)
  }
  for(i in 1:length(DFList)){
    if(i %% 2 == 1){
      Prep = paste(CombVec, paste(rep(".x",(i+1)%/%2), collapse = ""), sep = "")
    }else{
      Prep = paste(CombVec, paste(rep(".y",(i+1)%/%2), collapse = ""), sep = "")
    }
    FullDF <- FullDF%>%
      rename(!!Names[[i]] := !!sym(Prep))
  }
  return(FullDF)
}

ToMergeDFs <- list(RankingDFUngroupedEarlyDay, RankingDFgroupedEarlyDay, RankingDFUngrouped, RankingDFgrouped)
RenameLists <- list("EarlyFull", "EarlySite", "AllFull", "AllSite")

MergedDF <- JoinDFFromList(
  ToMergeDFs, ByOptions = c("Date","Site","N1","N2"), Names = RenameLists, CombVec = "MaxN1Rank")



```



```{r}
MergedDF


GPlotly <- MergedDF%>%
  ggplot()+
    geom_point(aes(x = EarlySite, shape = Site, y = EarlyFull,color = "Filtered"))+
    geom_point(aes(x = AllSite, shape = Site, y = AllFull,color = "Full"))#+
  #geom_abline()
ggplotly(GPlotly)




A <- RankingDFUngroupedEarlyDay%>%
  filter(MaxN1Rank<=12)%>%
  arrange((MaxN1Rank))


B <- RankingDFgroupedEarlyDay%>%
  filter(MaxN1Rank<=2)%>%
  arrange((MaxN1Rank))

C <- full_join(A,B, by=c("Date","Site","N1","N2"))%>%
  #select(-N1,-N2)%>%
  arrange(Site)


G <- C%>%
  mutate(Catagory = ifelse(is.na(MaxN1Rank.x),"Grouped",ifelse(is.na(MaxN1Rank.y),"UnGrouped","Both")))%>%
  full_join(LIMSFullDF)%>%
  mutate(Catagory = ifelse(is.na(Catagory),"NotFlagged",Catagory))%>%
  ggplot()+
  geom_point(aes(x=Date,y=N1,color = Catagory), size = .75)+
  facet_wrap(~Site)
ggplotly(G)
```


```{r}



ThresholdingLabel <- function(X,ThresholdC){
  A = 0
  for (i in 1:length(ThresholdC)){
    A = A + (X<=ThresholdC[i])

  }
  return(factor(A))
}

ThresholdGenDF <- function(DF, SysUsed ,Thresholds){
  ThresholdFlagDF <- DF%>%
    filter(!is.na(!!sym(SysUsed)))%>%
    mutate(ThresholdOutlier= ThresholdingLabel(!!sym(SysUsed),Thresholds))%>%
    arrange(Date,Site)
  
  return(ThresholdFlagDF)
}

ThresholdingPloting <- function(DF, SysUsed="" , isFacet = FALSE){
  if(isFacet){
    ColorScheme = "ThresholdOutlier"
  }else{
    ColorScheme = "Site"
  }
  GPlot <- DF%>%
    filter(!is.na(ThresholdOutlier))%>%
    ggplot(aes(x = Date))+
    theme(panel.spacing.y = unit(2, "lines"))+
    geom_point(aes(y = N1, color = !!sym(ColorScheme), shape = "N1", info = !!sym(SysUsed),
                   alpha = ThresholdOutlier, size = ThresholdOutlier))+
    geom_point(aes(y = N2, color = !!sym(ColorScheme), shape = "N2", info = !!sym(SysUsed),
                   alpha = ThresholdOutlier, size = ThresholdOutlier))
  if(isFacet){
    GPlot = GPlot+
      facet_wrap(~Site, ncol = 1, scales = "free")
  }
  return(GPlot)
}

```


```{r Clear outliers}
#MergedDF
Thresh <- c(4)
UsedDF <- ThresholdGenDF(MergedDF, "EarlySite", Thresh)

UsedDF%>%
  dplyr::filter(as.integer(ThresholdOutlier)>0)

PlotedGraphic <- ThresholdingPloting(UsedDF, SysUsed = "EarlySite")

GGPlotlyWithScaling(PlotedGraphic, length(Thresh)+1)

```

```{r FullOutliers, fig.height=10, fig.width=9}
#"EarlyFull", "EarlySite", "AllFull", "AllSite"
Thresh <- c(4, 11)
UsedDF <- ThresholdGenDF(MergedDF, "EarlySite", Thresh)
UsedDF%>%
  dplyr::filter(as.integer(ThresholdOutlier)>0)

PlotedGraphic <- ThresholdingPloting(UsedDF, SysUsed = "EarlySite", isFacet =TRUE)

GGPlotlyWithScaling(PlotedGraphic, length(Thresh)+1)
```

  


