---
title: "Candidates for Outliers"
author: "Marlin"
date:  "`r format(Sys.time(), '%d %B, %Y, %H:%M')`"
output: 
  bookdown::html_document2: 
    code_folding: hide
    df_print: paged
params:
  BaseDir: Z:/
  #~/Box/DSI/Projects/wastewater/RD/
knit: (
  function(inputFile, encoding) { 
    FileComp = strsplit(inputFile,"/")[[1]];
    File = FileComp[length(FileComp)];
    File = substr(File,1,nchar(File)-4);
    pSubTitle <- paste0('RmdOutput/',Sys.Date(),"_",File);
    rmarkdown::render( 
      input       = inputFile, 
      encoding    = encoding, 
      output_file = pSubTitle) })
---

```{r set up markdown settings, echo=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE
)
```


```{r}
library(tidyr)
library(dplyr)
library(lubridate)
library(zoo)
library(ggplot2)
library(limma)
library(ggpubr)
library(grid)
library(plotly)

#Data Files and prep work
source("../../lib/DataProccess.R")
source("../../lib/NormFuncs.R")
source("../../lib/OutlierDetectionFuncs.R")
source("../../lib/DataPathName.R")
source("InterceptorPlots.R")
BaseDir <- params$BaseDir#get the root of the directory where the data is stored
```

```{r, echo=FALSE}
SiteNames <- c("MMSD-P11","MMSD-P18","MMSD-P2","MMSD-P7","MMSD-P8")

#Importing the Madison waste water data
LIMSFullDF <- ParseData(LIMSWastePath(BaseDir))%>%
  filter(Site %in% SiteNames)%>%
  mutate(N1Pure = ifelse(is.na(N1),N1,N1),
         N1Pure = ifelse(is.na(N1),N1,N1),
         GeoMeanN12 = exp((log(N1Pure)+log(N1Pure))/2))%>%
  mutate(SC2_mass = (3.785*1e6)*FlowRate*N1)%>%
  select(Date, Site, N1, BCoV , N2 , SC2_mass, PMMoV,
         GeoMeanN12,FlowRate,temperature,equiv_sewage_amt, everything())
```


"Data Files Used: "

raw: qPCR Semi-Final Query 2.9.22.xlsx

processed:`r LIMSWastePath("")`


```{r Ploting}
GGPlotlyWithScaling <- function(GGPlotObject, FactorSize, Display = c("Date","N1","N2")){
  AlphaScalling <- scale_alpha_manual(values = seq(.3,1, length.out = FactorSize))
  SizeScalling <- scale_size_manual(values = seq(.7,2, length.out = FactorSize))
  #ShapeSCalling <- scale_shape_discrete(values = c(21,23))
  PlotlyObject <- GGPlotObject+
    AlphaScalling+
    SizeScalling
  return(ggplotly(PlotlyObject, tooltip = Display))
}


ThresholdingLabel <- function(X,ThresholdC){
  A = 0
  for (i in 1:length(ThresholdC)){
    A = A + (X<=ThresholdC[i])

  }
  return(factor(A))
}

ThresholdGenDF <- function(DF, SysUsed ,Thresholds){
  ThresholdFlagDF <- DF%>%
    filter(!is.na(!!sym(SysUsed)))%>%
    mutate(ThresholdOutlier= ThresholdingLabel(!!sym(SysUsed),Thresholds))%>%
    arrange(Date,Site)
  
  return(ThresholdFlagDF)
}

ThresholdingPloting <- function(DF, SysUsed="", ThreshLevel = "" , isFacet = FALSE){
  if(isFacet){
    ColorScheme = ThreshLevel
  }else{
    ColorScheme = "Site"
  }
  GPlot <- DF%>%
    filter(!is.na(!!sym(ThreshLevel)))%>%
    ggplot(aes(x = Date))+
    theme(panel.spacing.y = unit(2, "lines"))+
    geom_point(aes(y = N1, fill = !!sym(ColorScheme), shape = "N1", info = !!sym(SysUsed),
                   alpha = !!sym(ThreshLevel), size = !!sym(ThreshLevel)),
               color = "Black",pch=21, stroke = .15)+
    geom_point(aes(y = N2, fill = !!sym(ColorScheme), shape = "N2", info = !!sym(SysUsed),
                   alpha = !!sym(ThreshLevel), size = !!sym(ThreshLevel)),
               color = "Black",pch=24, stroke = .15)
  if(isFacet){
    GPlot = GPlot+
      facet_wrap(~Site, ncol = 1, scales = "free")
  }
  return(GPlot)
}

```


```{r }
DoRanking <- function(DF,IsGrouped,isFiltered){
  UsedDF <- DF%>%
    filter(!is.na(N1),!is.na(N2))
  if(IsGrouped){
    UsedDF <- UsedDF%>%
      group_by(Site)
  }
  if(isFiltered){
    UsedDF <- UsedDF%>%
      filter(Date<mdy("10/31/2021"))
  }
  RetDF <- UsedDF%>%
    arrange(Date)%>%
    mutate(N1 = ifelse(!is.na(N1),N1,0))%>%
    mutate(N2 = ifelse(!is.na(N2),N2,0))%>%
    mutate(N1RankLeft = rank(desc(N1 - lag(N1))),
         N1RankRight = rank(desc(N1 - lead(N1))),
         N2RankLeft = rank(desc(N2 - lag(N2))),
         N2RankRight = rank(desc(N2 - lead(N2))))%>%
    select(Date,Site,N1RankLeft,N1RankRight,N2RankLeft,N2RankRight,N1,N2)%>%
    mutate(MaxN1Rank = pmax(N1RankLeft,N1RankRight,N2RankLeft,N2RankRight))%>%
    select(Date,Site,MaxN1Rank,N1,N2)
  return(RetDF)
}

JoinDFFromList <- function(DFList, ByOptions, Names,CombVec){
  FullDF <- full_join(DFList[[1]],DFList[[2]], by = ByOptions)
  for (i in 3:length(DFList)){
    FullDF <- full_join(FullDF,DFList[[i]], by = ByOptions)
  }
  for(i in 1:length(DFList)){
    if(i %% 2 == 1){
      Prep = paste(CombVec, paste(rep(".x",(i+1)%/%2), collapse = ""), sep = "")
    }else{
      Prep = paste(CombVec, paste(rep(".y",(i+1)%/%2), collapse = ""), sep = "")
    }
    FullDF <- FullDF%>%
      rename(!!Names[[i]] := !!sym(Prep))
  }
  return(FullDF)
}
```


```{r DFPrep}
RankingDFUngroupedEarlyDay <- DoRanking(LIMSFullDF,FALSE,TRUE)
RankingDFgroupedEarlyDay <- DoRanking(LIMSFullDF,TRUE,TRUE)
RankingDFUngrouped <- DoRanking(LIMSFullDF,FALSE,FALSE)
RankingDFgrouped <- DoRanking(LIMSFullDF,TRUE,FALSE)

ToMergeDFs <- list(RankingDFUngroupedEarlyDay, RankingDFgroupedEarlyDay, RankingDFUngrouped, RankingDFgrouped)
RenameLists <- list("EarlyFull", "EarlySite", "AllFull", "AllSite")

MergedDF <- JoinDFFromList(
  ToMergeDFs, ByOptions = c("Date","Site","N1","N2"), Names = RenameLists, CombVec = "MaxN1Rank")

```


```{r Clear outliers, fig.width=9}
Method = "EarlySite"
#"EarlyFull", "EarlySite", "AllFull", "AllSite"

Thresh <- c(4)
UsedDF <- ThresholdGenDF(MergedDF, Method, Thresh)%>%
  rename(Threshold = ThresholdOutlier)%>%
  mutate(Threshold = ifelse((Threshold==1),"Strict","Inliers"))

PlotedGraphic <- ThresholdingPloting(UsedDF, SysUsed = "EarlySite",ThreshLevel = "Threshold")+
  #SiteColorScheme()+
  YLabN1_N2()

GGPlotlyWithScaling(PlotedGraphic, length(Thresh)+1)

#Explain N1,N2 diff in plot
#more discriptive title
#Text blacks to explain 
```


```{r FullOutliers, fig.height=10, fig.width=9}

Thresh <- c(4, 11)
UsedDF <- ThresholdGenDF(MergedDF, Method, Thresh)%>%
  rename(Threshold = ThresholdOutlier)%>%
  mutate(Threshold = ifelse((Threshold)==1,"Permissive",
                                   ifelse((Threshold==2),"Strict","Inliers")))
UsedDF%>%
  dplyr::filter(Threshold!="Inliers")%>%
  select(Date,Site, N1, N2, Threshold)#%>%
  #write.csv("RmdOutput/SendOutliersShortList.csv")

PlotedGraphic <- ThresholdingPloting(UsedDF, SysUsed = "EarlySite",ThreshLevel = "Threshold", isFacet =TRUE)+
  YLabN1_N2()

GGPlotlyWithScaling(PlotedGraphic, length(Thresh)+1)
```