---
title: "HFG Variance"
author: "Marlin"
date: "7/9/2021"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r warning = FALSE, message = FALSE,echo = FALSE}
library(ggpubr)
library(dplyr)

library(lubridate)

#Data Files and prep work
source("../../Scripts/GenPlotMaking.R")
source("../../Scripts/WasteWaterDataProccess.R")
source("../../Scripts/CasesDataProccess.R")
source("../../Scripts/HelperFunctions.R")

PathStarter="R:/"
HFGCasesFN  <-  paste0(PathStarter,"COVID-19_WastewaterAnalysis/data/raw/HighFreq_CaseData_2021-05-07.csv")
HFGWasteFN <-  paste0(PathStarter,"COVID-19_WastewaterAnalysis/data/raw/HFG data for stats corrected 071421.xlsx")
HFGPop <- paste0(PathStarter,"COVID-19_WastewaterAnalysis/data/raw/HFGPop.csv")

HFGWasteDF <- HFGWastePARSER(HFGWasteFN)
HFGCaseDF <- HFGCasesPARSER(HFGCasesFN)
  #mutate(across(c("ReportedCases", "EpisodeCases","",""), scale2))



Mod1 <- HFGWasteDF%>%
  group_by(Plant,Date,Filter)%>%
  summarise(ML=mean(log(N1GC)),VL=var(log(N1GC)),
            MN=mean(N1GC),VN=var(N1GC))

Mod2 <- Mod1%>%
  group_by(Plant,Date)%>%
  summarise(AL=mean(VL),BL=var(ML),
            A=mean(VN),B=var(MN))

Mod1%>%
  ggplot()+
  geom_point(aes(x=log(A),y=log(B)))

summary(lm(VL~I(VN/MN^2),data=Mod1))
summary(lm(VL~I(VN),data=Mod1))

Mod1%>%
  ggplot()+
  geom_point(aes(x=log(MN),y=ML))

Mod1%>%
  ggplot()+
  geom_point(aes(x=VN/MN^2,y=VL))
  
Mod1%>%
  filter(!is.na(ML),!is.na(VL))%>%
  mutate(VNTL=VN/MN^2)%>%
  mutate(A=abs(VL-VNTL)/VL)%>%
  ungroup()%>%
  summarise(ME=mean(A),FilterVar=fishmethods::combinevar(ML,VL,rep(3,length(ML)))[[2]])

plot(lm(VL~I(VN/MN^2)-1,data=Mod))

mean(Mod1$VL,na.rm=TRUE)


HFGWasteDF%>%
  mutate(LogN1=log(N1GC))%>%
  filter(!is.na(LogN1))%>%
  group_by(Plant,Date)%>%
  mutate(MeanDay=mean(LogN1))%>%
  group_by(Plant,Date,Filter)%>%
  mutate(MeanFilter=mean(LogN1))%>%
  ungroup()%>%
  # ggplot()+
  # geom_histogram(aes(x=LogN1-MeanFilter))
  summarise(VarFilter=var(LogN1-MeanDay),
            VarWell=var(LogN1-MeanFilter))
```


```{r fig.width=8, fig.height=8,echo = FALSE}

HFGWasteDF%>%
  ggplot()+
  aes(x=Date,y=N1GC)+
  geom_point(aes(color=as.factor(Well),shape=as.factor(Filter )))+
  facet_wrap(~Plant,scales = "free_y")

library(forecast)
library(zoo)
HFGWasteUSEDF <- HFGWasteDF%>%
  filter(Plant!="River Falls")%>%
  select(Date,Plant,N1GC,Filter)

LoessHFG <- HFGWasteUSEDF%>%
  group_by(Date,Plant)%>%
  summarise(N1Date=exp(mean(log(N1GC),na.rm=TRUE)))%>%
  ungroup()%>%
  arrange(Plant, Date) %>%
  mutate(RealN1=predict(loess(N1Date~as.numeric(Date),span=.7)))

HFGSumFilter <- HFGWasteUSEDF%>%
  group_by(Date,Plant,Filter)%>%
  summarise(N1Filt=exp(mean(log(N1GC),na.rm=TRUE)))

HFGDataMod <- full_join(full_join(LoessHFG,HFGWasteDF,by=c("Date","Plant")),
          HFGSumFilter,by=c("Date","Plant","Filter"))%>%
  select(Date,Plant,RealN1,N1Date,N1Filt,N1GC)

SSM <- function(Messured,Real){
  return(sum((log(Messured)-log(Real))^2,na.rm=TRUE)/(length(Real)-1))
}

SSM(HFGDataMod$N1GC,HFGDataMod$RealN1)



```
