---
title: "Madison Variance Diffrent Norms"
author: "Marlin"
date:  "`r format(Sys.time(), '%d %B, %Y, %H:%M')`"
output: 
  bookdown::html_document2: 
    code_folding: hide
    df_print: paged
params:
  BaseDir: Z:/
  #~/Box/DSI/Projects/wastewater/RD/
knit: (
  function(inputFile, encoding) { 
    FileComp = strsplit(inputFile,"/")[[1]];
    File = FileComp[length(FileComp)];
    File = substr(File,1,nchar(File)-4);
    pSubTitle <- paste0('RmdOutput/',Sys.Date(),"_",File);
    rmarkdown::render( 
      input       = inputFile, 
      encoding    = encoding, 
      output_file = pSubTitle) })
 
---

```{r}
library(dplyr)
library(lubridate)
library(zoo)
library(ggplot2)
library(limma)
library(ggpubr)
library(grid)
library(plotly)

#Data Files and prep work
source("../../../lib/DataProccess.R")
source("../../../lib/NormFuncs.R")
source("../../../lib/OutlierDetectionFuncs.R")
source("../../../lib/DataPathName.R")
BaseDir <- params$BaseDir#get the root of the directory where the data is stored
```


```{r Variance diffrent norms}
MadDF <- ParseData(LIMSWastePath(BaseDir))%>%
  filter(Site=="Madison")%>%
  mutate(FlagedOutliers = IdentifyOutliers(N1, Action = "Flag"))%>%
  filter(!FlagedOutliers)

RollingMadDF <- MadDF%>%
  mutate(RollN1 = rollapply(N1,width=35,FUN = mean, na.rm = TRUE, fill = NA),
         RollLogN1 = rollapply(log(N1),width=35,FUN = mean, na.rm = TRUE, fill = NA),
         RollSqrtN1 = rollapply((N1)**(1/2),width=35,FUN = mean, na.rm = TRUE, fill = NA))

RollingMadDF%>%
  ggplot(aes(x = Date))+
  geom_point(aes(y = N1, color = "N1"))+
  geom_line(aes(y = RollN1, color = "MA of N1"))

RollingMadDF%>%
  ggplot(aes(x = Date))+
  geom_point(aes(y = log(N1), color = "log N1"))+
  geom_line(aes(y = RollLogN1, color = "MA of log N1"))

RollingMadDF%>%
  ggplot(aes(x = Date))+
  geom_point(aes(y = sqrt(N1), color = "Root of N1"))+
  geom_line(aes(y = RollSqrtN1, color = "MA of Root N1"))
```

```{r RawVariance}
RollingMadDF%>%
  mutate(RollVar = rollapply(N1,width=30,FUN = var, na.rm = TRUE, fill = NA))%>%
  ggplot(aes(x = Date))+
  geom_line(aes(y = RollVar, color = "Var N1"))

RollingMadDF%>%
  mutate(RollVar = rollapply(log(N1),width=30,FUN = var, na.rm = TRUE, fill = NA))%>%
  ggplot(aes(x = Date))+
  geom_line(aes(y = RollVar, color = "Var log N1"))

RollingMadDF%>%
  mutate(RollVar = rollapply(N1**(1/2),width=30,FUN = var, na.rm = TRUE, fill = NA))%>%
  ggplot(aes(x = Date))+
  geom_line(aes(y = RollVar, color = "Var Root N1"))

```

```{r detrended ploting}
RollingDetrendedMadDF <- RollingMadDF%>%
  mutate(DiffN1 = N1 - RollN1,
         DiffLogN1 = log(N1) - RollLogN1,
         DiffRootN1 = sqrt(N1) - RollSqrtN1)

RollingDetrendedMadDF%>%
  ggplot(aes(x = Date))+
  geom_line(aes(y = DiffN1, color = "Detrended N1"))
RollingDetrendedMadDF%>%
  ggplot(aes(x = Date))+
  geom_line(aes(y = DiffLogN1, color = "Detrended log N1"))
RollingDetrendedMadDF%>%
  ggplot(aes(x = Date))+
  geom_line(aes(y = DiffRootN1, color = "Detrended root N1"))

```


```{r var ploting}


RollingDetrendedMadDF%>%
  mutate(RollVar = rollapply(N1/RollN1,width=30,FUN = var, na.rm = TRUE, fill = NA))%>%
  ggplot(aes(x = Date))+
  geom_line(aes(y = RollVar, color = "Var norm N1"))
RollingDetrendedMadDF%>%
  mutate(RollVar = rollapply(N1/RollLogN1,width=30,FUN = var, na.rm = TRUE, fill = NA))%>%
  ggplot(aes(x = Date))+
  geom_line(aes(y = RollVar, color = "Var norm log N1"))
RollingDetrendedMadDF%>%
  mutate(RollVar = rollapply(N1/RollSqrtN1,width=30,FUN = var, na.rm = TRUE, fill = NA))%>%
  ggplot(aes(x = Date))+
  geom_line(aes(y = RollVar, color = "Var norm Root N1"))
```


```{r Diff var norm ploting}


RollingDetrendedMadDF%>%
  mutate(RollVar = rollapply(DiffN1/RollN1,width=30,FUN = var, na.rm = TRUE, fill = NA))%>%
  ggplot(aes(x = Date))+
  geom_line(aes(y = RollVar, color = "Var norm N1"))
RollingDetrendedMadDF%>%
  mutate(RollVar = rollapply(exp(DiffLogN1)/RollLogN1,width=30,FUN = var, na.rm = TRUE, fill = NA))%>%
  ggplot(aes(x = Date))+
  geom_line(aes(y = RollVar, color = "Var norm log N1"))
RollingDetrendedMadDF%>%
  mutate(RollVar = rollapply(DiffRootN1**2/RollSqrtN1,width=30,FUN = var, na.rm = TRUE, fill = NA))%>%
  ggplot(aes(x = Date))+
  geom_line(aes(y = RollVar, color = "Var norm Root N1"))
```