---
title: "UWMad Analysis"
author: "Marlin"
date: "1/7/2022"
output: html_document
---

```{r set up markdown settings, echo=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE
)
```


```{r Start enviroment, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)
library(lmtest)
library(lubridate)
library(limma)
library(tidyr)
library(plotly)
  #library(lintr)
  #library(psych)

#Data Files and prep work
source("../../../lib/DataProccess.R")
```



```{r DF Set Up, echo=FALSE}
BaseDir <- params$BaseDir#get the root of the directory where the data is stored

#UpdatedHFGFN.csv
#HFGWasteData071421.csv

LIMSFN <- paste0(BaseDir, "COVID-19_WastewaterAnalysis/data/processed/LIMSWasteData_2021-06-30_17-40.csv")
MadisonCaseFN  <-  paste0(BaseDir, "COVID-19_WastewaterAnalysis/data/processed/MMSD_Cases_processed.csv")

DormNames <- c("Fall UW-LakeShore","Fall UW-Sellery","Spring UW-Sellery","Spring UW")

LatCaseDF <- ParseData(MadisonCaseFN)
LIMSDF <- ParseData(LIMSFN)%>%
  filter(Site %in% DormNames)%>%#Filter LIMS data to only select Sites
  select(Date, Site,  N1, N1Error)

#joining the two data frames together
FullDF <- inner_join(LatCaseDF,LIMSDF, by = c("Date","Site"))

#what does the data look like? 
tail(FullDF)
```

```{r Cases vs N1}
FullDF%>%
  ggplot()+
  aes(x=Date)+
  geom_line(aes(y=N1/1e5,color = "N1"))+
  geom_line(aes(y=Cases,color = "Cases"))+
  facet_wrap(~Site, scales = "free")

```