---
params:
  BaseDir: "Z:/"
title: "Variance Foundations"
author: "Marlin"
date: "11/15/2021"
output: html_document
---


```{r}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```


```{r Start enviroment, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)
# library(lmtest)
# library(lubridate)
# library(limma)
# library(tidyr)
# library(plotly)
  #library(lintr)


#Data Files and prep work
source("../../../lib/DataProccess.R")
```

This is a short document covering some ideas important to all three variance notebooks.

```{r DF Set Up, echo=FALSE}
BaseDir <- params$BaseDir#get the root of the directory where the data is stored
HFGWasteFN <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/processed/HFGWasteData071421.csv")


HFGDF <- ParseData(HFGWasteFN)%>% #Reads in preprocessed data into consistent format
  select(Site,Date,Filter,Well,N1)

tail(HFGDF) #Quick look into structure of data frame
```


The N1 data is log normal. This implies that most variance analysis that attempts to remove error from a base normal phenomenon should work primarily with log N1.

```{r N1 Distribution}

HFGDF%>% # Create a histogram of log N1
  ggplot()+
  aes(x = log(N1))%>%
  geom_histogram()

```