---
params:
  BaseDir: "./../../"
  IndVar: "N1"
  Site: "Madison"
  ##BaseDir: "/Volumes/byandell/"
title: "Heuristic exploration of the relationship between cases and viral load"
author: "Marlin Lee"
date: "1/28/2022"
output: 
  bookdown::html_document2: 
    fig_width: 8
    fig_height: 4
    code_folding: hide
bibliography: references.bib  
editor_options: 
  chunk_output_type: inline
knit: (
  function(inputFile, encoding) { 
    FileComp = strsplit(inputFile,"/")[[1]];
    File = FileComp[length(FileComp)];
    File = substr(File,1,nchar(File)-4);
    pSubTitle <- paste0('RmdOutput/',Sys.Date(),"_",File,"_Green_Bay");
    rmarkdown::render( 
      input       = inputFile, 
      encoding    = encoding, 
      output_file = pSubTitle) })
---


```{r Start enviroment, echo=FALSE, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(ggplot2)
library(lmtest)
library(lubridate)
library(limma)
library(tidyr)
library(plotly)
library(gridExtra)
library(data.table)
library(formattable)

#Data Files and prep work
source("../../lib/DataProccess.R")
source("../../lib/NormFuncs.R")
source("../../lib/OutlierDetectionFuncs.R")
source("../../lib/DataPathName.R")
BaseDir <- params$BaseDir#get the root of the directory where the data is stored
```



Files Used: 

`r LIMSCasePath(BaseDir)`

`r LIMSWastePath(BaseDir)`


```{r DF Set Up, echo=FALSE}

#Importing the Madison waste water data
LIMSFullDF <- ParseData(LIMSWastePath(BaseDir))%>%
  select(n1_lod,n2_lod,N1LOD,N2LOD,everything())
LIMSFullDF%>%
  filter(Site=="Madison")%>%
  ggplot(aes(y=N1,x=Date,color=N1LOD))+
  geom_point()#+
  scale_y_log10()

names(LIMSFullDF)
library(stringr)
unique(str_trim(tolower(LIMSFullDF$N1LOD)))
```