---
title: "Lat Model Work"
author: "Marlin"
date: "5/17/2021"
output: html_document
---

```{r}

knitr::opts_chunk$set(echo = TRUE,fig.width = 15,fig.height = 15)

```

```{r}

library(ggpubr)
library(dplyr)
library(formula.tools)

source("../../lib/GenPlotMaking.R")
source("../../lib/GenPlotMaking.R")
source("../../lib/WastewaterDataProccess.R")
source("../../lib/CasesDataProccess.R")
source("../../lib/HelperFunctions.R")


source("../Scripts/WasteShiny/PrepData.R", local = TRUE)


```

```{r, warning=FALSE}



SiteOptions <- unique(LIMSFullDF$Site)
SiteSubLists <- split(b,ceiling(seq_along(b)/9))


N1Plot <- function(SiteList){
  LIMSFullDF%>%
    filter(Site %in% SiteList)%>%
    mutate(Month=format(Date,"%B"))%>%
    ggplot()+geom_boxplot(aes(x=Month,y=N1),fill="light blue")+
    geom_point(aes(x=Month,y=mean(N1)),shape = 4)+
    facet_wrap(~Site)+
    scale_y_log10()
}
lapply(SiteSubLists,N1Plot)
```

```{r}


SiteLagHeatMap(LatCaseDF,LIMSFullDF,-14:14,"Site","Date","Cases~N1/BCoV")

```
