---
params:
  BaseDir: "R:/"
  ##BaseDir: "/Volumes/byandell/"
title: "No TS Correlation"
author: "Marlin"
date: "8/25/2021"
output: html_document
---

```{r set up markdown settings, echo=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)

```

```{r Start enviroment, message=FALSE, warning=FALSE}

library(ggpubr)
library(lubridate)
library(forecast)
library(lmtest)
library(lubridate)
library(limma)
library(zoo)
library(dplyr)
library(RColorBrewer)
library(tidyverse)
library(readxl)
#BiocManager::install("limma")

#Data Files and prep work
source("../../lib/GenPlotMaking.R")
source("../../lib/WasteWaterDataProccess.R")
source("../../lib/CasesDataProccess.R")



#ideas: scatter plot
#predicting future
#interplerating
#break things down to ideas
#SLD
#Rem
#make code more functional in design
#param code
#r script knit by param
#Direc structure for testing
#?Test first book
#remove unneeded branch
#add read me explaining presentation
#Store what rmd gen fig and perhaps encription
#**look into best practace
```

```{r DF Set Up, include=TRUE}
BaseDir <- params$BaseDir
LatMMSDFN  <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/MMSD_Cases.csv")
LatSpringDormFN  <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/SpringSemester_CasesByDorm.TSV")
LatFallDormFN  <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/FallSemester_CasesByDorm.TSV")

LIMSFN <- paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/WATERMICRO_WW_COVID-2021-06-30 17 40.xlsx")

HFGCasesFN  <-  paste0(BaseDir,"COVID-19_WastewaterAnalysis/data/raw/HighFreq_CaseData_2021-05-07.csv")

stopifnot(find("read.csv")=="package:utils")
LatCaseDF <- CovidDataPARSER(
  LatSpringDormFN, LatFallDormFN,MMSDFN = LatMMSDFN
  )%>% 
  
  filter(!is.na(Site)) %>%
  select(Date,Site,Cases,Tests,Per_pos)

HFGCaseDF <- HFGCasesPARSER(FN = HFGCasesFN)%>%
  filter(!is.na(Site))%>%
  mutate(Tests=NA,Per_pos=NA)%>%
  select(Date,Site,Cases=ReportedCases,Tests,Per_pos)%>%
  mutate(Cases = ifelse(Cases==-999,2.5,Cases))%>%
  filter(Site!="Madison")

FullCase <- bind_rows(HFGCaseDF,LatCaseDF)

FullCaseRoll <- RollPerPos(FullCase,"Cases","Tests",Facet="Site",n = 14)%>%
  filter(Per_pos!=-500)

LIMSFullDF <- LIMSDataPARSER(LIMSFN)%>%
  select(Date,Site, BCoV, N1,N1Error,N2, N2Error,PMMoV,Pop,FlowRate)
```

```{r}
LIMSDF <- BestCorDFGen(DFCases=FullCase,DFN1=LIMSFullDF,Site="Madison",keep=c("N1","N2"))
```

```{r LM binning}

#Creates 7 day mean weighting from gamma distribution explored elsewhere
WeightVec <- unlist(lapply((split(dgamma(1:21,scale =5.028338,shape =2.332779),c(rep(1,7),rep(2,7),rep(3,7))
              )),mean))
# 
# MadData <- MergedDF%>%
#     mutate(MovedCases = data.table::shift(Cases2,2))%>%
#     mutate(Week=as.numeric(Date+6)%/%7)%>%
#     group_by(Week)%>%
#     summarise(N1M=median(N1,na.rm=TRUE),CasesM=mean(MovedCases,na.rm = TRUE))
# A <- (lm(CasesM~N1M-1,data=MadData))
# B <- (lm(CasesM~N1M,data=MadData))



# CheckFunction(DaySmoothing=c(7,14),Show2=FALSE,Mat=TRUE,Ret="LM",CasesUsed="Cases4")
```

```{r Single Fit function}
#Makes model based on bined and shifted data. many return options.
BinRelationGen(LIMSDF,
               Weights=WeightVec,
               StartDate=1,
               DaySmoothing=14,
               Lag=2,
               Show=TRUE,
               Ret="R2",
               LogModel=TRUE,
               Intercept=FALSE)
#Ret options |Plot/R2/COR/PVal/LM|
```

```{r Matrix of single var fits function}
BinRelMatrix(DF=LIMSDF,
                                   Weights=WeightVec,
                                   DaySmoothing=c(7,14),
                                   Ret="PVal",#Options: R2,COR,PVal,All
                                   LogModel=TRUE,
                                   CasesUsed="BinningThenSLDCases",
                                   NSUsed="N1Mean",
                                   Intercept=FALSE,
                                   Mat=TRUE)[[1]]

```



```{r LM binning heatmap}
# max(R2Mat)
# max(CorMat)
#summary(BinRelationGen(7,7,2))
#CasesM
#Cases4
print("Binning -> SLD")
HeatMapCor(DF=LIMSDF,
           Weights=WeightVec,
           StartDate=0:7,
           DaySmoothing=c(7,14),
           Lag=-2:2,
           CasesUsed="BinningThenSLDCases")
print("SLD->Binning")
HeatMapCor(DF=LIMSDF,
           Weights=WeightVec,
           StartDate=0:7,
           DaySmoothing=c(7),
           Lag=-2:2,
           CasesUsed="SLDThenBinningCases")
print("Binning -> SLD late Start")

HeatMapCor(DF=LIMSDF,
           Weights=WeightVec,
           StartDate=0:7,
           DaySmoothing=c(7),
           Lag=-2:2,
           CasesUsed="SLDThenBinningCases",
           DateStart=mdy("11/13/2020"),
           ShowPlots=FALSE)

```

```{r Intercepters}
Intercepters <- c("MMSD-P2" ,"MMSD-P7" ,               
"MMSD-P8","MMSD-P11",                
"MMSD-P18")

IntercepterDFList <- lapply(Intercepters,BestCorDFGen,DFN1=LIMSFullDF,DFCases=FullCase,DateFilt=mdy("2/1/2021"),keep=c("N1","N1Error","N2","N2Error","Pop"))

print("Binning -> SLD")
lapply(IntercepterDFList,HeatMapCor,
           Weights=WeightVec, StartDate=0:7,DaySmoothing=c(7,14),Lag=-2:2,CasesUsed="BinningThenSLDCases",ShowPlots=FALSE)
print("SLD->Binning")
lapply(IntercepterDFList,HeatMapCor,
       Weights=WeightVec,StartDate=0:7,DaySmoothing=c(7,14),Lag=-2:2,CasesUsed="SLDThenBinningCases")
print("Binning -> SLD late Start")
lapply(IntercepterDFList,HeatMapCor,
       Weights=WeightVec,StartDate=0:7,DaySmoothing=c(7,14),Lag=-2:2,CasesUsed="SLDThenBinningCases",DateStart=mdy("11/13/2020"),ShowPlots=FALSE)

```


```{r Intercepters Norm}
PS1 <- 29547
PS2 <- 44073
PS3 <- 2426
PS4 <- 7081
PS5 <- 5247
PS6 <- 17087
PS7 <- 14921
PS8 <- 49860
PS9 <- 10726
PS10 <- 21353
PS11 <- 36734
PS12 <- 39257
PS13 <- 12493
PS14 <- 35937
PS15 <- 14917
PS16 <- 18370
PS17 <- 12430
PS18 <- 19356

P2Int <- PS1+PS2+PS3+PS4
P7Int <- PS6+PS7+PS9
P8Int <- PS5+PS8+PS15
P11Int <- PS11+PS12+PS16+PS17
P18Int <- PS10+PS13+PS14+PS18


Pops <- c(P2Int,
          P7Int,
          P8Int,
          P11Int,
          P18Int
          )

Show=FALSE
Smooth=7
IntercepterSlopes <- signif(bind_rows(
summary(BinRelationGen(IntercepterDFList[[1]],Weights=WeightVec,1,Smooth,-2,
                       Ret="LM",Show=Show))$coefficients[1:2],
summary(BinRelationGen(IntercepterDFList[[2]],Weights=WeightVec,5,Smooth,-2,
                       Ret="LM",Show=Show))$coefficients[1:2],
summary(BinRelationGen(IntercepterDFList[[3]],Weights=WeightVec,7,Smooth,-2,
                       Ret="LM",Show=Show))$coefficients[1:2],
summary(BinRelationGen(IntercepterDFList[[4]],Weights=WeightVec,1,Smooth,-2,
                       Ret="LM",Show=Show))$coefficients[1:2],
summary(BinRelationGen(IntercepterDFList[[5]],Weights=WeightVec,2,Smooth,-2,
                       Ret="LM",Show=Show))$coefficients[1:2]
),2)
rownames(IntercepterSlopes) <- Intercepters
colnames(IntercepterSlopes) <- c("Slope","SE")
IntercepterSlopes
Slopes <- IntercepterSlopes[,1]
plot(Pops,Slopes)
plot(Pops,Slopes/Pops)
#Flow for Norm. comp flow to pop
#hard to interp-mess around 
LocPops <- c(PS2,
          PS7,
          PS8,
          PS11,
          PS18)

LocPops/max(LocPops)
Pops/max(Pops)
```


```{r WWTP_exMadison}
Sites <- c("Hudson","Kenosha","Oshkosh","River Falls","Sun Prairie","Wausau")

SitesDFList <- lapply(Sites,BestCorDFGen,
                      DFN1=LIMSFullDF,DFCases=FullCase,DateFilt=mdy("2/1/2021"),keep=c("N1","N1Error","N2","N2Error","Pop"))

print("Binning -> SLD")
lapply(SitesDFList,HeatMapCor,
       Weights=WeightVec,StartDate=0:7,DaySmoothing=c(7,14),Lag=-2:2,CasesUsed="BinningThenSLDCases",ShowPlots=FALSE)
print("SLD->Binning")
lapply(SitesDFList,HeatMapCor,
       Weights=WeightVec,StartDate=0:7,DaySmoothing=c(7,14),Lag=-2:2,CasesUsed="SLDThenBinningCases")
print("Binning -> SLD late Start")
lapply(SitesDFList,HeatMapCor,
       Weights=WeightVec,StartDate=0:7,DaySmoothing=c(7,14),Lag=-2:2,CasesUsed="SLDThenBinningCases",DateStart=mdy("11/13/2020"),ShowPlots=FALSE)

summary(BinRelationGen(SitesDFList[[1]],Weights=WeightVec,0,7,-1,Ret="LM",Show=TRUE))
```

